-- Executar exclusivamente no Supabase de Questões.
create table if not exists public.law_structure (
  id bigint generated by default as identity primary key,
  law_id bigint not null references public.laws(id) on delete cascade,
  parent_id bigint null references public.law_structure(id) on delete cascade,
  tipo text not null check (tipo in ('titulo', 'capitulo', 'secao', 'subsecao')),
  nome text not null check (btrim(nome) <> ''),
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists law_structure_law_id_idx on public.law_structure(law_id);
create index if not exists law_structure_parent_id_idx on public.law_structure(parent_id);
create index if not exists law_structure_order_idx on public.law_structure(law_id, parent_id, ordem);
create index if not exists law_structure_type_idx on public.law_structure(law_id, tipo);

alter table public.questions add column if not exists structure_id bigint null references public.law_structure(id) on delete set null;
create index if not exists questions_structure_id_idx on public.questions(structure_id);

alter table public.law_structure enable row level security;
revoke all on public.law_structure from public, anon, authenticated;
grant select, insert, update, delete on public.law_structure to service_role;

create or replace function public.set_law_structure_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists law_structure_updated_at on public.law_structure;
create trigger law_structure_updated_at before update on public.law_structure for each row execute function public.set_law_structure_updated_at();
