"use client";

import { useCallback, useEffect, useState } from "react";
import { LegiscastAudioPlayer } from "@/components/legiscast-audio-player";
import { LegiscastPdfViewer } from "@/components/legiscast-pdf-viewer";
import { LegiscastCommentedArticles } from "@/components/legiscast-commented-articles";
import { StudentAreaTabs } from "@/components/student-area-tabs";
import type { ComentarioPublicoLegisBot } from "@/lib/legisbot/comentarios-publicos";
import type { LawStudyData } from "@/lib/law-study";
import { supabase } from "@/lib/supabase";

// Compatibilidade de incorporação: <LegiscastAudioPlayer slug={slug} embedded />

function LegiscastSkeleton() {
  return <div className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 sm:py-10" aria-busy="true" aria-label="Carregando LegisCast"><div className="h-28 animate-pulse rounded-3xl border border-blue-100 bg-slate-100" /><section className="mt-5 grid overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[minmax(0,1.65fr)_minmax(300px,.85fr)]"><div className="hidden h-[calc(72vh+5rem)] animate-pulse border-r border-slate-200 bg-slate-100 lg:block" /><div className="h-[calc(72vh+5rem)] animate-pulse bg-slate-50 p-6"><div className="h-8 w-40 rounded bg-slate-200" /><div className="mt-5 h-44 rounded-xl bg-slate-200" /><div className="mt-5 space-y-3 border-t border-slate-200 pt-4">{[1, 2, 3, 4, 5].map((item) => <div key={item} className="h-10 rounded bg-slate-200" />)}</div></div></section></div>;
}

export function LawLegiscastPageClient({ slug, recorteId, commentedArticles = [] }: { slug: string; recorteId: string | null; commentedArticles?: ComentarioPublicoLegisBot[] }) {
  const [study, setStudy] = useState<LawStudyData | null>(null); const [error, setError] = useState(""); const [pdfReady, setPdfReady] = useState(false); const [audioReady, setAudioReady] = useState(false); const [showPdf, setShowPdf] = useState(false); const [attempt, setAttempt] = useState(0);
  const completePdf = useCallback(() => setPdfReady(true), []); const completeAudio = useCallback(() => setAudioReady(true), []); const fail = useCallback((message: string) => setError(message), []);
  useEffect(() => { let active = true; setStudy(null); setError(""); setPdfReady(false); setAudioReady(false); void (async () => { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { const target = `/estudar/lei/${slug}/legiscast${recorteId ? `?recorte_id=${encodeURIComponent(recorteId)}` : ""}`; window.location.replace(`/conta?modo=login&retorno=${encodeURIComponent(target)}`); return; } try { const response = await fetch(`/api/aluno/estudar/lei/${encodeURIComponent(slug)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok || !body.study) throw new Error(body.message || "Não foi possível abrir o LegisCast desta lei."); if (active) { const loaded = body.study as LawStudyData; setStudy(loaded); setPdfReady(!loaded.materials.some((material) => material.type === "pdf" && material.accessAvailable && material.accessUrl)); } } catch (caught) { if (active) setError(caught instanceof Error ? caught.message : "Não foi possível abrir o LegisCast desta lei."); } })(); return () => { active = false; }; }, [slug, recorteId, attempt]);
  if (error) return <main className="mx-auto w-full max-w-6xl px-4 py-10"><StudentAreaTabs activeTab="leis" minhasLeisHref="/minhas-leis" /><section className="rounded-2xl border border-red-200 bg-white p-6 text-red-700"><p>{error}</p><button type="button" className="mt-4 rounded-xl bg-blue-700 px-4 py-2 font-black text-white" onClick={() => setAttempt((value) => value + 1)}>Tentar novamente</button></section></main>;
  if (!study) return <main><LegiscastSkeleton /></main>;
  const pdf = study.materials.find((material) => material.type === "pdf" && material.accessAvailable && material.accessUrl); const pageReady = pdfReady && audioReady;
  return <main className="relative mx-auto w-full max-w-7xl overflow-x-hidden px-4 py-6 sm:px-6 sm:py-10"><div className={pageReady ? "" : "invisible"}><StudentAreaTabs activeTab="leis" minhasLeisHref="/minhas-leis" /><header className="mb-5 rounded-3xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h1 className="mt-2 text-3xl font-black text-[#062a5f] sm:text-4xl">{study.law.title}</h1>{recorteId ? <p className="mt-2 text-sm text-slate-600">Contexto do recorte selecionado.</p> : null}</header><section className="grid min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[minmax(0,1.65fr)_minmax(300px,.85fr)]"><div className="hidden min-w-0 p-4 sm:p-6 lg:block">{pdf ? <LegiscastPdfViewer key={`pdf-${attempt}`} slug={slug} materialId={pdf.id} recorteId={recorteId} title={study.law.title} onReady={completePdf} onError={() => fail("Não foi possível carregar o PDF desta lei.")} /> : <p className="rounded-xl bg-slate-50 p-4 text-slate-600">O PDF desta lei não está disponível no momento.</p>}</div><div className="min-w-0 p-4 sm:p-6"><LegiscastAudioPlayer key={`audio-${attempt}`} slug={slug} embedded onReady={completeAudio} onError={fail} /></div><div className="border-t border-slate-200 p-4 lg:hidden"><button type="button" className="min-h-11 w-full rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 font-black text-blue-800" onClick={() => setShowPdf((value) => !value)} aria-expanded={showPdf}>{showPdf ? "Fechar legislação" : "Abrir legislação"}</button>{showPdf ? <div className="mt-4 min-w-0">{pdf ? <LegiscastPdfViewer slug={slug} materialId={pdf.id} recorteId={recorteId} title={study.law.title} /> : null}</div> : null}</div></section><LegiscastCommentedArticles comments={commentedArticles} recorteId={recorteId} /></div>{!pageReady ? <div className="absolute inset-x-4 top-6 sm:inset-x-6 sm:top-10"><LegiscastSkeleton /></div> : null}</main>;
}
