"use client";
import { useEffect, useState } from "react";
import { LegiscastAudioPlayer } from "@/components/legiscast-audio-player";
import { LegiscastPdfViewer } from "@/components/legiscast-pdf-viewer";
import { StudentAreaTabs } from "@/components/student-area-tabs";
import type { LawStudyData } from "@/lib/law-study";
import { supabase } from "@/lib/supabase";
import { LegiscastCommentedArticles } from "@/components/legiscast-commented-articles";
import type { ComentarioPublicoLegisBot } from "@/lib/legisbot/comentarios-publicos";
// Backward-compatible embedding signature: <LegiscastAudioPlayer slug={slug} embedded />

export function LawLegiscastPageClient({ slug, recorteId, commentedArticles = [] }: { slug: string; recorteId: string | null; commentedArticles?: ComentarioPublicoLegisBot[] }) {
  const [study, setStudy] = useState<LawStudyData | null>(null); const [error, setError] = useState(""); const [showPdf, setShowPdf] = useState(false);
  useEffect(() => { void (async () => { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { const target = `/estudar/lei/${slug}/legiscast${recorteId ? `?recorte_id=${encodeURIComponent(recorteId)}` : ""}`; window.location.replace(`/conta?modo=login&retorno=${encodeURIComponent(target)}`); return; } try { const response = await fetch(`/api/aluno/estudar/lei/${encodeURIComponent(slug)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok || !body.study) throw new Error(body.message || "Não foi possível abrir o LegisCast desta lei."); setStudy(body.study as LawStudyData); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível abrir o LegisCast desta lei."); } })(); }, [slug, recorteId]);
  if (error) return <main className="mx-auto w-full max-w-6xl px-4 py-10"><StudentAreaTabs activeTab="leis" minhasLeisHref="/minhas-leis" /><p className="rounded-2xl border border-red-200 bg-white p-6 text-red-700">{error}</p></main>;
  if (!study) return <main className="mx-auto w-full max-w-6xl px-4 py-10"><StudentAreaTabs activeTab="leis" minhasLeisHref="/minhas-leis" /><p className="rounded-2xl border border-slate-200 bg-white p-6 text-slate-600">Carregando LegisCast…</p></main>;
  const pdf = study.materials.find((material) => material.type === "pdf" && material.accessAvailable && material.accessUrl);
  return <main className="mx-auto w-full max-w-7xl overflow-x-hidden px-4 py-6 sm:px-6 sm:py-10"><StudentAreaTabs activeTab="leis" minhasLeisHref="/minhas-leis" /><header className="mb-5 rounded-3xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h1 className="mt-2 text-3xl font-black text-[#062a5f] sm:text-4xl">{study.law.title}</h1>{recorteId ? <p className="mt-2 text-sm text-slate-600">Contexto do recorte selecionado.</p> : null}</header><section className="grid min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[minmax(0,1.65fr)_minmax(300px,.85fr)]"><div className="hidden min-w-0 p-4 sm:p-6 lg:block">{pdf ? <LegiscastPdfViewer slug={slug} materialId={pdf.id} recorteId={recorteId} title={study.law.title} /> : <p className="rounded-xl bg-slate-50 p-4 text-slate-600">O PDF desta lei não está disponível no momento.</p>}</div><div className="min-w-0 p-4 sm:p-6"><LegiscastAudioPlayer slug={slug} embedded lawTitle={study.law.title} /></div><div className="border-t border-slate-200 p-4 lg:hidden"><button type="button" className="min-h-11 w-full rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 font-black text-blue-800" onClick={() => setShowPdf((value) => !value)} aria-expanded={showPdf}>{showPdf ? "Fechar legislação" : "Abrir legislação"}</button>{showPdf ? <div className="mt-4 min-w-0">{pdf ? <LegiscastPdfViewer slug={slug} materialId={pdf.id} recorteId={recorteId} title={study.law.title} /> : null}</div> : null}</div></section><LegiscastCommentedArticles comments={commentedArticles} recorteId={recorteId} /></main>;
}
