"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { StudentAreaTabs } from "@/components/student-area-tabs";
import { ANKI_PLATFORM_IDS, DEFAULT_ANKI_PLATFORM, getAnkiYoutubeEmbedUrl, type AnkiPlatformId } from "@/lib/anki-study";
import { resolveAnkiPlatformTutorials, type AnkiTutorialSettings } from "@/lib/anki-tutorial-settings";
import type { LawStudyData } from "@/lib/law-study";
import { supabase } from "@/lib/supabase";

type StudyContext = { recorteId: string | null; nome: string; questionCount: number };
const pageHref = (slug: string, scope: string | null) => `/estudar/lei/${encodeURIComponent(slug)}/anki${scope ? `?recorte_id=${encodeURIComponent(scope)}` : ""}`;
const customizeHref = (slug: string, scope: string | null) => `/estudar/lei/${encodeURIComponent(slug)}/anki/personalizar${scope ? `?recorte_id=${encodeURIComponent(scope)}` : ""}`;

export function LawAnkiPageClient({ slug, recorteId, settings }: { slug: string; recorteId: string | null; settings: AnkiTutorialSettings | null }) {
  const [study, setStudy] = useState<LawStudyData | null>(null); const [contexts, setContexts] = useState<StudyContext[]>([]); const [message, setMessage] = useState(""); const [downloading, setDownloading] = useState<string | null>(null); const [platform, setPlatform] = useState<AnkiPlatformId>(DEFAULT_ANKI_PLATFORM); const [tutorialOpen, setTutorialOpen] = useState(false);
  const tutorials = useMemo(() => resolveAnkiPlatformTutorials(settings), [settings]); const tutorial = tutorials[platform]; const videoUrl = useMemo(() => getAnkiYoutubeEmbedUrl(tutorial.videoUrl), [tutorial.videoUrl]);
  const selected = recorteId ? contexts.find((item) => item.recorteId === recorteId) ?? null : null; const hasFullLaw = contexts.some((item) => item.recorteId === null);
  useEffect(() => { let live = true; void (async () => { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { window.location.replace(`/conta?modo=login&retorno=${encodeURIComponent(pageHref(slug, recorteId))}`); return; } try { const headers = { Authorization: `Bearer ${token}` }; const [studyResponse, contextsResponse] = await Promise.all([fetch(`/api/aluno/estudar/lei/${encodeURIComponent(slug)}`, { headers, cache: "no-store" }), fetch(`/api/aluno/estudar/lei/${encodeURIComponent(slug)}/contextos`, { headers, cache: "no-store" })]); const result = await studyResponse.json().catch(() => ({})); const contextResult = await contextsResponse.json().catch(() => ({})); if (!studyResponse.ok) throw new Error(result.message || "Não foi possível carregar o material."); if (!contextsResponse.ok) throw new Error(contextResult.message || "Não foi possível carregar os baralhos disponíveis."); if (live) { setStudy(result.study ?? null); setContexts(Array.isArray(contextResult.contexts) ? contextResult.contexts : []); } } catch (error) { if (live) setMessage(error instanceof Error ? error.message : "Não foi possível carregar o material."); } })(); return () => { live = false; }; }, [slug, recorteId]);
  async function download(scope: string | null) { const key = scope ?? "full"; setDownloading(key); setMessage(""); try { const { data } = await supabase.auth.getSession(); const query = scope ? `?recorte_id=${encodeURIComponent(scope)}` : ""; const response = await fetch(`/api/aluno/estudar/lei/${encodeURIComponent(slug)}/anki/download${query}`, { headers: { Authorization: `Bearer ${data.session?.access_token ?? ""}` } }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(result.message || "Não foi possível gerar o deck."); } const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${slug}${scope ? `-${scope.slice(0, 8)}` : ""}.apkg`; link.click(); URL.revokeObjectURL(link.href); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível gerar o deck."); } finally { setDownloading(null); } }
  const openTutorial = () => { setTutorialOpen(true); window.setTimeout(() => document.getElementById("anki-tutorial")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); };
  if (message && !study) return <Frame><p role="alert" className="rounded-2xl border border-red-200 bg-white p-6 text-red-700 shadow-sm">{message}</p></Frame>;
  if (!study) return <Frame><p role="status" className="rounded-2xl border border-slate-200 bg-white p-6 text-slate-600 shadow-sm">Carregando seus baralhos…</p></Frame>;
  return <Frame><main className="grid min-w-0 gap-5 sm:gap-6">
    <header className="overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm"><div className="p-5 sm:p-8"><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black tracking-tight text-[#062a5f] sm:text-4xl">Estudar no <span className="text-blue-600">Anki</span></h1><Image src="/icons/anki.png" alt="Ícone do Anki" width={56} height={56} className="h-12 w-12 shrink-0 object-contain sm:h-14 sm:w-14" priority /></div><p className="mt-3 text-lg font-bold text-slate-800">Suas questões do Legis Questões também estão disponíveis no Anki!</p><div className="mt-5 max-w-3xl text-sm leading-relaxed text-slate-600 sm:text-base"><h2 className="font-black text-[#062a5f]">O que é o Anki?</h2><p className="mt-1">O Anki é um aplicativo de flashcards que organiza suas revisões automaticamente, ajudando você a memorizar o conteúdo estudado.</p><p className="mt-2">No LegisFlashcards, você pode baixar as mesmas questões do Legis Questões na versão Anki e estudá-las no computador ou celular, com revisões programadas.</p></div></div></header>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-2xl font-black text-[#062a5f]">Você já utiliza o Anki?</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Choice icon="🎓" title="Não, quero aprender" text="Aprenda a instalar o aplicativo, importar as questões e começar suas revisões." action="Começar do zero" onClick={openTutorial} primary /><Choice icon="✓" title="Sim, já utilizo" text="Acesse diretamente os baralhos disponíveis para esta legislação." action="Acessar meus baralhos" onClick={() => document.getElementById("anki-decks")?.scrollIntoView({ behavior: "smooth", block: "start" })} /></div></section>
    <section id="anki-tutorial" className="scroll-mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex gap-3"><Number value="1" /><div><h2 className="text-2xl font-black text-[#062a5f]">Passo a passo para começar</h2><p className="mt-1 text-slate-600">Siga as etapas abaixo para instalar o Anki e importar seus flashcards.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-3"><section><Step value="1" title="Escolha seu dispositivo" /><p className="mt-2 text-sm text-slate-600">Baixe o aplicativo adequado para o seu computador ou celular.</p><div className="mt-4 grid gap-2">{ANKI_PLATFORM_IDS.filter((item) => item !== "navegador").map((item) => <button key={item} type="button" onClick={() => { setPlatform(item); setTutorialOpen(true); }} className={`flex min-h-12 items-center justify-between rounded-xl border px-3 py-2 text-left text-sm font-black ${item === platform ? "border-blue-700 bg-blue-700 text-white" : "border-slate-200 text-slate-700 hover:border-blue-300 hover:bg-blue-50"}`}><span>{tutorials[item].label}</span><span className="text-xs">{tutorials[item].note}</span></button>)}</div></section><section className="md:col-span-2"><Step value="2" title="Aprenda a instalar e sincronizar" /><p className="mt-2 text-sm text-slate-600">Assista ao tutorial para aprender a instalar o Anki, importar seus flashcards e sincronizar suas revisões.</p>{tutorialOpen ? <div className="mt-4">{videoUrl ? <div className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-950"><iframe key={platform} src={videoUrl} title={`Tutorial do Anki para ${tutorial.label}`} className="aspect-video w-full" loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div> : <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">O tutorial para {tutorial.label} ainda será disponibilizado.</p>}<div className="mt-3 flex flex-col gap-3 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-[#062a5f]">{tutorial.label}</p><p className="text-sm text-slate-600">{tutorial.description}</p></div>{tutorial.officialUrl ? <a href={tutorial.officialUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white">{tutorial.buttonLabel}</a> : null}</div></div> : <button type="button" onClick={() => setTutorialOpen(true)} className="mt-4 min-h-11 rounded-xl border border-blue-700 px-4 py-2 font-black text-blue-700 hover:bg-blue-50">Ver tutorial</button>}</section></div></section>
    <section id="anki-decks" className="scroll-mt-5 rounded-3xl border border-blue-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex gap-3"><Number value="3" /><div><h2 className="text-2xl font-black text-[#062a5f]">Seus baralhos Anki</h2><p className="mt-1 font-bold text-[#062a5f]">{study.law.title}</p>{selected ? <><p className="mt-3 inline-flex rounded-full bg-blue-100 px-3 py-1 text-xs font-black tracking-wide text-blue-700">{selected.nome}</p><p className="mt-2 text-slate-600">{selected.questionCount} {selected.questionCount === 1 ? "questão disponível neste recorte." : "questões disponíveis neste recorte."}</p><p className="mt-2 text-slate-600">Baixe os flashcards deste recorte ou personalize seu baralho selecionando os conteúdos que deseja estudar.</p></> : <><p className="mt-1 text-slate-600">{study.law.totalFlashcards} {study.law.totalFlashcards === 1 ? "questão disponível nesta legislação." : "questões disponíveis nesta legislação."}</p><p className="mt-2 text-slate-600">Baixe os flashcards desta legislação ou personalize seu baralho selecionando os conteúdos que deseja estudar.</p></>}</div></div><div className="mt-5 grid gap-3 sm:flex sm:flex-wrap"><button type="button" disabled={downloading !== null || (recorteId ? !selected : !hasFullLaw)} onClick={() => void download(recorteId)} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-blue-700 px-5 py-3 font-black text-white disabled:opacity-50">{downloading ? "Gerando arquivo…" : "Baixar baralho"}</button><Link href={customizeHref(slug, selected ? recorteId : null)} className="inline-flex min-h-12 items-center justify-center rounded-xl border border-blue-700 px-5 py-3 font-black text-blue-700 hover:bg-blue-50">Personalizar meu baralho</Link></div>{message ? <p role="alert" className="mt-4 text-sm font-bold text-red-700">{message}</p> : null}<p className="mt-4 text-sm text-slate-500">Já possui uma versão anterior? Confira seus baralhos no Anki antes de importar novamente. A exclusão de um baralho pode apagar seu histórico de revisões.</p></section>
  </main></Frame>;
}
function Frame({ children }: { children: React.ReactNode }) { return <div className="mx-auto w-full max-w-6xl overflow-x-hidden px-3 py-5 sm:px-6 sm:py-8"><StudentAreaTabs activeTab="leis" minhasLeisHref="/minhas-leis" />{children}</div>; }
function Number({ value }: { value: string }) { return <span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-blue-700 text-sm font-black text-white">{value}</span>; }
function Step({ value, title }: { value: string; title: string }) { return <div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-700 text-xs font-black text-white">{value}</span><h3 className="font-black text-[#062a5f]">{title}</h3></div>; }
function Choice({ icon, title, text, action, onClick, primary = false }: { icon: string; title: string; text: string; action: string; onClick: () => void; primary?: boolean }) { return <article className={`rounded-2xl border p-5 ${primary ? "border-blue-100 bg-blue-50/50" : "border-slate-200 bg-white"}`}><div className="flex items-center gap-3"><span aria-hidden="true" className="text-4xl leading-none">{icon}</span><h3 className="text-xl font-black text-[#062a5f]">{title}</h3></div><p className="mt-3 text-slate-600">{text}</p><button type="button" onClick={onClick} className={`mt-5 inline-flex min-h-12 w-full items-center justify-center rounded-xl px-5 py-3 font-black ${primary ? "bg-blue-700 text-white hover:bg-blue-600" : "border border-blue-700 text-blue-700 hover:bg-blue-50"}`}>{action} <span className="ml-2 text-lg">→</span></button></article>; }
function Deck({ icon, title, text, busy, onDownload, featured = false }: { icon: string; title: string; text: string; busy: boolean; onDownload: () => void; featured?: boolean }) { return <article className={`rounded-2xl border p-5 ${featured ? "border-blue-300 bg-blue-50/50" : "border-slate-200"}`}><span aria-hidden="true" className="text-3xl">{icon}</span><h3 className="mt-3 text-lg font-black text-[#062a5f]">{title}</h3><p className="mt-1 text-sm text-slate-600">{text}</p><button type="button" disabled={busy} onClick={onDownload} className="mt-5 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-blue-700 px-4 py-3 font-black text-white hover:bg-blue-600 disabled:opacity-50">{busy ? "Gerando arquivo…" : "Baixar deck (.apkg)"}</button></article>; }
