"use client";

import { useEffect, useRef, useState } from "react";
import { legiscastPdfPositionKey, normalizeLegiscastPdfPage } from "@/lib/legiscast-pdf-position";
import { supabase } from "@/lib/supabase";

type OutlineItem = { title: string; dest: unknown; items?: OutlineItem[] };
type PdfDocument = { numPages: number; getPage: (page: number) => Promise<{ getViewport: (input: { scale: number }) => { width: number; height: number }; render: (input: { canvasContext: CanvasRenderingContext2D; viewport: { width: number; height: number } }) => { promise: Promise<void> } }>; getOutline: () => Promise<OutlineItem[] | null>; getDestination: (dest: string) => Promise<unknown>; getPageIndex: (ref: unknown) => Promise<number> };
type PdfJs = { GlobalWorkerOptions: { workerSrc: string }; getDocument: (source: string) => { promise: Promise<PdfDocument> } };

function storageKey(slug: string, recorteId: string | null) { return legiscastPdfPositionKey(slug, recorteId); }
function savedPage(slug: string, recorteId: string | null) { try { const page = Number(window.localStorage.getItem(storageKey(slug, recorteId))); return Number.isSafeInteger(page) && page > 0 ? page : 1; } catch { return 1; } }

export function LegiscastPdfViewer({ slug, materialId, recorteId, title }: { slug: string; materialId: number; recorteId: string | null; title: string }) {
  const viewportRef = useRef<HTMLDivElement>(null); const pagesRef = useRef<HTMLDivElement>(null); const documentRef = useRef<PdfDocument | null>(null); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [zoom, setZoom] = useState(1); const [outline, setOutline] = useState<OutlineItem[]>([]); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { let active = true; let objectUrl = ""; const render = async () => {
    setStatus("loading"); setOutline([]); setTotal(0); documentRef.current = null;
    try {
      const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) throw new Error("Sessão expirada.");
      const response = await fetch(`/api/aluno/estudar/lei/${encodeURIComponent(slug)}/materiais/${materialId}/download`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); if (!response.ok) throw new Error("Não foi possível carregar o PDF.");
      objectUrl = URL.createObjectURL(await response.blob()); const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs") as unknown as PdfJs; pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/legacy/build/pdf.worker.mjs", import.meta.url).toString(); const pdf = await pdfjs.getDocument(objectUrl).promise;
      if (!active) return; documentRef.current = pdf; setTotal(pdf.numPages); setOutline((await pdf.getOutline()) ?? []);
      const holder = pagesRef.current; const viewport = viewportRef.current; if (!holder || !viewport) throw new Error("Visor não disponível."); holder.replaceChildren();
      const desiredWidth = Math.max(280, viewport.clientWidth - 24);
      for (let number = 1; number <= pdf.numPages; number += 1) { const source = await pdf.getPage(number); const base = source.getViewport({ scale: 1 }); const scale = desiredWidth / base.width * zoom; const pageViewport = source.getViewport({ scale }); const canvas = document.createElement("canvas"); const ratio = window.devicePixelRatio || 1; canvas.width = Math.floor(pageViewport.width * ratio); canvas.height = Math.floor(pageViewport.height * ratio); canvas.style.width = `${Math.floor(pageViewport.width)}px`; canvas.style.height = `${Math.floor(pageViewport.height)}px`; canvas.dataset.page = String(number); const context = canvas.getContext("2d"); if (!context) throw new Error("Canvas indisponível."); context.scale(ratio, ratio); const wrapper = document.createElement("div"); wrapper.className = "flex justify-center bg-slate-100 p-2 sm:p-3"; wrapper.append(canvas); holder.append(wrapper); await source.render({ canvasContext: context, viewport: pageViewport }).promise; }
      if (!active) return; const restored = normalizeLegiscastPdfPage(savedPage(slug, recorteId), pdf.numPages); setPage(restored); requestAnimationFrame(() => holder.querySelector<HTMLElement>(`canvas[data-page="${restored}"]`)?.scrollIntoView({ block: "start" })); setStatus("ready");
    } catch { if (active) setStatus("error"); }
  }; void render(); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [slug, materialId, recorteId, zoom]);
  useEffect(() => { const viewport = viewportRef.current; if (!viewport || status !== "ready") return; const onScroll = () => { const canvases = [...viewport.querySelectorAll<HTMLCanvasElement>("canvas[data-page]")]; const top = viewport.getBoundingClientRect().top; const nearest = canvases.reduce((best, canvas) => Math.abs(canvas.getBoundingClientRect().top - top) < Math.abs(best.getBoundingClientRect().top - top) ? canvas : best, canvases[0]); const next = Number(nearest?.dataset.page); if (Number.isSafeInteger(next) && next !== page) { setPage(next); try { window.localStorage.setItem(storageKey(slug, recorteId), String(next)); } catch {} } }; viewport.addEventListener("scroll", onScroll, { passive: true }); return () => viewport.removeEventListener("scroll", onScroll); }, [page, slug, recorteId, status]);
  async function openOutline(dest: unknown) { const pdf = documentRef.current; if (!pdf || !dest) return; try { const resolved = typeof dest === "string" ? await pdf.getDestination(dest) : dest; const reference = Array.isArray(resolved) ? resolved[0] : null; if (!reference) return; const target = await pdf.getPageIndex(reference) + 1; pagesRef.current?.querySelector<HTMLElement>(`canvas[data-page="${target}"]`)?.scrollIntoView({ block: "start" }); } catch {} }
  const Outline = ({ items, depth = 0 }: { items: OutlineItem[]; depth?: number }) => <ul className="grid gap-1">{items.map((item, index) => <li key={`${depth}-${index}-${item.title}`}><button type="button" onClick={() => void openOutline(item.dest)} className="w-full rounded px-2 py-1 text-left text-sm font-semibold text-blue-800 hover:bg-blue-50" style={{ paddingLeft: `${8 + depth * 14}px` }}>{item.title || "Seção"}</button>{item.items?.length ? <Outline items={item.items} depth={depth + 1} /> : null}</li>)}</ul>;
  return <div className="mt-4 min-w-0"><div className="flex flex-wrap items-center justify-between gap-3 rounded-t-xl border border-slate-300 bg-slate-50 px-3 py-2"><p className="text-sm font-bold text-slate-700">{status === "ready" ? `Página ${page} de ${total}` : status === "error" ? "Não foi possível abrir o PDF" : "Carregando PDF…"}</p><div className="flex items-center gap-2"><button type="button" disabled={status !== "ready" || zoom <= 0.75} onClick={() => setZoom((value) => Math.max(0.75, Number((value - 0.25).toFixed(2))))} className="min-h-9 rounded border border-slate-300 bg-white px-3 font-black disabled:opacity-50" aria-label="Diminuir zoom">−</button><span className="text-sm font-bold text-slate-600">{Math.round(zoom * 100)}%</span><button type="button" disabled={status !== "ready" || zoom >= 2} onClick={() => setZoom((value) => Math.min(2, Number((value + 0.25).toFixed(2))))} className="min-h-9 rounded border border-slate-300 bg-white px-3 font-black disabled:opacity-50" aria-label="Aumentar zoom">+</button></div></div>{outline.length ? <details className="border-x border-t border-slate-300 bg-white"><summary className="cursor-pointer px-3 py-2 text-sm font-black text-[#062a5f]">Sumário do PDF</summary><div className="max-h-56 overflow-auto border-t border-slate-200 p-2"><Outline items={outline} /></div></details> : null}<div ref={viewportRef} className="h-[72vh] min-h-[520px] overflow-auto rounded-b-xl border border-slate-300 bg-slate-100" aria-label={`PDF: ${title}`}><div ref={pagesRef} /></div></div>;
}
