"use client";

import { useEffect, useRef, useState } from "react";
import { legiscastPdfPositionKey, normalizeLegiscastPdfPage } from "@/lib/legiscast-pdf-position";
import { authorizedLegiscastPdfPath, LegiscastPdfError, pdfFailureForHttpStatus, validateLegiscastPdfBytes } from "@/lib/legiscast-pdf";
import type { PdfHighlight, PdfHighlightAnchor, PdfHighlightRect } from "@/lib/legiscast-pdf-highlight";
import { supabase } from "@/lib/supabase";

type OutlineItem = { title: string; dest: unknown; items?: OutlineItem[] };
type PdfViewport = { width: number; height: number; scale?: number };
type PdfPage = { getViewport: (input: { scale: number }) => PdfViewport; getTextContent: () => Promise<unknown>; render: (input: { canvasContext: CanvasRenderingContext2D; viewport: PdfViewport }) => { promise: Promise<void> } };
type PdfDocument = { numPages: number; getPage: (page: number) => Promise<PdfPage>; getOutline: () => Promise<OutlineItem[] | null>; getDestination: (dest: string) => Promise<unknown>; getPageIndex: (ref: unknown) => Promise<number> };
type PdfJs = { GlobalWorkerOptions: { workerSrc: string }; getDocument: (source: string) => { promise: Promise<PdfDocument> }; TextLayer: new (input: { textContentSource: unknown; container: HTMLElement; viewport: PdfViewport }) => { render: () => Promise<void> } };

function storageKey(slug: string, recorteId: string | null) { return legiscastPdfPositionKey(slug, recorteId); }
function savedPage(slug: string, recorteId: string | null) { try { const page = Number(window.localStorage.getItem(storageKey(slug, recorteId))); return Number.isSafeInteger(page) && page > 0 ? page : 1; } catch { return 1; } }
function highlightsPath(slug: string, materialId: number) { return `/api/aluno/estudar/lei/${encodeURIComponent(slug)}/materiais/${materialId}/highlights`; }
async function sessionToken() { const { data } = await supabase.auth.getSession(); return data.session?.access_token ?? ""; }

async function fetchAuthorizedLegiscastPdf(slug: string, materialId: number, recorteId: string | null) {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  if (!token) throw new LegiscastPdfError("unauthorized", "Sessão expirada.");
  const response = await fetch(authorizedLegiscastPdfPath(slug, materialId, recorteId), { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" });
  const contentType = response.headers.get("content-type");
  const contentLength = response.headers.get("content-length");
  if (!response.ok) {
    console.warn("legiscast_pdf_response", { slug, materialId, hasRecorteId: Boolean(recorteId), status: response.status, contentType, contentLength });
    throw new LegiscastPdfError(pdfFailureForHttpStatus(response.status), "Não foi possível obter o PDF autorizado.", { status: response.status, contentType, contentLength });
  }
  const bytes = await response.arrayBuffer();
  console.info("legiscast_pdf_response", { slug, materialId, hasRecorteId: Boolean(recorteId), status: response.status, contentType, contentLength, size: bytes.byteLength });
  validateLegiscastPdfBytes(contentType, bytes);
  return new Blob([bytes], { type: "application/pdf" });
}

async function downloadAuthorizedPdf(slug: string, materialId: number, recorteId: string | null, title: string) {
  const blob = await fetchAuthorizedLegiscastPdf(slug, materialId, recorteId);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${title.replace(/[\\/:*?"<>|]/g, "-")}.pdf`;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

async function printAuthorizedPdf(slug: string, materialId: number, recorteId: string | null) {
  const blob = await fetchAuthorizedLegiscastPdf(slug, materialId, recorteId);
  const url = URL.createObjectURL(blob);
  const frame = document.createElement("iframe");
  frame.className = "fixed h-px w-px opacity-0";
  frame.src = url;
  frame.onload = () => {
    frame.contentWindow?.focus();
    frame.contentWindow?.print();
    setTimeout(() => { frame.remove(); URL.revokeObjectURL(url); }, 60000);
  };
  document.body.append(frame);
}

export function LegiscastPdfActions({ slug, materialId, recorteId, title, onExpand }: { slug: string; materialId: number; recorteId: string | null; title: string; onExpand: () => void }) {
  return <div className="grid grid-cols-3 gap-2" aria-label="Ações do PDF"><button type="button" onClick={() => void downloadAuthorizedPdf(slug, materialId, recorteId, title)} className="min-h-12 min-w-0 rounded-xl border border-blue-200 bg-white px-2 py-2 text-xs font-black text-blue-800">Baixar</button><button type="button" onClick={() => void printAuthorizedPdf(slug, materialId, recorteId)} className="min-h-12 min-w-0 rounded-xl border border-blue-200 bg-white px-2 py-2 text-xs font-black text-blue-800">Imprimir</button><button type="button" onClick={onExpand} className="min-h-12 min-w-0 rounded-xl border border-blue-200 bg-blue-50 px-2 py-2 text-xs font-black text-blue-800">Expandir</button></div>;
}

export function LegiscastPdfViewer({ slug, materialId, recorteId, title, targetPage, onReady, onError }: { slug: string; materialId: number; recorteId: string | null; title: string; targetPage?: number | null; onReady?: () => void; onError?: () => void }) {
  const viewportRef = useRef<HTMLDivElement>(null); const pagesRef = useRef<HTMLDivElement>(null); const documentRef = useRef<PdfDocument | null>(null); const objectUrlRef = useRef(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [zoom, setZoom] = useState(1); const [outline, setOutline] = useState<OutlineItem[]>([]); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading"); const [highlights, setHighlights] = useState<PdfHighlight[]>([]); const [highlightingAvailable, setHighlightingAvailable] = useState(true); const [selectionAction, setSelectionAction] = useState<{ page: number; selectedText: string; anchor: PdfHighlightAnchor; left: number; top: number } | null>(null); const [removeAction, setRemoveAction] = useState<{ id: string; left: number; top: number } | null>(null);
  useEffect(() => { let active = true; let objectUrl = ""; const render = async () => {
    setStatus("loading"); setOutline([]); setTotal(0); documentRef.current = null;
    try {
      objectUrl = URL.createObjectURL(await fetchAuthorizedLegiscastPdf(slug, materialId, recorteId)); objectUrlRef.current = objectUrl; const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs") as unknown as PdfJs; pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/legacy/build/pdf.worker.mjs", import.meta.url).toString(); let pdf: PdfDocument; try { pdf = await pdfjs.getDocument(objectUrl).promise; } catch (error) { throw new LegiscastPdfError("pdfjs_load_failed", "O PDF não pôde ser aberto.", { message: error instanceof Error ? error.message : "unknown" }); }
      if (!active) return; documentRef.current = pdf; setTotal(pdf.numPages); setOutline((await pdf.getOutline()) ?? []);
      const holder = pagesRef.current; const viewport = viewportRef.current; if (!holder || !viewport) throw new Error("Visor não disponível."); holder.replaceChildren();
      const desiredWidth = Math.max(280, viewport.clientWidth - 24);
      for (let number = 1; number <= pdf.numPages; number += 1) {
        const source = await pdf.getPage(number); const base = source.getViewport({ scale: 1 }); const scale = desiredWidth / base.width * zoom; const pageViewport = source.getViewport({ scale });
        const canvas = document.createElement("canvas"); const ratio = window.devicePixelRatio || 1; canvas.width = Math.floor(pageViewport.width * ratio); canvas.height = Math.floor(pageViewport.height * ratio); canvas.style.width = `${Math.floor(pageViewport.width)}px`; canvas.style.height = `${Math.floor(pageViewport.height)}px`; canvas.dataset.page = String(number);
        const context = canvas.getContext("2d"); if (!context) throw new Error("Canvas indisponível."); context.scale(ratio, ratio);
        const pageWrapper = document.createElement("div"); pageWrapper.className = "relative mx-auto bg-white"; pageWrapper.dataset.pdfPage = String(number); pageWrapper.style.width = canvas.style.width; pageWrapper.style.height = canvas.style.height; pageWrapper.append(canvas);
        const highlightLayer = document.createElement("div"); highlightLayer.className = "pdfHighlightLayer pointer-events-none absolute inset-0 z-30"; highlightLayer.dataset.highlightPage = String(number); pageWrapper.append(highlightLayer);
        const textLayer = document.createElement("div"); textLayer.className = "textLayer absolute inset-0 z-20 overflow-hidden text-transparent [line-height:1] selection:bg-blue-300/60"; textLayer.style.width = canvas.style.width; textLayer.style.height = canvas.style.height; pageWrapper.append(textLayer);
        const wrapper = document.createElement("div"); wrapper.className = "bg-slate-100 p-2 sm:p-3"; wrapper.append(pageWrapper); holder.append(wrapper);
        await source.render({ canvasContext: context, viewport: pageViewport }).promise;
        try { const textContent = await source.getTextContent(); await new pdfjs.TextLayer({ textContentSource: textContent, container: textLayer, viewport: pageViewport }).render(); } catch { textLayer.remove(); }
      }
      if (!active) return; const restored = normalizeLegiscastPdfPage(savedPage(slug, recorteId), pdf.numPages); setPage(restored); requestAnimationFrame(() => holder.querySelector<HTMLElement>(`canvas[data-page="${restored}"]`)?.scrollIntoView({ block: "start" })); setStatus("ready");
    } catch (error) { const details = error instanceof LegiscastPdfError ? { code: error.code, ...error.details } : { code: "unknown" }; console.error("legiscast_pdf_load_failed", { slug, materialId, hasRecorteId: Boolean(recorteId), ...details }); if (active) setStatus("error"); }
  }; void render(); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); if (objectUrlRef.current === objectUrl) objectUrlRef.current = ""; }; }, [slug, materialId, recorteId, zoom]);
  useEffect(() => { const viewport = viewportRef.current; if (!viewport || status !== "ready") return; const onScroll = () => { const canvases = [...viewport.querySelectorAll<HTMLCanvasElement>("canvas[data-page]")]; const top = viewport.getBoundingClientRect().top; const nearest = canvases.reduce((best, canvas) => Math.abs(canvas.getBoundingClientRect().top - top) < Math.abs(best.getBoundingClientRect().top - top) ? canvas : best, canvases[0]); const next = Number(nearest?.dataset.page); if (Number.isSafeInteger(next) && next !== page) { setPage(next); try { window.localStorage.setItem(storageKey(slug, recorteId), String(next)); } catch {} } }; viewport.addEventListener("scroll", onScroll, { passive: true }); return () => viewport.removeEventListener("scroll", onScroll); }, [page, slug, recorteId, status]);
  useEffect(() => { let active = true; void (async () => { try { const token = await sessionToken(); if (!token) throw new Error("missing_session"); const response = await fetch(highlightsPath(slug, materialId), { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); if (!response.ok) throw new Error(`http_${response.status}`); const body = await response.json(); if (active) { setHighlights(Array.isArray(body.highlights) ? body.highlights : []); setHighlightingAvailable(true); } } catch (error) { console.warn("legiscast_pdf_highlights_unavailable", { slug, materialId, message: error instanceof Error ? error.message : "unknown" }); if (active) setHighlightingAvailable(false); } })(); return () => { active = false; }; }, [slug, materialId]);
  useEffect(() => { if (status !== "ready") return; pagesRef.current?.querySelectorAll<HTMLElement>("[data-highlight-page]").forEach((layer) => { layer.replaceChildren(); const pageNumber = Number(layer.dataset.highlightPage); for (const highlight of highlights.filter((item) => item.page === pageNumber)) for (const rect of highlight.anchor.rects) { const marker = document.createElement("button"); marker.type = "button"; marker.className = "pointer-events-auto absolute cursor-pointer border-0 bg-yellow-300/45 p-0 hover:bg-yellow-300/60 focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-700"; marker.style.left = `${rect.x * 100}%`; marker.style.top = `${rect.y * 100}%`; marker.style.width = `${rect.width * 100}%`; marker.style.height = `${rect.height * 100}%`; marker.setAttribute("aria-label", `Destaque: ${highlight.selectedText.slice(0, 80)}`); marker.addEventListener("click", (event) => { event.stopPropagation(); setSelectionAction(null); setRemoveAction({ id: highlight.id, left: Math.min(window.innerWidth - 170, event.clientX), top: Math.min(window.innerHeight - 60, event.clientY + 8) }); }); layer.append(marker); } }); }, [highlights, status, zoom]);
  useEffect(() => { const viewport = viewportRef.current; if (!viewport || status !== "ready" || !highlightingAvailable) return; const inspectSelection = () => { const selection = window.getSelection(); if (!selection || selection.isCollapsed || !selection.rangeCount) { setSelectionAction(null); return; } const range = selection.getRangeAt(0); const start = range.startContainer.parentElement?.closest<HTMLElement>(".textLayer"); const end = range.endContainer.parentElement?.closest<HTMLElement>(".textLayer"); const wrapper = start?.closest<HTMLElement>("[data-pdf-page]"); if (!start || start !== end || !wrapper || !viewport.contains(wrapper)) { setSelectionAction(null); return; } const bounds = wrapper.getBoundingClientRect(); const selectedText = selection.toString().trim(); const rects: PdfHighlightRect[] = [...range.getClientRects()].filter((rect) => rect.width > 0 && rect.height > 0).map((rect) => ({ x: Math.max(0, (rect.left - bounds.left) / bounds.width), y: Math.max(0, (rect.top - bounds.top) / bounds.height), width: Math.min(1, rect.width / bounds.width), height: Math.min(1, rect.height / bounds.height) })); const actionBounds = range.getBoundingClientRect(); if (!selectedText || !rects.length) { setSelectionAction(null); return; } setRemoveAction(null); setSelectionAction({ page: Number(wrapper.dataset.pdfPage), selectedText, anchor: { version: 1, rects }, left: Math.min(window.innerWidth - 140, Math.max(8, actionBounds.left)), top: Math.min(window.innerHeight - 56, Math.max(8, actionBounds.bottom + 8)) }); }; viewport.addEventListener("mouseup", inspectSelection); viewport.addEventListener("touchend", inspectSelection); return () => { viewport.removeEventListener("mouseup", inspectSelection); viewport.removeEventListener("touchend", inspectSelection); }; }, [status, highlightingAvailable]);
  useEffect(() => { if (status !== "ready" || targetPage === null || targetPage === undefined) return; if (!Number.isSafeInteger(targetPage) || targetPage < 1 || targetPage > total) { console.warn("legiscast_pdf_page_navigation_ignored", { targetPage, total }); return; } const target = pagesRef.current?.querySelector<HTMLElement>(`canvas[data-page="${targetPage}"]`); if (!target) return; target.scrollIntoView({ block: "start" }); setPage(targetPage); try { window.localStorage.setItem(storageKey(slug, recorteId), String(targetPage)); } catch {} }, [targetPage, status, total, slug, recorteId]);
  useEffect(() => { if (status === "ready") onReady?.(); if (status === "error") onError?.(); }, [status, onReady, onError]);
  async function openOutline(dest: unknown) { const pdf = documentRef.current; if (!pdf || !dest) return; try { const resolved = typeof dest === "string" ? await pdf.getDestination(dest) : dest; const reference = Array.isArray(resolved) ? resolved[0] : null; if (!reference) return; const target = await pdf.getPageIndex(reference) + 1; pagesRef.current?.querySelector<HTMLElement>(`canvas[data-page="${target}"]`)?.scrollIntoView({ block: "start" }); } catch {} }
  async function authorizedPdfBlob() { return fetchAuthorizedLegiscastPdf(slug, materialId, recorteId); }
  async function downloadPdf() { await downloadAuthorizedPdf(slug, materialId, recorteId, title); }
  async function printPdf() { await printAuthorizedPdf(slug, materialId, recorteId); }
  async function createHighlight() { if (!selectionAction) return; try { const token = await sessionToken(); const response = await fetch(highlightsPath(slug, materialId), { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(selectionAction) }); const body = await response.json().catch(() => ({})); if (!response.ok || !body.highlight) throw new Error(`http_${response.status}`); setHighlights((current) => [...current, body.highlight as PdfHighlight]); window.getSelection()?.removeAllRanges(); setSelectionAction(null); } catch (error) { console.warn("legiscast_pdf_highlight_create_failed", { slug, materialId, message: error instanceof Error ? error.message : "unknown" }); } }
  async function removeHighlight() { if (!removeAction) return; try { const token = await sessionToken(); const response = await fetch(`${highlightsPath(slug, materialId)}/${encodeURIComponent(removeAction.id)}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`http_${response.status}`); setHighlights((current) => current.filter((highlight) => highlight.id !== removeAction.id)); setRemoveAction(null); } catch (error) { console.warn("legiscast_pdf_highlight_delete_failed", { slug, materialId, message: error instanceof Error ? error.message : "unknown" }); } }
  const Outline = ({ items, depth = 0 }: { items: OutlineItem[]; depth?: number }) => <ul className="grid gap-1">{items.map((item, index) => <li key={`${depth}-${index}-${item.title}`}><button type="button" onClick={() => void openOutline(item.dest)} className="w-full rounded px-2 py-1 text-left text-sm font-semibold text-blue-800 hover:bg-blue-50" style={{ paddingLeft: `${8 + depth * 14}px` }}>{item.title || "Seção"}</button>{item.items?.length ? <Outline items={item.items} depth={depth + 1} /> : null}</li>)}</ul>;
  return <div className="mt-0 min-w-0"><div className="flex flex-wrap items-center justify-between gap-3 rounded-t-xl border border-slate-300 bg-slate-50 px-3 py-2"><p className="text-sm font-bold text-slate-700">{status === "ready" ? `Página ${page} de ${total}` : status === "error" ? "Não foi possível abrir o PDF" : "Carregando PDF…"}</p><div className="flex items-center gap-2"><button type="button" disabled={status !== "ready" || zoom <= 0.75} onClick={() => setZoom((value) => Math.max(0.75, Number((value - 0.25).toFixed(2))))} className="min-h-9 rounded border border-slate-300 bg-white px-3 font-black disabled:opacity-50" aria-label="Diminuir zoom">−</button><span className="text-sm font-bold text-slate-600">{Math.round(zoom * 100)}%</span><button type="button" disabled={status !== "ready" || zoom >= 2} onClick={() => setZoom((value) => Math.min(2, Number((value + 0.25).toFixed(2))))} className="min-h-9 rounded border border-slate-300 bg-white px-3 font-black disabled:opacity-50" aria-label="Aumentar zoom">+</button><button type="button" onClick={() => void downloadPdf()} className="min-h-9 rounded border border-slate-300 bg-white px-3 text-sm font-bold text-blue-800">Baixar PDF</button><button type="button" onClick={() => void printPdf()} className="min-h-9 rounded border border-slate-300 bg-white px-3 text-sm font-bold text-blue-800">Imprimir</button></div></div><div ref={viewportRef} className="h-[52vh] min-h-[360px] overflow-auto overflow-x-auto rounded-b-xl border border-slate-300 bg-slate-100 sm:h-[62vh] sm:min-h-[460px] lg:h-[74vh] lg:min-h-[520px]" aria-label={`PDF: ${title}`}><div ref={pagesRef} /></div>{selectionAction ? <button type="button" onClick={() => void createHighlight()} className="fixed z-[150] min-h-10 rounded-full bg-yellow-300 px-3 text-sm font-black text-slate-900 shadow-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-700" style={{ left: selectionAction.left, top: selectionAction.top }}>🖍 Destacar</button> : null}{removeAction ? <button type="button" onClick={() => void removeHighlight()} className="fixed z-[150] min-h-10 rounded-full bg-white px-3 text-sm font-black text-red-700 shadow-lg ring-1 ring-red-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-700" style={{ left: removeAction.left, top: removeAction.top }}>Remover destaque</button> : null}</div>;
}
