"use client";

import { useEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";

type AudioTrack = { id: string; title: string; description: string | null; durationSeconds: number | null; url: string };
const speeds = [0.75, 1, 1.25, 1.5, 2];
const formatTime = (seconds: number) => { const value = Math.max(0, Math.floor(seconds)); return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, "0")}`; };

export function LegiscastAudioPlayer({ slug, embedded = false }: { slug: string; embedded?: boolean }) {
  const audioRef = useRef<HTMLAudioElement>(null); const [tracks, setTracks] = useState<AudioTrack[]>([]); const [index, setIndex] = useState(0); const [currentTime, setCurrentTime] = useState(0); const [duration, setDuration] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1); const [state, setState] = useState<"loading" | "ready" | "unavailable">("loading");
  const track = tracks[index];
  useEffect(() => { let active = true; void (async () => { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { if (active) setState("unavailable"); return; } const response = await fetch(`/api/aluno/leis/${encodeURIComponent(slug)}/legiscast`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok || !Array.isArray(body.audios) || !body.audios.length) { if (active) setState("unavailable"); return; } if (active) { setTracks(body.audios); setState("ready"); } })(); return () => { active = false; }; }, [slug]);
  useEffect(() => { const audio = audioRef.current; if (!audio || !track) return; const saved = Number(window.localStorage.getItem(`legiscast-audio:${track.id}`)); audio.currentTime = Number.isFinite(saved) && saved > 0 ? saved : 0; setCurrentTime(audio.currentTime); setDuration(track.durationSeconds ?? 0); }, [track]);
  useEffect(() => { if (audioRef.current) audioRef.current.playbackRate = speed; }, [speed]);
  if (state === "loading") return null;
  if (state === "unavailable") return <section className={embedded ? "min-w-0 border-t border-slate-200 pt-6" : "min-w-0 rounded-2xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"}><h2 className="text-3xl font-black text-[#062a5f]">🎧 LegisCast</h2><p className="mt-2 text-sm text-slate-600">Áudios do LegisCast ainda não disponíveis para esta lei.</p></section>;
  const seek = (delta: number) => { const audio = audioRef.current; if (!audio) return; audio.currentTime = Math.max(0, Math.min(audio.duration || duration, audio.currentTime + delta)); };
  const toggle = async () => { const audio = audioRef.current; if (!audio) return; if (audio.paused) await audio.play(); else audio.pause(); };
  return <section className={embedded ? "min-w-0 border-t border-slate-200 pt-6" : "min-w-0 rounded-2xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"} aria-labelledby="legiscast-audio-title"><h2 id="legiscast-audio-title" className="text-3xl font-black text-[#062a5f]">🎧 LegisCast</h2><p className="mt-2 text-sm text-slate-600">Ouça enquanto acompanha a legislação.</p><audio key={track?.id} ref={audioRef} src={track?.url} preload="metadata" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration)} onTimeUpdate={(event) => { const time = event.currentTarget.currentTime; setCurrentTime(time); try { window.localStorage.setItem(`legiscast-audio:${track.id}`, String(time)); } catch {} }} onEnded={() => { if (index < tracks.length - 1) setIndex(index + 1); }} /><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="font-black text-[#062a5f]">{track?.title}</p>{track?.description ? <p className="mt-1 text-sm text-slate-600">{track.description}</p> : null}<input className="mt-4 w-full accent-blue-700" aria-label="Posição da reprodução" type="range" min="0" max={Number.isFinite(duration) ? duration : 0} value={Math.min(currentTime, duration || 0)} onChange={(event) => { const audio = audioRef.current; if (audio) audio.currentTime = Number(event.target.value); }} /><div className="mt-1 flex justify-between text-xs font-semibold text-slate-500"><span>{formatTime(currentTime)}</span><span>{formatTime(duration)}</span></div><div className="mt-4 flex flex-wrap items-center gap-2"><button type="button" onClick={() => seek(-15)} className="min-h-11 rounded-lg border border-slate-300 px-3 font-bold text-slate-700">↺ 15s</button><button type="button" onClick={() => void toggle()} className="min-h-11 rounded-lg bg-blue-700 px-5 font-black text-white">{playing ? "Pausar" : "Reproduzir"}</button><button type="button" onClick={() => seek(15)} className="min-h-11 rounded-lg border border-slate-300 px-3 font-bold text-slate-700">15s ↻</button><label className="ml-auto flex min-h-11 items-center gap-2 text-sm font-bold text-slate-700">Velocidade<select value={speed} onChange={(event) => setSpeed(Number(event.target.value))} className="min-h-11 rounded-lg border border-slate-300 bg-white px-2">{speeds.map((value) => <option key={value} value={value}>{String(value).replace(".", ",")}x</option>)}</select></label></div></div>{tracks.length > 1 ? <ol className="mt-5 grid gap-2" aria-label="Playlist do LegisCast">{tracks.map((item, itemIndex) => <li key={item.id}><button type="button" onClick={() => setIndex(itemIndex)} aria-current={itemIndex === index ? "true" : undefined} className={itemIndex === index ? "w-full rounded-lg bg-blue-50 px-3 py-3 text-left font-black text-blue-800" : "w-full rounded-lg px-3 py-3 text-left font-bold text-slate-700 hover:bg-slate-50"}>{itemIndex + 1}. {item.title}</button></li>)}</ol> : null}</section>;
}
