"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { buildLegiscastStructureTree, type LegiscastStructureTreeItem } from "@/lib/legiscast-structure-tree";
import { supabase } from "@/lib/supabase";

type AudioTrack = { id: string; structureId: number | null; title: string; description: string | null; durationSeconds: number | null; url: string };
type Structure = { id: number; parent_id: number | null; tipo: string; nome: string; ordem: number | null };
const speeds = [0.75, 1, 1.25, 1.5, 2];
const formatTime = (seconds: number) => { const value = Math.max(0, Math.floor(seconds)); return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, "0")}`; };

function StructureSummary({ structure, tracks, index, onSelect }: { structure: Structure[]; tracks: AudioTrack[]; index: number; onSelect: (track: AudioTrack) => void }) {
  const tree = useMemo(() => buildLegiscastStructureTree(structure), [structure]);
  const tracksByStructure = useMemo(() => { const result = new Map<number, AudioTrack[]>(); for (const track of tracks) if (track.structureId !== null) result.set(track.structureId, [...(result.get(track.structureId) ?? []), track]); return result; }, [tracks]);
  const trackIndex = useMemo(() => new Map(tracks.map((track, position) => [track.id, position])), [tracks]);
  const unstructured = tracks.filter((track) => track.structureId === null);
  const render = (node: LegiscastStructureTreeItem, depth = 0): React.ReactNode => {
    const nodeTracks = tracksByStructure.get(node.id) ?? []; const first = nodeTracks[0]; const active = first ? trackIndex.get(first.id) === index : false;
    const label = <span className={node.tipo === "titulo" ? "font-black uppercase tracking-wide text-blue-950" : node.tipo === "capitulo" ? "font-bold text-slate-800" : "text-slate-600"}>{first ? "▶ " : ""}{node.nome}</span>;
    return <li key={node.id} style={{ paddingLeft: `${Math.min(depth, 3) * 12}px` }} className={node.tipo === "titulo" ? "mt-3 border-b border-blue-200 pb-2 pt-1 text-sm" : "pt-1 text-sm"}>{first ? <button type="button" onClick={() => onSelect(first)} aria-current={active ? "true" : undefined} className={active ? "w-full rounded-lg bg-blue-50 px-2 py-2 text-left ring-1 ring-blue-200" : "w-full rounded-lg px-2 py-2 text-left hover:bg-slate-50"}>{label}</button> : <div className="px-2 py-2">{label}</div>}{nodeTracks.slice(1).map((track) => <button key={track.id} type="button" onClick={() => onSelect(track)} aria-current={trackIndex.get(track.id) === index ? "true" : undefined} className={trackIndex.get(track.id) === index ? "ml-2 mt-1 w-[calc(100%-0.5rem)] rounded bg-blue-50 px-2 py-1 text-left text-xs font-bold text-blue-800" : "ml-2 mt-1 w-[calc(100%-0.5rem)] rounded px-2 py-1 text-left text-xs font-semibold text-slate-600 hover:bg-slate-50"}>▶ {track.title}</button>)}{node.children.length ? <ul>{node.children.map((child) => render(child, depth + 1))}</ul> : null}</li>;
  };
  return <nav className="mt-5 max-h-96 overflow-y-auto border-t border-slate-200 pt-2 lg:min-h-0 lg:flex-1 lg:max-h-none" aria-label="Playlist do LegisCast"><p className="px-2 pb-1 text-xs font-black uppercase tracking-wide text-slate-500">Sumário da lei</p><ul>{tree.map((node) => render(node))}</ul>{unstructured.length ? <section className="mt-3 border-t border-slate-200 pt-2"><p className="px-2 text-xs font-bold text-slate-500">Outros áudios</p>{unstructured.map((track) => <button key={track.id} type="button" onClick={() => onSelect(track)} aria-current={trackIndex.get(track.id) === index ? "true" : undefined} className={trackIndex.get(track.id) === index ? "mt-1 w-full rounded bg-blue-50 px-2 py-2 text-left text-sm font-bold text-blue-800" : "mt-1 w-full rounded px-2 py-2 text-left text-sm font-semibold text-slate-600 hover:bg-slate-50"}>▶ {track.title}</button>)}</section> : null}</nav>;
}

export function LegiscastAudioPlayer({ slug, embedded = false }: { slug: string; embedded?: boolean; lawTitle?: string }) {
  const audioRef = useRef<HTMLAudioElement>(null); const [tracks, setTracks] = useState<AudioTrack[]>([]); const [structure, setStructure] = useState<Structure[]>([]); const [index, setIndex] = useState(0); const [currentTime, setCurrentTime] = useState(0); const [duration, setDuration] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1); const [state, setState] = useState<"loading" | "ready" | "unavailable">("loading");
  const track = tracks[index];
  useEffect(() => { let active = true; void (async () => { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { if (active) setState("unavailable"); return; } const response = await fetch(`/api/aluno/leis/${encodeURIComponent(slug)}/legiscast`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok || !Array.isArray(body.audios) || !body.audios.length) { if (active) setState("unavailable"); return; } if (active) { setTracks(body.audios as AudioTrack[]); setStructure(Array.isArray(body.structure) ? body.structure as Structure[] : []); setState("ready"); } })(); return () => { active = false; }; }, [slug]);
  useEffect(() => { const audio = audioRef.current; if (!audio || !track) return; const saved = Number(window.localStorage.getItem(`legiscast-audio:${track.id}`)); audio.currentTime = Number.isFinite(saved) && saved > 0 ? saved : 0; setCurrentTime(audio.currentTime); setDuration(track.durationSeconds ?? 0); }, [track]);
  useEffect(() => { if (audioRef.current) audioRef.current.playbackRate = speed; }, [speed]);
  if (state === "loading") return null;
  if (state === "unavailable") return <section className={embedded ? "min-w-0 border-t border-slate-200 pt-6" : "min-w-0 rounded-2xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"}><h2 className="text-3xl font-black text-[#062a5f]">🎧 LegisCast</h2><p className="mt-2 text-sm text-slate-600">Áudios do LegisCast ainda não disponíveis para esta lei.</p></section>;
  const seek = (delta: number) => { const audio = audioRef.current; if (!audio) return; audio.currentTime = Math.max(0, Math.min(audio.duration || duration, audio.currentTime + delta)); };
  const toggle = async () => { const audio = audioRef.current; if (!audio) return; if (audio.paused) await audio.play(); else audio.pause(); };
  const select = (next: AudioTrack) => { const nextIndex = tracks.findIndex((item) => item.id === next.id); if (nextIndex >= 0) setIndex(nextIndex); };
  return <section className={embedded ? "flex min-w-0 flex-col border-t border-slate-200 pt-6 lg:h-[calc(72vh+5rem)]" : "min-w-0 rounded-2xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"} aria-labelledby="legiscast-audio-title"><h2 id="legiscast-audio-title" className="text-3xl font-black text-[#062a5f]">🎧 LegisCast</h2><p className="mt-2 text-sm text-slate-600">Ouça nossos hosts enquanto acompanha a legislação.</p><audio key={track?.id} ref={audioRef} src={track?.url} preload="metadata" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration)} onTimeUpdate={(event) => { const time = event.currentTarget.currentTime; setCurrentTime(time); try { window.localStorage.setItem(`legiscast-audio:${track.id}`, String(time)); } catch {} }} onEnded={() => { if (index < tracks.length - 1) setIndex(index + 1); }} /><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="font-black text-[#062a5f]">{track?.title}</p>{track?.description ? <p className="mt-1 text-sm text-slate-600">{track.description}</p> : null}<input className="mt-4 w-full accent-blue-700" aria-label="Posição da reprodução" type="range" min="0" max={Number.isFinite(duration) ? duration : 0} value={Math.min(currentTime, duration || 0)} onChange={(event) => { const audio = audioRef.current; if (audio) audio.currentTime = Number(event.target.value); }} /><div className="mt-1 flex justify-between text-xs font-semibold text-slate-500"><span>{formatTime(currentTime)}</span><span>{formatTime(duration)}</span></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><button type="button" onClick={() => seek(-15)} className="min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 font-bold text-slate-700">↺ 15s</button><button type="button" onClick={() => void toggle()} className="min-h-14 min-w-32 rounded-xl bg-blue-700 px-5 text-lg font-black text-white">{playing ? "Pausar" : "Reproduzir"}</button><button type="button" onClick={() => seek(15)} className="min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 font-bold text-slate-700">15s ↻</button><label className="col-span-3 mt-1 flex min-h-11 items-center justify-end gap-2 border-t border-slate-200 pt-3 text-sm font-bold text-slate-700">Velocidade<select value={speed} onChange={(event) => setSpeed(Number(event.target.value))} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3">{speeds.map((value) => <option key={value} value={value}>{String(value).replace(".", ",")}x</option>)}</select></label></div></div><StructureSummary structure={structure} tracks={tracks} index={index} onSelect={select} /></section>;
}
