"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { RecordsContestImage } from "@/components/records-contest-image";
import type { RecordsEntry, RecordsRankingData } from "@/lib/records-ranking-server";
import { supabase } from "@/lib/supabase";

const medal = (position: number) => position === 1 ? "🥇" : position === 2 ? "🥈" : position === 3 ? "🥉" : `${position}º`;
const rowStyle = (entry: RecordsEntry) => entry.isCurrentUser ? "border-cyan-300/80 bg-cyan-300/15" : entry.position === 1 ? "border-amber-300/60 bg-amber-300/10" : entry.position === 2 ? "border-slate-200/40 bg-slate-100/[.07]" : entry.position === 3 ? "border-orange-300/45 bg-orange-300/[.08]" : "border-cyan-200/10 bg-slate-950/35";

function RankingRow({ entry }: { entry: RecordsEntry }) {
  return <li className={`grid grid-cols-[3.8rem_minmax(0,1fr)_auto] items-center gap-2 rounded-xl border px-3 py-3 sm:grid-cols-[5rem_minmax(0,1fr)_9rem] sm:px-5 ${rowStyle(entry)}`}><strong className={`font-mono ${entry.position <= 3 ? "text-lg" : "text-base"} ${entry.position === 1 ? "text-amber-300" : entry.position === 2 ? "text-slate-200" : entry.position === 3 ? "text-orange-300" : "text-cyan-200"}`}>{medal(entry.position)}</strong><span className="min-w-0 truncate font-bold text-slate-100">{entry.publicName}{entry.isCurrentUser ? <em className="ml-2 not-italic text-xs font-black text-cyan-300">VOCÊ</em> : null}</span><strong className="text-right font-mono text-base text-cyan-300 sm:text-lg">{entry.score.toLocaleString("pt-BR")}</strong></li>;
}

export function RecordsRankingPage({ initial }: { initial: RecordsRankingData }) {
  const [data, setData] = useState(initial); const [personalStatus, setPersonalStatus] = useState<"visitor" | "loading" | "ready" | "error">("visitor");
  useEffect(() => { let live = true; void (async () => { const { data: sessionData } = await supabase.auth.getSession(); const token = sessionData.session?.access_token; if (!live || !token) return; setPersonalStatus("loading"); const response = await fetch(`/api/recordes/${encodeURIComponent(initial.contest.productSlug)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); if (!response.ok) { if (live) setPersonalStatus("error"); return; } const next = await response.json() as RecordsRankingData; if (live) { setData(next); setPersonalStatus("ready"); } })(); return () => { live = false; }; }, [initial.contest.productSlug]);
  const loginReturn = `/recordes/${encodeURIComponent(data.contest.productSlug)}`; const outsideTop10 = Boolean(data.personal && data.personal.position > 10);
  return <main className="min-h-screen bg-[#020817] px-4 py-10 text-slate-100 sm:px-6 lg:py-16"><div className="mx-auto max-w-5xl">
    <section className="relative isolate overflow-hidden rounded-[2rem] border border-cyan-300/35 bg-[#031126] px-6 py-8 shadow-[0_0_70px_rgba(14,165,233,.16)] sm:px-10 sm:py-10"><div aria-hidden="true" className="absolute inset-0 -z-10 opacity-60 [background-image:linear-gradient(rgba(56,189,248,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(56,189,248,.06)_1px,transparent_1px)] [background-size:26px_26px]" /><Link href="/recordes" className="inline-flex text-sm font-bold text-cyan-300 underline underline-offset-4">← Voltar para Records</Link><div className="mt-6 flex items-center gap-4 sm:gap-5"><RecordsContestImage src={data.contest.contestImageUrl} alt={`Imagem ${data.contest.shortName}`} className="h-16 w-16 shrink-0 rounded-2xl border border-cyan-200/25 object-cover object-right sm:h-20 sm:w-20" /><div><p className="font-mono text-[10px] font-black tracking-[.26em] text-cyan-300">UNIDADE DE ELITE</p><h1 className="mt-1 text-4xl font-black tracking-tight text-white sm:text-5xl">{data.contest.shortName}</h1><p className="mt-1 text-base text-slate-300">Ranking Legis Questões</p></div></div></section>
    <section className="mt-6 rounded-[2rem] border border-cyan-300/30 bg-[#071329] p-4 shadow-[0_0_42px_rgba(6,182,212,.1)] sm:mt-8 sm:p-7"><div className="border-b border-cyan-200/20 pb-5"><p className="font-mono text-xs font-black tracking-[.3em] text-cyan-300">HIGH SCORES</p><h2 className="mt-1 text-xl font-black text-white sm:text-2xl">Top 10 · {data.contest.productName}</h2></div><div className="mt-3 grid grid-cols-[3.8rem_minmax(0,1fr)_auto] gap-2 px-3 py-2 text-[11px] font-black tracking-wider text-cyan-200/70 sm:grid-cols-[5rem_minmax(0,1fr)_9rem] sm:px-5"><span>POS.</span><span>JOGADOR</span><span className="text-right">SCORE</span></div>{data.ranking.length ? <ol className="space-y-2">{data.ranking.map((entry) => <RankingRow key={entry.position} entry={entry} />)}</ol> : <p className="py-12 text-center text-sm text-slate-400">Ainda não há participantes neste ranking.</p>}</section>
    {personalStatus === "ready" ? <>{outsideTop10 ? <section className="mt-6 rounded-3xl border border-amber-300/35 bg-[#111827] p-5 sm:p-7"><p className="text-xs font-black tracking-[.2em] text-amber-200">SUA POSIÇÃO</p><p className="mt-2 font-mono text-3xl font-black text-white">#{data.personal?.position} <span className="text-cyan-300">· {data.personal?.score.toLocaleString("pt-BR")} pts</span></p><p className="mt-1 text-sm text-slate-300">{data.personal?.publicName}</p>{data.nearby.length ? <><h3 className="mt-6 border-t border-amber-200/15 pt-5 text-sm font-black uppercase tracking-wider text-amber-100">Posições próximas</h3><ol className="mt-3 space-y-2">{data.nearby.map((entry) => <RankingRow key={entry.position} entry={entry} />)}</ol></> : null}</section> : !data.personal ? <section className="mt-6 rounded-3xl border border-amber-300/35 bg-[#111827] p-5 sm:p-7"><p className="font-black text-white">Você ainda não possui posição neste ranking.</p></section> : null}<section className="mt-6 rounded-3xl border border-cyan-200/20 bg-[#071329] p-5 sm:p-7"><div><p className="font-mono text-xs font-black tracking-[.25em] text-cyan-300">SEU DESEMPENHO</p><h2 className="mt-1 text-xl font-black text-white">Pontuação por lei</h2></div><ul className="mt-5 space-y-3">{data.laws.map((law) => <li key={law.slug} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-cyan-200/10 bg-slate-950/35 p-4"><div className="min-w-0"><p className="font-bold text-white">{law.name}</p><p className="mt-1 font-mono text-sm text-cyan-300">{law.score.toLocaleString("pt-BR")} pts</p></div><Link href={law.href} className="shrink-0 rounded-xl border border-cyan-200/30 px-4 py-2 text-sm font-black text-cyan-200 hover:bg-cyan-300/10">{law.actionLabel} →</Link></li>)}</ul>{!data.laws.length ? <p className="mt-5 text-sm text-slate-400">Este produto não possui leis vinculadas para compor o ranking.</p> : null}</section></> : personalStatus === "loading" ? <p className="mt-6 text-center text-sm text-slate-400">Carregando seu desempenho…</p> : personalStatus === "error" ? <p className="mt-6 text-center text-sm text-slate-400">Não foi possível carregar seu desempenho agora.</p> : <p className="mt-6 text-center text-sm text-slate-400">Já estuda conosco? <Link className="font-bold text-cyan-300 underline underline-offset-4" href={`/conta?modo=login&retorno=${encodeURIComponent(loginReturn)}`}>Entre para ver sua posição.</Link></p>}
  </div></main>;
}
