"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { StudentAreaTabs } from "@/components/student-area-tabs";
import type { StudentExam } from "@/lib/student-exams";
import { supabase } from "@/lib/supabase";
async function api(init?: RequestInit) { const { data } = await supabase.auth.getSession(); return fetch("/api/aluno/editais", { ...init, headers: { Authorization: `Bearer ${data.session?.access_token ?? ""}`, "Content-Type": "application/json", ...init?.headers } }); }
export function StudentExamClient() {
  const [editais, setEditais] = useState<StudentExam[]>([]), [selected, setSelected] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await api(); if (response.status === 401) { window.location.replace("/conta?modo=login&retorno=%2Fmeu-edital"); return; } const body = await response.json(); if (!response.ok || !Array.isArray(body.editais)) throw new Error(body.message); setEditais(body.editais); setSelected((current) => body.editais.some((exam: StudentExam) => exam.id === current) ? current : body.editais[0]?.id ?? ""); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar seus editais."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const current = editais.find((exam) => exam.id === selected) ?? null;
  const completed = current?.leis.filter((law) => law.campaignStatus === "concluida").length ?? 0, total = current?.leis.length ?? 0, percent = total ? completed / total * 100 : 0;
  const next = current?.leis.find((law) => law.campaignStatus !== "concluida") ?? null;
  async function change(action: string, payload: Record<string, unknown>) { const response = await api({ method: "PATCH", body: JSON.stringify({ action, ...payload }) }); if (!response.ok) { const body = await response.json().catch(() => null); setError(body?.message || "Não foi possível atualizar o edital."); return; } await load(); }
  async function move(index: number, direction: number) { if (!current || current.tipo !== "personalizado") return; const ids = current.leis.map((law) => law.id); const target = index + direction; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; await change("reorder", { leiIds: ids }); }
  return <main className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6"><header><p className="font-bold text-blue-700">Área do aluno</p><h1 className="mt-1 text-3xl font-black text-[#062a5f] sm:text-4xl">Meu Edital</h1></header><StudentAreaTabs activeTab="edital" minhasLeisHref="/minhas-leis" meuEditalHref="/meu-edital" />{loading ? <p className="mt-6 rounded-2xl border bg-white p-6">Carregando seu edital…</p> : null}{error ? <p className="mt-6 rounded-2xl border border-red-200 bg-white p-6 text-red-700">{error}</p> : null}{!loading && !error && !current ? <section className="mt-6 rounded-3xl border bg-white p-8 text-center"><h2 className="text-2xl font-black text-[#062a5f]">Monte seu edital</h2><Link className="mt-5 inline-flex rounded-xl bg-blue-700 px-5 py-3 font-black text-white" href="/minhas-leis">Ir para Legis Questões</Link></section> : null}{current ? <div className="mt-6 grid gap-6"><section className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm"><p className="text-sm font-bold text-slate-600">{current.nome}</p><h2 className="mt-2 text-3xl font-black text-[#062a5f]">{completed}/{total} concluídas</h2><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${percent}%` }} /></div><p className="mt-3 font-semibold text-slate-600">{total > 0 && completed === total ? "Edital concluído" : next ? <>Próximo estudo: <Link className="text-blue-700 underline" href={`/estudar/lei/${encodeURIComponent(next.slug)}`}>{next.titulo}</Link></> : null}</p></section><ol className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{current.leis.map((law, index) => <li key={law.id} className="flex flex-col gap-3 border-b border-slate-100 p-4 last:border-0 sm:flex-row sm:items-center"><span className="font-black text-slate-400">{index + 1}.</span><Link href={`/estudar/lei/${encodeURIComponent(law.slug)}`} className="min-w-0 flex-1 text-lg font-black text-[#062a5f] underline decoration-blue-200 underline-offset-4">{law.titulo}</Link><span className={`text-sm font-black ${law.campaignStatus === "concluida" ? "text-emerald-700" : law.campaignStatus === "em_andamento" ? "text-amber-700" : "text-slate-500"}`}>{law.campaignStatus === "concluida" ? "Concluída" : law.campaignStatus === "em_andamento" ? "Em andamento" : "Não iniciada"}</span>{current.tipo === "personalizado" ? <span className="flex gap-2"><button disabled={index === 0} onClick={() => void move(index, -1)} className="min-h-10 px-2 font-black text-blue-700 disabled:opacity-30">↑</button><button disabled={index === current.leis.length - 1} onClick={() => void move(index, 1)} className="min-h-10 px-2 font-black text-blue-700 disabled:opacity-30">↓</button><button onClick={() => void change("remove", { leiId: law.id })} className="min-h-10 px-2 font-bold text-red-700">Remover</button></span> : null}</li>)}</ol></div> : null}</main>;
}
