import "server-only";
import { obterAdministrador } from "@/lib/admin-auth";
import { parseQuestionDraft, type QuestionDraft } from "@/lib/admin-questoes";
import { effectiveAnkiSlug, parseAnkiTxt, validateImportSlug } from "@/lib/anki-txt-import";
import { parseLegisApkg } from "@/lib/anki-apkg-import";
import type { ImportedQuestion, ImportIssue } from "@/lib/imported-question";
import { compareQuestionStructureNames, planQuestionDeckStructure, type QuestionStructureNode } from "@/lib/questoes-structure";
import { getSupabaseServerClient } from "@/lib/supabase-server";
import { descendantsForScope, questionsInScope } from "@/lib/law-question-scope-resolution";

export class AdminQuestoesError extends Error { constructor(public status: number, message: string) { super(message); } }
type StructureType = "titulo" | "capitulo" | "secao" | "subsecao";
type Law = { id: number; slug: string; titulo: string; nome_curto: string | null; codigo: string | null };
const types: StructureType[] = ["titulo", "capitulo", "secao", "subsecao"];
const parents: Record<StructureType, StructureType | null | "law"> = { titulo: "law", capitulo: null, secao: "capitulo", subsecao: "secao" };
const questionFields = "id,lei_id,structure_id,pergunta,resposta,justificativa,assunto,legislacao,ordem,titulo,total_artigos,slug,ultima_alteracao_legislativa,capitulo,secao,subsecao,artigo,ativo,created_at,updated_at";
const db = () => getSupabaseServerClient();
async function requireAdmin() { if (!await obterAdministrador()) throw new AdminQuestoesError(401, "Autenticação administrativa obrigatória."); }
function fail(context: string, error: { message?: string } | null): never { console.error("Falha na administração de questões", { context, message: error?.message ?? null }); throw new AdminQuestoesError(502, "Não foi possível concluir a operação no banco de questões."); }
function slug(value: unknown) { if (typeof value !== "string" || !/^[a-z0-9-]{1,160}$/.test(value)) throw new AdminQuestoesError(400, "Lei inválida."); return value; }
function id(value: unknown) { if (!Number.isSafeInteger(Number(value)) || Number(value) < 1) throw new AdminQuestoesError(400, "Estrutura inválida."); return Number(value); }
function qid(value: unknown) { if (typeof value !== "string" || !/^[0-9a-f-]{36}$/i.test(value)) throw new AdminQuestoesError(400, "Questão inválida."); return value; }
function text(value: unknown, label: string) { if (typeof value !== "string" || !value.trim() || value.trim().length > 500) throw new AdminQuestoesError(400, `${label} inválido.`); return value.trim(); }
function type(value: unknown) { if (!types.includes(value as StructureType)) throw new AdminQuestoesError(400, "Tipo estrutural inválido."); return value as StructureType; }
function optionalId(value: unknown) { return value === null || value === undefined || value === "" ? null : id(value); }
function draft(value: unknown) { try { return parseQuestionDraft(value as Record<string, unknown>); } catch (error) { throw new AdminQuestoesError(400, error instanceof Error ? error.message : "Dados da questão inválidos."); } }
async function law(lawSlug: string): Promise<Law> { const r = await db().from("leis").select("id,slug,titulo,nome_curto,codigo").eq("slug", slug(lawSlug)).eq("ativo", true).maybeSingle(); if (r.error) fail("carregar_lei", r.error); if (!r.data) throw new AdminQuestoesError(404, "Lei ativa não encontrada no banco principal."); return r.data as Law; }
async function structure(leiId: number) { const r = await db().from("law_structure").select("id,lei_id,parent_id,tipo,nome,ordem,ativo,created_at,updated_at").eq("lei_id", leiId).eq("ativo", true).order("ordem").order("id"); if (r.error) fail("listar_estrutura", r.error); return [...(r.data ?? [])].sort(compareQuestionStructureNames) as QuestionStructureNode[]; }
async function validateStructure(leiId: number, structureId: number | null) { if (!structureId) return; const r = await db().from("law_structure").select("id").eq("id", structureId).eq("lei_id", leiId).eq("ativo", true).maybeSingle(); if (r.error) fail("validar_estrutura", r.error); if (!r.data) throw new AdminQuestoesError(422, "A estrutura selecionada não pertence à lei ativa."); }
function values(law: Law, d: QuestionDraft) { return { lei_id: law.id, structure_id: d.structure_id, pergunta: d.pergunta, resposta: d.resposta, justificativa: d.justificativa, assunto: d.assunto, legislacao: d.legislacao, ordem: d.ordem, titulo: d.titulo, total_artigos: d.total_artigos, slug: law.slug, capitulo: d.capitulo, secao: d.secao, subsecao: d.subsecao, artigo: d.artigo }; }

export async function listAdminQuestionLaws() { await requireAdmin(); const r = await db().from("leis").select("id,slug,titulo,nome_curto,codigo").eq("ativo", true).order("ordem").order("titulo"); if (r.error) fail("listar_leis", r.error); return r.data ?? []; }
export async function listLawQuestionScopes(lawSlug: string) { await requireAdmin(); const current = await law(lawSlug); const [scopes, nodes, questions] = await Promise.all([db().from("recortes_leis").select("id,nome,descricao,ativo,created_at,updated_at,recortes_leis_estrutura(structure_id)").eq("lei_id", current.id).order("nome"), structure(current.id), db().from("questions").select("id,structure_id").eq("lei_id", current.id).eq("ativo", true)]); if (scopes.error) fail("listar_recortes", scopes.error); if (questions.error) fail("contar_recortes", questions.error); return { law: current, structure: nodes, questions: questions.data ?? [], unstructured_questions: (questions.data ?? []).filter((question) => question.structure_id === null).length, recortes: (scopes.data ?? []).map((scope) => { const structure_ids = ((scope.recortes_leis_estrutura ?? []) as Array<{ structure_id: number }>).map((item) => item.structure_id); return { ...scope, structure_ids, question_count: questionsInScope(questions.data ?? [], descendantsForScope(nodes, structure_ids)).length }; }) }; }
export async function saveLawQuestionScope(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const name = text(body.nome, "Nome do recorte"); const description = typeof body.descricao === "string" ? body.descricao.trim() : ""; const ids = Array.isArray(body.structure_ids) ? body.structure_ids.map(Number).filter((item) => Number.isSafeInteger(item) && item > 0) : []; const suppliedId = typeof body.id === "string" && /^[0-9a-f-]{36}$/i.test(body.id) ? body.id : null; const result = await db().rpc("admin_salvar_recorte_lei", { p_recorte_id: suppliedId, p_lei_id: current.id, p_nome: name, p_descricao: description, p_ativo: body.ativo !== false, p_structure_ids: ids }); if (result.error || !result.data) fail("salvar_recorte", result.error); return { id: result.data, lei_id: current.id, nome: name, descricao: description, structure_ids: ids }; }
export async function listQuestionContent(lawSlug: string) { const current = await law(lawSlug); const r = await db().from("questions").select(questionFields).eq("lei_id", current.id).eq("ativo", true).order("ordem").order("created_at").order("id"); if (r.error) fail("listar_questoes", r.error); return { law: current, questions: r.data ?? [], structure: await structure(current.id) }; }
export async function listAdminQuestions(lawSlug: string) { await requireAdmin(); return listQuestionContent(lawSlug); }
export async function createAdminQuestion(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const d = draft(body.data); await validateStructure(current.id, d.structure_id); const r = await db().from("questions").insert({ ...values(current, d), ativo: true }).select(questionFields).single(); if (r.error || !r.data) fail("criar_questao", r.error); return r.data; }
export async function updateAdminQuestion(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const d = draft(body.data); await validateStructure(current.id, d.structure_id); const r = await db().from("questions").update(values(current, d)).eq("id", qid(body.id)).eq("lei_id", current.id).eq("ativo", true).select(questionFields).maybeSingle(); if (r.error) fail("editar_questao", r.error); if (!r.data) throw new AdminQuestoesError(404, "Questão ativa não encontrada para a lei selecionada."); return r.data; }
export async function updateQuickAdminQuestion(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const question = await db().from("questions").select(questionFields).eq("id", qid(body.id)).eq("lei_id", current.id).eq("ativo", true).maybeSingle(); if (question.error) fail("ler_questao", question.error); if (!question.data) throw new AdminQuestoesError(404, "Questão ativa não encontrada para a lei selecionada."); const input = body.data as Record<string, unknown>; if (!input || Object.keys(input).some((key) => !["pergunta","resposta","justificativa","assunto","legislacao","ordem"].includes(key))) throw new AdminQuestoesError(400, "A edição rápida não permite alterar a estrutura da questão."); return updateAdminQuestion({ law_slug: current.slug, id: question.data.id, data: { ...question.data, ...input } }); }
export async function deactivateAdminQuestion(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const r = await db().from("questions").update({ ativo: false }).eq("id", qid(body.id)).eq("lei_id", current.id).eq("ativo", true).select("id").maybeSingle(); if (r.error) fail("desativar_questao", r.error); if (!r.data) throw new AdminQuestoesError(404, "Questão ativa não encontrada para a lei selecionada."); return { id: r.data.id, ativo: false }; }
export async function reactivateAdminQuestion(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const r = await db().from("questions").update({ ativo: true }).eq("id", qid(body.id)).eq("lei_id", current.id).eq("ativo", false).select("id").maybeSingle(); if (r.error) fail("reativar_questao", r.error); if (!r.data) throw new AdminQuestoesError(404, "Questão inativa não encontrada para a lei selecionada."); return { id: r.data.id, ativo: true }; }

export async function createStructureNode(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const nodeType = type(body.tipo); const parentId = optionalId(body.parent_id); if (parentId) { const r = await db().from("law_structure").select("tipo").eq("id", parentId).eq("lei_id", current.id).eq("ativo", true).maybeSingle(); if (r.error) fail("validar_pai", r.error); if (!r.data || parents[nodeType] !== r.data.tipo) throw new AdminQuestoesError(422, "Relação estrutural inválida para esta lei."); } else if (parents[nodeType] !== "law" && nodeType !== "capitulo") throw new AdminQuestoesError(422, "Este nível exige um nível pai compatível."); const r = await db().from("law_structure").insert({ lei_id: current.id, parent_id: parentId, tipo: nodeType, nome: text(body.nome, "Nome"), ordem: optionalId(body.ordem) ?? 0, ativo: true }).select().single(); if (r.error || !r.data) fail("criar_estrutura", r.error); return r.data; }
export async function updateStructureNode(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const r = await db().from("law_structure").update({ nome: text(body.nome, "Nome"), ordem: optionalId(body.ordem) ?? 0 }).eq("id", id(body.id)).eq("lei_id", current.id).eq("ativo", true).select().maybeSingle(); if (r.error) fail("editar_estrutura", r.error); if (!r.data) throw new AdminQuestoesError(404, "Estrutura ativa não encontrada."); return r.data; }
export async function deactivateStructureNode(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const r = await db().from("law_structure").update({ ativo: false }).eq("id", id(body.id)).eq("lei_id", current.id).eq("ativo", true).select("id").maybeSingle(); if (r.error) fail("desativar_estrutura", r.error); if (!r.data) throw new AdminQuestoesError(404, "Estrutura ativa não encontrada."); return r.data; }
export async function structureDeletionSummary(body: Record<string, unknown>) { await requireAdmin(); const current = await law(String(body.law_slug)); const rootId = id(body.id); const nodes = await structure(current.id); const root = nodes.find((node) => node.id === rootId); if (!root) throw new AdminQuestoesError(404, "Estrutura ativa não encontrada."); const children = new Map<number, QuestionStructureNode[]>(); for (const node of nodes) if (node.parent_id !== null) children.set(node.parent_id, [...(children.get(node.parent_id) ?? []), node]); const descendants = (node: QuestionStructureNode): QuestionStructureNode[] => [node, ...(children.get(node.id) ?? []).flatMap(descendants)]; const affected = descendants(root); const ids = affected.map((node) => node.id); const q = await db().from("questions").select("id,structure_id").eq("lei_id", current.id).eq("ativo", true).in("structure_id", ids); if (q.error) fail("resumo_exclusao", q.error); const direct = q.data?.filter((question) => question.structure_id === root.id).length ?? 0; return { id: root.id, nome: root.nome, tipo: root.tipo, ids, descendentes: affected.length - 1, por_tipo: Object.fromEntries(types.map((item) => [item, affected.filter((node) => node.id !== root.id && node.tipo === item).length])), questoes: q.data?.length ?? 0, questoes_diretas: direct, questoes_descendentes: (q.data?.length ?? 0) - direct, pode_excluir: !(q.data?.length) }; }
export async function deleteStructureNode(body: Record<string, unknown>) { const summary = await structureDeletionSummary(body); if (!summary.pode_excluir) throw new AdminQuestoesError(422, `Este item não pode ser excluído porque existem ${summary.questoes} questões vinculadas a ele ou aos seus subitens.`); const current = await law(String(body.law_slug)); const r = await db().from("law_structure").delete().eq("id", summary.id).eq("lei_id", current.id).select("id").maybeSingle(); if (r.error) fail("excluir_estrutura", r.error); if (!r.data) throw new AdminQuestoesError(404, "Estrutura ativa não encontrada."); return { ...summary, excluido: true }; }

function withSlug(rows: ImportedQuestion[], lawSlug: string) { return rows.map((row) => ({ ...row, slug: effectiveAnkiSlug(row.slug, lawSlug) })); }
function diagnostics(issues: ImportIssue[], items: Array<{ line: number; deck: string; ordem: string; pergunta: string; status: string; motivo: string | null }>) { return [...issues.map((issue) => ({ severity: "erro", line: issue.line, deck: issue.deck?.join("::") ?? "", ordem: issue.ordem ?? "", pergunta: issue.pergunta ?? "", field: issue.field ?? "arquivo", received: issue.received ?? "", expected: issue.expected ?? "", motivo: issue.message })), ...items.filter((item) => item.status === "erro").map((item) => ({ severity: "erro", line: item.line, deck: item.deck, ordem: item.ordem, pergunta: item.pergunta, field: "estrutura", received: item.deck, expected: "Deck/subdeck com níveis reconhecidos", motivo: item.motivo ?? "Estrutura inválida." }))]; }
async function preview(lawSlug: string, parsed: { rows: ImportedQuestion[]; issues: ImportIssue[] }, apkg?: Record<string, unknown>) { const current = await law(lawSlug); const check = validateImportSlug(parsed.rows, current.slug); if (!check.valid) throw new AdminQuestoesError(422, check.message ?? "O arquivo não corresponde à legislação selecionada."); const rows = withSlug(parsed.rows, current.slug); const [existing, nodes] = await Promise.all([db().from("questions").select("pergunta,slug,ordem").eq("lei_id", current.id), structure(current.id)]); if (existing.error) fail("previsualizar", existing.error); const plan = planQuestionDeckStructure(rows, nodes); const decks = new Map(plan.decks.map((deck) => [deck.line, deck])); const known = new Set((existing.data ?? []).map((row) => `${row.slug}\u0000${row.ordem}\u0000${row.pergunta}`)); const items = rows.map((row) => { const deck = decks.get(row.line); const duplicate = known.has(`${row.slug}\u0000${row.ordem}\u0000${row.pergunta}`); return { line: row.line, deck: row.deck.join("::"), ordem: row.ordem, pergunta: row.pergunta, status: deck?.error ? "erro" : duplicate ? "duplicada" : "nova", motivo: deck?.error ?? null }; }); const errors = diagnostics(parsed.issues, items); const structurePreview = plan.nodes.map((node) => ({ path: node.path, tipo: node.tipo, status: node.existingId === null ? "nova" : "existente" })); return { law: current, slug: check, total: rows.length, issues: parsed.issues, errors, items, structure: { items: structurePreview, existentes: structurePreview.filter((node) => node.status === "existente").length, novas: structurePreview.filter((node) => node.status === "nova").length }, summary: { novas: items.filter((item) => item.status === "nova").length, duplicadas: items.filter((item) => item.status === "duplicada").length, erros: errors.length }, ...(apkg ? { apkg } : {}) }; }
export async function previewAnkiImport(body: Record<string, unknown>) { await requireAdmin(); if (typeof body.text !== "string" || body.text.length > 20_000_000) throw new AdminQuestoesError(400, "Arquivo TXT inválido ou grande demais."); try { return preview(slug(body.law_slug), parseAnkiTxt(body.text)); } catch (error) { if (error instanceof AdminQuestoesError) throw error; throw new AdminQuestoesError(400, error instanceof Error ? error.message : "TXT inválido."); } }
export async function previewApkgImport(lawSlug: unknown, file: File) { await requireAdmin(); if (!file.name.toLowerCase().endsWith(".apkg") || !file.size || file.size > 100_000_000) throw new AdminQuestoesError(400, "Arquivo APKG inválido ou grande demais."); let parsed; try { parsed = await parseLegisApkg(new Uint8Array(await file.arrayBuffer())); } catch (error) { throw new AdminQuestoesError(400, error instanceof Error ? error.message : "APKG inválido."); } if (parsed.media.some((media) => media.referenced)) throw new AdminQuestoesError(422, "O APKG possui mídia referenciada. O suporte a mídia ainda não faz parte desta etapa."); return preview(slug(lawSlug), { rows: parsed.rows, issues: parsed.issues }, { rootDecks: parsed.rootDecks ?? [], subdecks: parsed.subdecks ?? [], notes: parsed.notes ?? 0, cards: parsed.cards ?? 0, recognizedModels: parsed.recognizedModels ?? [], unrecognizedModels: parsed.unrecognizedModels ?? [], media: parsed.media ?? [], samples: parsed.rows.slice(0, 5) }); }
async function persist(lawSlug: string, rows: ImportedQuestion[], previewData: Awaited<ReturnType<typeof preview>>, ignored = 0) { if (!previewData.slug.valid || previewData.errors.length) throw new AdminQuestoesError(422, "A importação possui linhas inválidas ou estruturas não encontradas."); const current = await law(lawSlug); const newRows = withSlug(rows, current.slug).filter((row) => previewData.items.find((item) => item.line === row.line)?.status === "nova"); if (!newRows.length) return { lidas: rows.length, importadas: 0, duplicadas: previewData.summary.duplicadas, ignoradas: ignored, erros: 0, estruturas_criadas: 0, estruturas_reutilizadas: (await structure(current.id)).length }; const before = await structure(current.id); const plan = planQuestionDeckStructure(newRows, before); const ids = new Map(plan.nodes.filter((node) => node.existingId !== null).map((node) => [node.key, node.existingId!])); for (const node of plan.nodes) if (!ids.has(node.key)) { const parentId = node.parentKey ? ids.get(node.parentKey) : null; if (node.parentKey && !parentId) throw new AdminQuestoesError(422, "Estrutura pai não pôde ser criada."); const r = await db().from("law_structure").insert({ lei_id: current.id, parent_id: parentId ?? null, tipo: node.tipo, nome: node.nome, ordem: 0, ativo: true }).select("id").single(); if (r.error || !r.data) fail("criar_estrutura_importacao", r.error); ids.set(node.key, r.data.id); } const byLine = new Map(plan.decks.map((deck) => [deck.line, deck.structureKey ? ids.get(deck.structureKey) ?? null : null])); const inserted = await db().from("questions").insert(newRows.map((row) => ({ lei_id: current.id, structure_id: byLine.get(row.line) ?? null, pergunta: row.pergunta, resposta: row.resposta, justificativa: row.justificativa || null, assunto: row.assunto || null, legislacao: row.legislacao || null, ordem: row.ordem, titulo: row.titulo || null, total_artigos: /^\d+$/.test(row.total_artigos) ? Number(row.total_artigos) : null, slug: row.slug, ultima_alteracao_legislativa: row.ultima_alteracao_legislativa || null, ativo: true }))).select("id"); if (inserted.error) fail("importar_anki", inserted.error); return { lidas: rows.length, importadas: inserted.data?.length ?? 0, duplicadas: previewData.summary.duplicadas, ignoradas: ignored, erros: 0, estruturas_criadas: plan.nodes.filter((node) => node.existingId === null).length, estruturas_reutilizadas: plan.nodes.filter((node) => node.existingId !== null).length }; }
export async function importAnkiTxt(body: Record<string, unknown>) { await requireAdmin(); const parsed = parseAnkiTxt(String(body.text)); const data = await preview(slug(body.law_slug), parsed); return persist(slug(body.law_slug), parsed.rows, data); }
export async function importApkg(body: { lawSlug: unknown; file: File }) { await requireAdmin(); const parsed = await parseLegisApkg(new Uint8Array(await body.file.arrayBuffer())); const data = await previewApkgImport(body.lawSlug, body.file); return persist(slug(body.lawSlug), parsed.rows, data, parsed.unrecognizedModels.reduce((sum, model) => sum + model.notes, 0)); }
