import type { ImportedQuestion, ImportIssue } from "@/lib/imported-question";
export type AnkiRow = ImportedQuestion;
export type { ImportedQuestion, ImportIssue } from "@/lib/imported-question";
type TsvRecord={line:number;fields:string[]};
function tsv(source:string){const records:TsvRecord[]=[];let fields:string[]=[],field="",quoted=false,line=1,recordLine=1;const finish=()=>{fields.push(field);if(fields.some(value=>value!==""))records.push({line:recordLine,fields});fields=[];field="";};for(let i=0;i<source.length;i++){const char=source[i];if(char==='"'){if(quoted&&source[i+1]==='"'){field+='"';i++;}else quoted=!quoted;continue;}if(char==='\t'&&!quoted){fields.push(field);field="";continue;}if(char==='\n'){if(quoted)field+='\n';else{finish();recordLine=line+1;}line++;continue;}field+=char;}if(field||fields.length)finish();return records;}
export function normalizeStructure(value:string){return value.normalize("NFKC").trim().replace(/\s+/g," ").toLocaleLowerCase("pt-BR");}
export function parseAnkiTxt(source:string){const records=tsv(source.replace(/^\uFEFF/,"").replace(/\r\n?/g,"\n"));const headers=new Set(records.filter(record=>record.fields.length===1&&record.fields[0].startsWith("#")).map(record=>record.fields[0]));if(!headers.has("#separator:tab"))throw new Error("O arquivo precisa declarar #separator:tab.");const rows:AnkiRow[]=[];const issues:ImportIssue[]=[];for(const record of records){const c=record.fields;if(c.length===1&&c[0].startsWith("#"))continue;const deck=c[0]?.split("::").map(x=>x.trim()).filter(Boolean)??[];if(c.length!==11&&c.length!==12){issues.push({line:record.line,deck,ordem:c[6],pergunta:c[1],field:"colunas",received:String(c.length),expected:"11 ou 12 colunas",message:`Quantidade de colunas inválida: recebidas ${c.length}; esperadas 11 ou 12.`});continue;}const answer=c[2].trim().toLocaleLowerCase("pt-BR");if(answer!=="certo"&&answer!=="errado"){issues.push({line:record.line,deck,ordem:c[6],pergunta:c[1],field:"resposta",received:c[2],expected:"Certo ou Errado",message:`Resposta inválida: “${c[2]}”. Esperado: “Certo” ou “Errado”.`});continue;}if(!c[1].trim()){issues.push({line:record.line,deck,ordem:c[6],field:"pergunta",received:c[1],expected:"Pergunta não vazia",message:"Pergunta vazia."});continue;}rows.push({line:record.line,deck,pergunta:c[1],resposta:answer==="certo"?"Certo":"Errado",justificativa:c[3],assunto:c[4],legislacao:c[5],ordem:c[6],titulo:c[7],total_artigos:c[8],slug:c[9].trim(),ultima_alteracao_legislativa:c[10]});}return{rows,issues,headers};}
export function effectiveAnkiSlug(value:string,selected:string){return value.trim()||selected;}
export function validateImportSlug(rows:AnkiRow[],selected:string){const slugs=[...new Set(rows.map(x=>x.slug).filter(Boolean))];const different=slugs.find(value=>value!==selected);return{slugs:slugs.length?slugs:[selected],valid:!different,message:different?`O arquivo pertence à legislação ${different}, mas a legislação selecionada é ${selected}.`:null};}
export function structureIdForDeck(deck:string[],nodes:{id:number;parent_id:number|null;nome:string}[]){let parent:number|null=null;for(const segment of deck.slice(1)){const normalized=normalizeStructure(segment);const found=nodes.find(n=>n.parent_id===parent&&normalizeStructure(n.nome)===normalized);if(!found)return null;parent=found.id;}return parent;}
