import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const server=readFileSync("lib/coach-admin-server.ts","utf8");
const migration=readFileSync("supabase/migrations/20260821140000_add_campaign_score_adjustments.sql","utf8");
const completionMigration=readFileSync("supabase/migrations/20260822100000_create_level_completion_messages.sql","utf8");
const activityMigration=readFileSync("supabase/migrations/20260828170000_create_campaign_answer_activity.sql","utf8");
const ranking=readFileSync("lib/public-law-ranking.ts","utf8");
describe("Painel de Coach e ajuste auditável de score",()=>{
 it("protege leituras e ajuste no servidor",()=>{expect(server.match(/requireAdmin\(\)/g)?.length).toBeGreaterThanOrEqual(3);expect(server).toContain("admin_ajustar_score_campanha");expect(server).toContain("reason.length > 1000");});
 it("filtra nome e e-mail no banco antes de aplicar a paginação",()=>{expect(server).toContain("studentsQuery = studentsQuery.or");expect(server.indexOf("studentsQuery = studentsQuery.or")).toBeLessThan(server.indexOf('.range((page - 1) * limit'));expect(server).not.toContain("(students ?? []).filter");});
 it("ordena a visão inicial por atividade antes de paginar",()=>{expect(server).toContain('const orderByStudyActivity = filter === "todos" && !query');expect(server).toContain('const right = b.lastActivity');expect(server).toContain('items: ordered.slice(start, start + limit)');});
 it("preserva score original, exige campanha concluída e audita cada ajuste",()=>{expect(migration).toContain("add column if not exists score_ajustado");expect(migration).toContain("if not v_before.concluida");expect(migration).toContain("admin_comercial_auditar");expect(migration).toContain("score_original");expect(migration).toContain("p_motivo");});
 it("usa somente campanhas V2 e exibe o score competitivo atual",()=>{const client=readFileSync("components/admin/coach-admin.tsx","utf8");expect(migration).toContain("coalesce(score_ajustado, score)");expect(ranking).toContain("campaign.score_ajustado");expect(ranking).toContain("effectiveScore");expect(server).toContain('.eq("score_version", 2)');expect(client).toContain("Score competitivo:");expect(client).toContain("Score competitivo: {(campaign.score_efetivo ?? campaign.score ?? 0)");});
 it("administra mensagens de conclusão por RPC auditada e ordem canônica",()=>{const client=readFileSync("components/admin/coach-admin.tsx","utf8");const cache=readFileSync("lib/level-completion-messages-server.ts","utf8");expect(completionMigration).toContain("create table if not exists public.mensagens_conclusao_niveis");expect(completionMigration).toContain("ordem asc, id asc");expect(completionMigration).toContain("admin_comercial_auditar");expect(completionMigration).toContain("admin_criar_mensagem_conclusao_nivel");expect(completionMigration).toContain("admin_excluir_mensagem_conclusao_nivel");expect(server).toContain("await requireAdmin()");expect(server).toContain("invalidateLevelCompletionMessagesCache()");expect(client).toContain("Mensagens de conclusão");expect(client).toContain('window.confirm("Excluir esta mensagem de conclusão?")');expect(cache).toContain('eq("ativo", true)');expect(cache).toContain("LEVEL_COMPLETION_MESSAGES_CACHE_TAG");});
 it("registra e ordena respostas pelo instante semântico, sem usar updated_at como atividade",()=>{const client=readFileSync("components/admin/coach-admin.tsx","utf8");expect(activityMigration).toContain("create table if not exists public.campanhas_leis_respostas");expect(activityMigration).toContain("respondido_em timestamptz not null default now()");expect(activityMigration).toContain("insert into public.campanhas_leis_respostas");expect(activityMigration).toContain("campanhas_leis_respostas_campanha_respondido_idx");expect(server).toContain('from("campanhas_leis_respostas")');expect(server).toContain('order("respondido_em", { ascending: false })');expect(server).toContain("newestAnswerByCampaign");expect(client).toContain("Última questão respondida:");expect(client).toContain("Atividades recentes");expect(client).toContain("formatCoachActivityAt(activity.answeredAt)");});
 it("mantém o histórico restrito ao servidor administrativo e indexado pela campanha",()=>{expect(activityMigration).toContain("revoke all on public.campanhas_leis_respostas from public, anon, authenticated");expect(activityMigration).toContain("grant select, insert on public.campanhas_leis_respostas to service_role");expect(activityMigration).toContain("(campanha_id, respondido_em desc, id desc)");expect(activityMigration).toContain("references public.campanhas_leis_niveis(id) on delete cascade");});
});
