export type AccessEmailFlow = "existing_account" | "first_access";

export type AccessEmailEditorial = {
  subject: string;
  title: string;
  message: string;
  buttonText: string;
  footer: string;
};

export type AccessEmailSnapshot = AccessEmailEditorial & {
  flow: AccessEmailFlow;
  recipient: string;
  template: string;
  buttonDestination: "account" | "secure_activation";
  html: string;
  text: string;
};

const allowedVariables = new Set(["nome", "produto", "email"]);
const defaults: Record<AccessEmailFlow, AccessEmailEditorial> = {
  existing_account: {
    subject: "Seu acesso ao Legis Flashcards está disponível",
    title: "Seu acesso está liberado",
    message: "Olá, {{nome}}. Seu acesso a {{produto}} já está liberado. Use o botão abaixo para entrar na sua conta.",
    buttonText: "Acessar minha conta",
    footer: "Se não lembrar sua senha, use a recuperação de acesso na área do aluno.",
  },
  first_access: {
    subject: "Ative seu acesso ao Legis Flashcards",
    title: "Ative seu acesso",
    message: "Olá, {{nome}}. Seu acesso a {{produto}} já foi liberado. Use o botão abaixo para ativar sua conta e começar seus estudos.",
    buttonText: "Ativar meu acesso",
    footer: "Este é um link seguro e pessoal para ativação do seu acesso.",
  },
};

function plain(value: unknown, field: string, max: number) {
  if (typeof value !== "string") throw new Error(`${field} inválido.`);
  const normalized = value.replace(/<[^>]*>/g, "").replace(/\r\n?/g, "\n").trim();
  if (!normalized || normalized.length > max) throw new Error(`${field} inválido.`);
  return normalized;
}

function validateVariables(value: string) {
  for (const match of value.matchAll(/{{\s*([^{}\s]+)\s*}}/g)) {
    if (!allowedVariables.has(match[1])) throw new Error(`Placeholder não permitido: {{${match[1]}}}.`);
  }
  if (/{{|}}/.test(value.replace(/{{\s*(nome|produto|email)\s*}}/g, ""))) throw new Error("Placeholder inválido.");
  return value;
}

function escapeHtml(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

function interpolate(value: string, variables: Record<"nome" | "produto" | "email", string>) {
  return value.replace(/{{\s*(nome|produto|email)\s*}}/g, (_, key: keyof typeof variables) => variables[key]);
}

export function defaultAccessEmailEditorial(flow: AccessEmailFlow) {
  return { ...defaults[flow] };
}

/** Admin content is plain text only; HTML is generated by the server from escaped values. */
export function validateAccessEmailEditorial(input: unknown, flow: AccessEmailFlow): AccessEmailEditorial {
  if (!input || typeof input !== "object" || Array.isArray(input)) return defaultAccessEmailEditorial(flow);
  const value = input as Record<string, unknown>;
  return {
    subject: validateVariables(plain(value.subject, "Assunto", 180)),
    title: validateVariables(plain(value.title, "Título", 180)),
    message: validateVariables(plain(value.message, "Mensagem", 4000)),
    buttonText: validateVariables(plain(value.buttonText, "Texto do botão", 100)),
    footer: validateVariables(plain(value.footer, "Rodapé", 1000)),
  };
}

export function renderAccessEmail(input: {
  flow: AccessEmailFlow;
  name: string | null;
  product: string;
  email: string;
  editorial?: unknown;
  secureUrl: string;
}) {
  const editorial = validateAccessEmailEditorial(input.editorial ?? defaultAccessEmailEditorial(input.flow), input.flow);
  const variables = { nome: input.name?.trim() || "aluno(a)", produto: input.product, email: input.email };
  const rendered = Object.fromEntries(Object.entries(editorial).map(([key, value]) => [key, interpolate(value, variables)])) as AccessEmailEditorial;
  const destination = input.flow === "existing_account" ? "account" : "secure_activation";
  // Snapshots intentionally retain only the logical destination, never a query or fragment token.
  const safeUrl = (() => {
    try { const url = new URL(input.secureUrl); return `${url.origin}${url.pathname}`; } catch { return "Link seguro redigido"; }
  })();
  const text = `${rendered.title}\n\n${rendered.message}\n\n${rendered.buttonText}: ${input.secureUrl}\n\n${rendered.footer}`;
  const snapshotText = `${rendered.title}\n\n${rendered.message}\n\n${rendered.buttonText}: ${safeUrl}\n\n${rendered.footer}`;
  const html = `<main><h1>${escapeHtml(rendered.title)}</h1><p>${escapeHtml(rendered.message).replace(/\n/g, "<br>")}</p><p><a href="${escapeHtml(input.secureUrl)}">${escapeHtml(rendered.buttonText)}</a></p><p>${escapeHtml(rendered.footer).replace(/\n/g, "<br>")}</p></main>`;
  const snapshotHtml = html.replace(escapeHtml(input.secureUrl), escapeHtml(safeUrl));
  const snapshot: AccessEmailSnapshot = { ...rendered, flow: input.flow, recipient: input.email, template: input.flow === "existing_account" ? "crm_access_existing_account" : "crm_access_first_access", buttonDestination: destination, html: snapshotHtml, text: snapshotText };
  return { subject: rendered.subject, text, html, snapshot };
}
