import "server-only";
import { obterAdministrador } from "@/lib/admin-auth";
import { getSupabaseServerClient } from "@/lib/supabase-server";

const db = () => getSupabaseServerClient();
async function excludedRecipientIds(noticeId:string) { const result=await db().from("law_update_notice_recipient_exclusions").select("student_id").eq("notice_id",noticeId); if(result.error) throw new Error(result.error.message); return new Set((result.data??[]).map(row=>row.student_id)); }
async function recipientCount(lawId:number,noticeId:string) { const r=await db().rpc("obter_destinatarios_aviso_lei",{p_lei_id:lawId}); if(r.error) throw new Error(r.error.message); const excluded=await excludedRecipientIds(noticeId); return new Set((r.data??[]).map((x:{aluno_id:string})=>x.aluno_id).filter((id:string)=>!excluded.has(id))).size; }
export type NoticeKind = "question_added" | "question_changed" | "question_removed" | "structure_changed" | "law_content_changed";
export async function recordLawUpdate(lawId: number, kind: NoticeKind, summary: string, metadata: Record<string, unknown> = {}) {
  const { error } = await db().rpc("record_law_update_notice_event", { p_law_id: lawId, p_kind: kind, p_summary: summary, p_metadata: metadata });
  if (error) throw new Error("Não foi possível registrar o aviso de atualização: " + error.message);
}
async function admin() { if (!await obterAdministrador()) throw new Error("Administração obrigatória."); }
export async function listNotices() { await admin(); const r=await db().from("law_update_notices").select("*,leis(titulo,slug),law_update_notice_changes(*) ").order("created_at",{ascending:false}); if(r.error) throw new Error(r.error.message); const rows=r.data??[]; const publishedIds=rows.filter(row=>row.status!=="draft").map(row=>row.id); const deliveries=publishedIds.length?await db().from("law_update_notice_deliveries").select("notice_id").in("notice_id",publishedIds):null; if(deliveries?.error) throw new Error(deliveries.error.message); return Promise.all(rows.map(async row=>({...row,recipient_count:row.status==="draft"?await recipientCount(row.law_id,row.id):(deliveries?.data?.filter(delivery=>delivery.notice_id===row.id).length??0)}))); }
export async function notice(id:string) { await admin(); const r=await db().from("law_update_notices").select("*,leis(titulo,slug),law_update_notice_changes(*)").eq("id",id).single(); if(r.error) throw new Error("Aviso não encontrado."); const recipient_count=r.data.status==="draft"?await recipientCount(r.data.law_id,id):(await db().from("law_update_notice_deliveries").select("notice_id",{count:"exact",head:true}).eq("notice_id",id)).count??0; return {...r.data,recipient_count}; }
export async function updateNotice(id:string,data:{title?:string;message?:string;destination_url?:string|null}) { await admin(); const {title,message,destination_url}=data; const r=await db().from("law_update_notices").update({...(title!==undefined?{title}:{}),...(message!==undefined?{message}:{}),...(destination_url!==undefined?{destination_url}:{})}).eq("id",id).eq("status","draft"); if(r.error) throw new Error(r.error.message); }
export async function publishNotice(id:string) { await admin(); const excluded=await excludedRecipientIds(id); const r=await db().rpc("publish_law_update_notice",{p_notice_id:id}); if(r.error) throw new Error(r.error.message); if(excluded.size){const removed=await db().from("law_update_notice_deliveries").delete().eq("notice_id",id).in("student_id",[...excluded]);if(removed.error)throw new Error(removed.error.message);} return Number(r.data??0)-excluded.size; }
export async function discardNotice(id:string) { await admin(); const r=await db().from("law_update_notices").update({status:"discarded",discarded_at:new Date().toISOString()}).eq("id",id).eq("status","draft"); if(r.error) throw new Error(r.error.message); }
export async function noticeRecipients(id:string) { await admin(); const current=await notice(id); let ids:string[]=[]; if(current.status==="draft"){const candidates=await db().rpc("obter_destinatarios_aviso_lei",{p_lei_id:current.law_id});if(candidates.error)throw new Error(candidates.error.message);ids=(candidates.data??[]).map((row:{aluno_id:string})=>row.aluno_id);}else{const deliveries=await db().from("law_update_notice_deliveries").select("student_id").eq("notice_id",id);if(deliveries.error)throw new Error(deliveries.error.message);ids=(deliveries.data??[]).map(row=>row.student_id);}const excluded=await excludedRecipientIds(id);ids=ids.filter(studentId=>!excluded.has(studentId));if(!ids.length)return [];const students=await db().from("alunos").select("id,nome,email").in("id",ids).order("nome");if(students.error)throw new Error(students.error.message);return students.data??[]; }
export async function setNoticeRecipientExcluded(noticeId:string,studentId:string,excluded:boolean) { await admin(); const current=await notice(noticeId); if(current.status==="discarded"||current.email_status==="sent_resend") throw new Error("Não é mais possível alterar os destinatários deste aviso."); if(excluded){const result=await db().from("law_update_notice_recipient_exclusions").upsert({notice_id:noticeId,student_id:studentId},{onConflict:"notice_id,student_id"});if(result.error)throw new Error(result.error.message);if(current.status==="published"){const delivery=await db().from("law_update_notice_deliveries").delete().eq("notice_id",noticeId).eq("student_id",studentId);if(delivery.error)throw new Error(delivery.error.message);}}else{const result=await db().from("law_update_notice_recipient_exclusions").delete().eq("notice_id",noticeId).eq("student_id",studentId);if(result.error)throw new Error(result.error.message);} }
export async function claimResend(id:string) { await admin(); const r=await db().rpc("claim_law_update_notice_resend",{p_notice_id:id}); if(r.error) throw new Error(r.error.message); return r.data===true; }
export async function finishResend(id:string,success:boolean,count:number,error?:string) { const r=await db().rpc("finish_law_update_notice_resend",{p_notice_id:id,p_success:success,p_count:count,p_error:error??null}); if(r.error) throw new Error(r.error.message); }
