import { randomUUID } from "node:crypto";
import { Client } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const url = process.env.CONTENT_DELETION_LOCAL_TEST_DATABASE_URL ?? "postgresql://postgres:postgres@127.0.0.1:54322/postgres";
const suite = process.env.RUN_CONTENT_DELETION_DB_INTEGRATION === "1" ? describe.sequential : describe.skip;

suite("desvínculo seguro de jobs LegisCast ao excluir estrutura", () => {
  let db: Client; let law = 0; let actor = ""; const suffix = randomUUID().slice(0, 8);
  const job = async (structureId: number, status: "pendente" | "processando" | "concluido" = "pendente") => (await db.query<{ id: string }>("insert into public.legiscast_audio_jobs(id,lei_id,structure_id,titulo,status,original_bucket,original_path,original_mime,original_size_bytes,final_path,final_mime,final_size_bytes,duracao_segundos,processing_token) values($1,$2,$3,'Job de teste',$4,'test',$5,'audio/mpeg',1,$6,$7,$8,$9,$10) returning id", [randomUUID(), law, structureId, status, `source/${randomUUID()}`, `final/${randomUUID()}`, status === "concluido" ? "audio/mp4" : null, status === "concluido" ? 1 : null, status === "concluido" ? 1 : null, status === "processando" ? randomUUID() : null])).rows[0].id;
  const structure = async () => Number((await db.query("insert into public.law_structure(lei_id,tipo,nome,ordem,ativo) values($1,'titulo','Teste',1,true) returning id", [law])).rows[0].id);
  const call = async (structureId: number, execute = false, jobAction: string | null = null) => (await db.query<{ result: Record<string, unknown> }>("select public.admin_delete_law_content_v3($1,null,$2,$3,'EXCLUIR',$4,$5) result", [law, structureId, actor, execute, jobAction])).rows[0].result;

  beforeAll(async () => { db = new Client({ connectionString: url }); await db.connect(); if (!(await db.query("select to_regprocedure('public.admin_delete_law_content_v3(bigint,uuid[],bigint,uuid,text,boolean,text)') f")).rows[0].f) throw new Error("A migration de jobs LegisCast precisa estar aplicada no banco descartável."); actor = randomUUID(); await db.query("insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,'',now(),'{}','{}',now(),now())", [actor, `job-${suffix}@example.test`]); law = Number((await db.query("insert into public.leis(slug,titulo) values($1,$2) returning id", [`job-${suffix}`, "Lei de teste"])).rows[0].id); });
  afterAll(async () => { if (!db) return; await db.query("delete from public.leis where id=$1", [law]); await db.query("delete from auth.users where id=$1", [actor]); await db.end(); });

  it("desvincula job encerrado e preserva seu histórico", async () => { const node = await structure(); const id = await job(node, "concluido"); expect(await call(node)).toMatchObject({ job_action_required: "detach_completed" }); await call(node, true, "detach_completed"); expect((await db.query("select status,structure_id from public.legiscast_audio_jobs where id=$1", [id])).rows[0]).toEqual({ status: "concluido", structure_id: null }); });
  it("cancela job em processamento antes de excluir", async () => { const node = await structure(); const id = await job(node, "processando"); expect(await call(node)).toMatchObject({ job_action_required: "cancel_active" }); await call(node, true, "cancel_active"); expect((await db.query("select status,structure_id,processing_token from public.legiscast_audio_jobs where id=$1", [id])).rows[0]).toEqual({ status: "cancelado", structure_id: null, processing_token: null }); });
  it("bloqueia publicação de callback tardio", async () => { const node = await structure(); const id = await job(node, "processando"); const token = (await db.query("select processing_token from public.legiscast_audio_jobs where id=$1", [id])).rows[0].processing_token; await call(node, true, "cancel_active"); expect((await db.query("select public.publish_legiscast_audio_job($1,$2,1,1) ok", [id, token])).rows[0].ok).toBe(false); expect(Number((await db.query("select count(*) from public.legiscast_audios where storage_path=(select final_path from public.legiscast_audio_jobs where id=$1)", [id])).rows[0].count)).toBe(0); });
  it("reverte o cancelamento quando outro bloqueio impede a exclusão", async () => { const node = await structure(); const id = await job(node, "pendente"); const recorte = (await db.query("insert into public.recortes_leis(lei_id,nome) values($1,'Bloqueio') returning id", [law])).rows[0].id; await db.query("insert into public.recortes_leis_estrutura(recorte_id,structure_id,lei_id) values($1,$2,$3)", [recorte, node, law]); await expect(call(node, true, "cancel_active")).rejects.toThrow(); expect((await db.query("select status,structure_id from public.legiscast_audio_jobs where id=$1", [id])).rows[0]).toEqual({ status: "pendente", structure_id: node }); await db.query("delete from public.recortes_leis_estrutura where recorte_id=$1", [recorte]); });
  it("não desvincula job de outra lei", async () => { const node = await structure(); const other = Number((await db.query("insert into public.leis(slug,titulo) values($1,'Outra') returning id", [`other-${randomUUID()}`])).rows[0].id); const id = randomUUID(); await db.query("insert into public.legiscast_audio_jobs(id,lei_id,structure_id,titulo,original_bucket,original_path,original_mime,original_size_bytes,final_path) values($1,$2,$3,'Cruzado','test',$4,'audio/mpeg',1,$5)", [id, other, node, `source/${id}`, `final/${id}`]); await expect(call(node, true, null)).rejects.toThrow(); expect((await db.query("select structure_id from public.legiscast_audio_jobs where id=$1", [id])).rows[0].structure_id).toBe(node); await db.query("delete from public.leis where id=$1", [other]); });
});
