"use client";

import { useMemo, useRef, useState } from "react";
import { sanitizeLegisQuestoesHtml } from "@/lib/legis-questoes-html";
import type { CreatableQuestionStructureType } from "@/lib/questoes-structure";

type AnkiItem = { line: number; deck: string; structure_id: number | null; status: "nova" | "duplicada" | "erro"; motivo: string | null };
type AnkiStructure = { key: string; path: string; tipo: CreatableQuestionStructureType; status: "nova" | "existente" | "revisao" | "erro"; destination_id: number | null; candidates: Array<{ id: number; nome: string }> };
type ImportDiagnostic = { line: number; deck: string; ordem: string; pergunta: string; field: string; received: string; expected: string; motivo: string };
type AnkiPreview = { total: number; errors: ImportDiagnostic[]; items: AnkiItem[]; structure: { items: AnkiStructure[]; existentes: number; novas: number; revisoes: number }; summary: { novas: number; duplicadas: number; erros: number } };
type AnkiResult = { lidas: number; importadas: number; duplicadas: number; erros: number };
type ApkgPreview = AnkiPreview & { apkg: { rootDecks: string[]; subdecks: string[]; notes: number; cards: number; recognizedModels: string[]; unrecognizedModels: Array<{ name: string; fields: string[]; notes: number }>; media: Array<{ name: string; referenced: boolean }>; samples: Array<{ pergunta: string; resposta: string; justificativa: string; legislacao: string; ordem: string; deck: string[] }> } };
type StructureMappings = Record<string, number | "new">;

async function api<T>(url: string, init?: RequestInit) {
  const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || "Erro na operação.");
  return body as T;
}

export function AdminQuestionAnkiTools({ lawSlug, lawName, onImported }: { lawSlug: string; lawName: string; onImported?: () => Promise<void> }) {
  return <section className="grid gap-5">
    <header className="law-center-page-heading"><div><p className="law-center-kicker">Anki</p><h2>Importação e exportação</h2><p>Use os mesmos parsers, validações e formatos do Admin de Questões.</p></div></header>
    <article className="commercial-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2>Exportar Anki</h2><p className="text-sm text-slate-600">Gera o APKG da lei com o exportador administrativo atual.</p></div><a className="admin-button secondary" href={`/api/admin/questoes/exportar-apkg?slug=${encodeURIComponent(lawSlug)}`}>Exportar APKG</a></div></article>
    <AnkiImport key={lawSlug} lawSlug={lawSlug} lawName={lawName} onImported={onImported} />
    <ApkgImport lawSlug={lawSlug} lawName={lawName} />
  </section>;
}

function StructureDestinations({ preview, lawName, mappings, onMapping }: { preview: AnkiPreview; lawName: string; mappings: StructureMappings; onMapping: (key: string, value: number | "new") => void }) {
  if (!preview.structure.items.length) return null;
  return <details open><summary>Destinos estruturais: {preview.structure.existentes} existente(s) · {preview.structure.novas} nova(s){preview.structure.revisoes ? ` · ${preview.structure.revisoes} para revisar` : ""}</summary><ul className="anki-structure-destinations">{preview.structure.items.map((node) => <li key={node.key}><strong>{lawName}::{node.path.replaceAll(" › ", "::")}</strong><br />{node.status === "existente" ? "✓ Estrutura equivalente existente" : node.status === "nova" ? "+ Nova estrutura será criada" : node.status === "erro" ? "✕ Mapeamento inválido" : <label>Nome semelhante encontrado; escolha o destino:<select value={mappings[node.key] === "new" ? "new" : String(mappings[node.key] ?? "")} onChange={(event) => onMapping(node.key, event.target.value === "new" ? "new" : Number(event.target.value))}><option value="">Selecione…</option>{node.candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>Usar “{candidate.nome}”</option>)}<option value="new">Criar nova estrutura “{node.path.split(" › ").at(-1)}”</option></select></label>}</li>)}</ul></details>;
}

function ImportErrors({ errors, expectedCount }: { errors: ImportDiagnostic[]; expectedCount: number }) {
  if (!errors.length) return <section className="anki-import-errors"><h4>Erros impeditivos</h4><p className="admin-alert error">A prévia informou {expectedCount} erro(s) impeditivo(s), mas não retornou seus detalhes.</p></section>;
  return <section className="anki-import-errors"><h4>Erros impeditivos</h4>{errors.map((item) => <details key={`${item.line}-${item.field}-${item.deck}`}><summary>{item.ordem || `Linha/note ${item.line}`} — {item.motivo}</summary><p><strong>Deck:</strong> {item.deck || "Sem deck"}</p><p><strong>Campo:</strong> {item.field}</p></details>)}</section>;
}

function AnkiImport({ lawSlug, lawName, onImported }: { lawSlug: string; lawName: string; onImported?: () => Promise<void> }) {
  const [fileName, setFileName] = useState(""); const [fileText, setFileText] = useState(""); const [preview, setPreview] = useState<AnkiPreview | null>(null); const [mappings, setMappings] = useState<StructureMappings>({}); const [result, setResult] = useState<AnkiResult | null>(null); const [analyzing, setAnalyzing] = useState(false); const [importing, setImporting] = useState(false); const [error, setError] = useState(""); const input = useRef<HTMLInputElement>(null);
  const groups = useMemo(() => { const map = new Map<string, AnkiItem[]>(); for (const item of preview?.items ?? []) map.set(item.deck, [...(map.get(item.deck) ?? []), item]); return [...map.entries()]; }, [preview]);
  async function analyze(nextMappings = mappings) { if (!fileText) return; setAnalyzing(true); setError(""); setResult(null); try { setPreview(await api<AnkiPreview>("/api/admin/questoes", { method: "POST", body: JSON.stringify({ action: "previsualizar_anki", law_slug: lawSlug, text: fileText, structure_mappings: nextMappings }) })); } catch (caught) { setPreview(null); setError(caught instanceof Error ? caught.message : "Não foi possível analisar o arquivo."); } finally { setAnalyzing(false); } }
  async function importFile() { if (!preview || preview.summary.erros || preview.structure.revisoes || !fileText) return; setImporting(true); setError(""); try { const nextResult = await api<AnkiResult>("/api/admin/questoes", { method: "POST", body: JSON.stringify({ action: "importar_anki", law_slug: lawSlug, text: fileText, structure_mappings: mappings }) }); setResult(nextResult); await onImported?.(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível importar o arquivo."); } finally { setImporting(false); } }
  function choose(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; setError(""); setPreview(null); setResult(null); setMappings({}); if (!file) { setFileName(""); setFileText(""); return; } void file.text().then((text) => { setFileName(file.name); setFileText(text); }).catch(() => setError("Não foi possível ler o arquivo TXT.")); }
  const unresolved = preview?.structure.items.some((node) => node.status === "revisao" && mappings[node.key] === undefined) ?? false;
  return <article className="commercial-card anki-import"><h2>Importar flashcards do Anki</h2><p>Importação para <strong>{lawName}</strong>. O arquivo só é importado após a confirmação.</p><label>Arquivo TXT<input ref={input} type="file" accept=".txt,text/plain" onChange={choose} /></label>{fileName && <p className="anki-import-file"><strong>{fileName}</strong></p>}<button type="button" className="admin-button secondary" disabled={!fileText || analyzing || importing} onClick={() => void analyze()}>{analyzing ? "Analisando arquivo…" : "Analisar arquivo"}</button>{error && <p className="admin-alert error" role="alert">{error}</p>}{preview && <section className="anki-import-preview"><h3>Prévia: {fileName}</h3><div className="anki-import-summary"><p><strong>Notas:</strong> {preview.total}</p><p className="new"><strong>Novas:</strong> {preview.summary.novas}</p><p className="duplicate"><strong>Duplicadas:</strong> {preview.summary.duplicadas}</p><p className="error"><strong>Erros:</strong> {preview.summary.erros}</p></div><StructureDestinations preview={preview} lawName={lawName} mappings={mappings} onMapping={(key, value) => setMappings((current) => ({ ...current, [key]: value }))} />{preview.structure.revisoes ? <button type="button" className="admin-button secondary" disabled={analyzing || importing || unresolved} onClick={() => void analyze()}>Atualizar destinos revisados</button> : null}{groups.length ? <details><summary>Decks e estrutura ({groups.length})</summary><ul>{groups.map(([deck, items]) => <li key={deck}>{items.some((item) => item.status === "erro") ? "✕" : "✓"} {deck || "Sem deck"} — {items.length} questão(ões)</li>)}</ul></details> : null}{preview.summary.erros ? <><ImportErrors errors={preview.errors} expectedCount={preview.summary.erros} /><p className="admin-alert error">Existem problemas que precisam ser corrigidos antes da importação.</p></> : <button type="button" className="admin-button primary" disabled={importing || Boolean(preview.structure.revisoes)} onClick={() => void importFile()}>{importing ? "Importando…" : `Importar ${preview.summary.novas} questões`}</button>}</section>}{result && <section className="anki-import-result" role="status"><h3>Importação concluída</h3><p><strong>{result.importadas} questões importadas</strong><br />{result.duplicadas} duplicadas ignoradas<br />{result.erros} erros</p></section>}</article>;
}

function ApkgImport({ lawSlug, lawName }: { lawSlug: string; lawName: string }) {
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<ApkgPreview | null>(null); const [mappings, setMappings] = useState<StructureMappings>({}); const [result, setResult] = useState<{ importadas: number; duplicadas: number; ignoradas: number; erros: number; estruturas_criadas: number; estruturas_reutilizadas: number } | null>(null); const [error, setError] = useState(""); const [analyzing, setAnalyzing] = useState(false); const [importing, setImporting] = useState(false);
  async function analyze(nextMappings = mappings) { if (!file) return; setAnalyzing(true); setError(""); try { const form = new FormData(); form.set("action", "previsualizar_apkg"); form.set("law_slug", lawSlug); form.set("file", file); form.set("structure_mappings", JSON.stringify(nextMappings)); const response = await fetch("/api/admin/questoes", { method: "POST", body: form }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Não foi possível analisar o APKG."); setPreview(body as ApkgPreview); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível analisar o APKG."); } finally { setAnalyzing(false); } }
  async function confirm() { if (!file || !preview || preview.summary.erros || preview.structure.revisoes) return; setImporting(true); setError(""); try { const form = new FormData(); form.set("action", "importar_apkg"); form.set("law_slug", lawSlug); form.set("file", file); form.set("structure_mappings", JSON.stringify(mappings)); const response = await fetch("/api/admin/questoes", { method: "POST", body: form }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Não foi possível importar o APKG."); setResult(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível importar o APKG."); } finally { setImporting(false); } }
  const unresolved = preview?.structure.items.some((node) => node.status === "revisao" && mappings[node.key] === undefined) ?? false;
  return <article className="commercial-card anki-import"><h2>Importar APKG</h2><p>Importação para <strong>{lawName}</strong>. O arquivo não é armazenado.</p><label>Arquivo APKG<input type="file" accept=".apkg,application/octet-stream" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setResult(null); setMappings({}); setError(""); }} /></label>{file && <p className="anki-import-file"><strong>{file.name}</strong></p>}<button type="button" className="admin-button secondary" disabled={!file || analyzing || importing} onClick={() => void analyze()}>{analyzing ? "Analisando APKG…" : "Analisar APKG"}</button>{error && <p className="admin-alert error" role="alert">{error}</p>}{preview && <section className="anki-import-preview"><h3>Prévia APKG</h3><div className="anki-import-summary"><p><strong>Notes:</strong> {preview.apkg.notes}</p><p><strong>Cards:</strong> {preview.apkg.cards}</p><p className="new"><strong>Convertidas:</strong> {preview.total}</p><p className="error"><strong>Erros:</strong> {preview.summary.erros}</p></div><p><strong>Deck raiz:</strong> {preview.apkg.rootDecks.join(" · ") || "Não encontrado"}</p><p><strong>Subdecks:</strong> {preview.apkg.subdecks.join(" · ") || "Nenhum"}</p><StructureDestinations preview={preview} lawName={lawName} mappings={mappings} onMapping={(key, value) => setMappings((current) => ({ ...current, [key]: value }))} />{preview.structure.revisoes ? <button type="button" className="admin-button secondary" disabled={analyzing || importing || unresolved} onClick={() => void analyze()}>Atualizar destinos revisados</button> : null}<details open><summary>Exemplos ({preview.apkg.samples.length})</summary>{preview.apkg.samples.map((sample, index) => <article className="commercial-card" key={`${sample.ordem}-${index}`}><p><strong>{sample.deck.join("::") || "Deck raiz"} · {sample.ordem}</strong></p><div className="legis-questoes-html" dangerouslySetInnerHTML={{ __html: sanitizeLegisQuestoesHtml(sample.pergunta) }} /><p><strong>Resposta:</strong> {sample.resposta}</p></article>)}</details>{preview.summary.erros ? <ImportErrors errors={preview.errors} expectedCount={preview.summary.erros} /> : <button type="button" className="admin-button primary" disabled={importing || Boolean(preview.structure.revisoes)} onClick={() => void confirm()}>{importing ? "Importando…" : `Confirmar importação de ${preview.summary.novas} questões`}</button>}</section>}{result && <section className="anki-import-result" role="status"><h3>Importação concluída</h3><p><strong>{result.importadas} questões importadas</strong><br />{result.duplicadas} duplicadas<br />{result.ignoradas} notas ignoradas por modelo<br />{result.estruturas_criadas} subdecks criados<br />{result.estruturas_reutilizadas} subdecks reutilizados<br />{result.erros} erros</p></section>}</article>;
}
