"use client";

import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { CommercialDataTable as DataTable, CommercialEditForm as EditForm } from "@/components/admin/commercial-admin-ui";

type Row = Record<string, unknown>;
type PageResult = { items: Row[]; page: number; pages: number; total: number };
type MaterialMutation = (resource: "materiais", payload: Row, success: string) => Promise<void>;

const text = (value: unknown) => value == null ? "" : String(value);
const object = (value: unknown): Row => value && typeof value === "object" && !Array.isArray(value) ? value as Row : {};
const relation = (row: Row, key: string) => object(row[key]);

async function requestJson(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível concluir a operação."); return data; }

export function LawMaterialsAdmin({ law }: { law: { id: number; slug: string; titulo: string } }) {
  const [result, setResult] = useState<PageResult>({ items: [], page: 1, pages: 1, total: 0 }); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [editing, setEditing] = useState<Row | null>(null); const loadVersion = useRef(0);
  const load = useCallback(async () => { const version = ++loadVersion.current; setBusy(true); setError(""); try { const params = new URLSearchParams({ page: String(page), limit: "25" }); if (query.trim()) params.set("q", query.trim()); const next = await requestJson(`/api/admin/leis/${encodeURIComponent(law.slug)}/materiais?${params}`); if (version === loadVersion.current) setResult(next); } catch (caught) { if (version === loadVersion.current) setError(caught instanceof Error ? caught.message : "Falha na consulta de materiais."); } finally { if (version === loadVersion.current) setBusy(false); } }, [law.slug, page, query]);
  useEffect(() => { void load(); }, [load]);
  async function mutate(_resource: "materiais", payload: Row, success: string) { setBusy(true); setError(""); setMessage(""); try { await requestJson(`/api/admin/leis/${encodeURIComponent(law.slug)}/materiais`, { method: "POST", body: JSON.stringify(payload) }); setMessage(success); setEditing(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Falha na operação."); } finally { setBusy(false); } }
  return <section className="commercial-admin"><header className="law-center-page-heading"><div><p className="law-center-kicker">Materiais</p><h2>Materiais vinculados</h2><p>Cadastre e mantenha os materiais desta lei usando o fluxo comercial existente.</p></div></header>{message ? <div className="admin-alert success" role="status">{message}</div> : null}{error ? <div className="admin-alert error" role="alert">{error}</div> : null}<form className="commercial-toolbar" onSubmit={(event) => { event.preventDefault(); if (page === 1) void load(); else setPage(1); }}><label>Busca<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filtrar materiais desta lei" /></label><button className="admin-button secondary" disabled={busy}>Filtrar</button></form><MaterialPanel rows={result.items} laws={[law]} fixedLaw={law} editing={editing} setEditing={setEditing} busy={busy} mutate={mutate} />{!busy && !result.items.length ? <div className="commercial-card law-center-empty"><h3>{query.trim() ? "Nenhum material encontrado" : "Esta lei ainda não possui materiais"}</h3><p>{query.trim() ? "Limpe ou altere o filtro para consultar novamente." : "Use o formulário acima para cadastrar o primeiro material já vinculado a esta lei."}</p></div> : null}{busy ? <p className="commercial-loading" role="status">Carregando…</p> : null}<footer className="commercial-pagination"><span>{result.total} registro(s)</span><button type="button" disabled={busy || page <= 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page} / {result.pages}</span><button type="button" disabled={busy || page >= result.pages} onClick={() => setPage(page + 1)}>Próxima</button></footer></section>;
}

export function MaterialPanel({ rows, laws, fixedLaw, editing, setEditing, busy, mutate }: { rows: Row[]; laws: Row[]; fixedLaw?: Row; editing: Row | null; setEditing: (row: Row | null) => void; busy: boolean; mutate: MaterialMutation }) {
  const [kind, setKind] = useState(text(editing?.tipo) || "flashcards");
  useEffect(() => setKind(text(editing?.tipo) || "flashcards"), [editing]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await mutate("materiais", { action: editing ? "atualizar" : "criar", id: editing?.id, data: { ...data, ...(editing ? {} : { lei_id: fixedLaw ? Number(fixedLaw.id) : Number(data.lei_id) }), ordem: Number(data.ordem), ativo: data.ativo === "true", quantidade_itens: data.quantidade_itens === "" ? null : Number(data.quantidade_itens) } }, "Material salvo com sucesso."); }
  return <><EditForm key={text(editing?.id) || "new"} title={editing ? "Editar material" : "Cadastrar material"} onSubmit={submit} onCancel={() => setEditing(null)} busy={busy}>
    {!editing && !fixedLaw ? <select name="lei_id" required defaultValue=""><option value="" disabled>Selecione a lei</option>{laws.map((law) => <option key={text(law.id)} value={text(law.id)}>{text(law.titulo)}</option>)}</select> : null}
    <select name="tipo" value={kind} onChange={(event) => setKind(event.target.value)}>{["flashcards","video","pdf","tutorial","audio","outro"].map((item) => <option key={item}>{item}</option>)}</select>
    <input name="titulo" defaultValue={text(editing?.titulo)} placeholder="Título" required /><textarea name="descricao" defaultValue={text(editing?.descricao)} placeholder="Descrição" />
    <select name="provedor" defaultValue={text(editing?.provedor) || "google_drive"}>{["google_drive","youtube","externo","supabase_storage"].map((item) => <option key={item}>{item}</option>)}</select>
    <input name="url_externa" type="url" defaultValue={text(editing?.url_externa)} placeholder="URL externa (opcional)" /><select name="acao" defaultValue={text(editing?.acao) || "abrir"}>{["abrir","baixar","assistir"].map((item) => <option key={item}>{item}</option>)}</select>
    <label>{kind === "flashcards" ? "Quantidade de flashcards" : "Quantidade de itens"}<input name="quantidade_itens" type="number" min="0" defaultValue={text(editing?.quantidade_itens)} /></label>
    <label>Versão do material<input name="versao_material" defaultValue={text(editing?.versao_material)} /></label><label>Data de revisão<input name="revisado_em" type="date" defaultValue={text(editing?.revisado_em)} /></label><label>Data de publicação<input name="publicado_em" type="date" defaultValue={text(editing?.publicado_em)} /></label><label>Entrega prevista<input name="data_entrega_prevista" type="date" defaultValue={text(editing?.data_entrega_prevista)} /></label>
    <textarea name="observacao_interna" defaultValue={text(editing?.observacao_interna)} placeholder="Observação interna — nunca exibida ao aluno ou catálogo" />
    <input name="ordem" type="number" min="0" defaultValue={text(editing?.ordem) || "0"} required /><select name="ativo" defaultValue={editing?.ativo === false ? "false" : "true"}><option value="true">Ativo</option><option value="false">Inativo</option></select>
  </EditForm><DataTable headers={["Material", "Lei", "Versão / quantidade", "Estado", "Ações"]}>{rows.map((row) => <tr key={text(row.id)}><td><strong>{text(row.titulo)}</strong><small><a href={text(row.url_externa)} target="_blank" rel="noreferrer">Abrir URL administrativa</a></small></td><td>{text(relation(row,"leis").titulo)}</td><td>{text(row.versao_material) || "—"}<small>{row.quantidade_itens == null ? "Quantidade não informada" : `${text(row.quantidade_itens)} ${row.tipo === "flashcards" ? "flashcards" : "itens"}`}</small></td><td>{row.ativo ? "Ativo" : "Inativo"}</td><td><button onClick={() => setEditing(row)}>Editar</button><button disabled={busy} onClick={() => void mutate("materiais", { action: "atualizar", id: row.id, data: { ativo: !row.ativo } }, "Estado do material atualizado.")}>{row.ativo ? "Desativar" : "Ativar"}</button></td></tr>)}</DataTable></>;
}
