"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { AdminQuestionEditor, adminQuestionFormFrom, blankAdminQuestionForm, type AdminQuestionForm, type AdminQuestionStructureNode } from "@/components/admin/admin-question-editor";
import { LawStructureAdmin } from "@/components/admin/law-structure-admin";
import { adminQuestionSearchTerms, type AdminQuestionSearchFilter } from "@/lib/admin-question-search";
import { questionResultNeighbor } from "@/lib/admin-question-management";

type Law = { id: number; slug: string; titulo: string };
type SearchResult = { id: string; structure_id: number | null; pergunta_trecho: string; resposta: "Certo" | "Errado"; artigo: string | null; assunto: string | null; ordem: string; ativo: boolean; updated_at: string };
type SearchResponse = { results: SearchResult[]; total: number; page: number; limit: number; pages: number };
type FullQuestion = AdminQuestionForm & { id: string; ativo: boolean };
type DeletionCampaign = { id: string; aluno_id: string; nome: string | null; email: string | null; concluida: boolean; abandonada: boolean; is_requesting_admin: boolean };
type DeletionSummary = { questions_count: number; structures_count: number; substructures_count: number; campaigns: DeletionCampaign[]; campaigns_count: number; answers_count: number; progresses_count: number; requires_confirmation: boolean; dependencies_count: number };

const answers: Array<{ value: AdminQuestionSearchFilter; label: string }> = [{ value: "all", label: "Todos os gabaritos" }, { value: "certo", label: "Certo" }, { value: "errado", label: "Errado" }, { value: "unstructured", label: "Sem estrutura" }];
async function readJson(response: Response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Não foi possível concluir a operação."); return body; }
async function post(body: Record<string, unknown>) { return fetch("/api/admin/questoes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }).then(readJson); }
function HighlightedText({ text, query }: { text: string; query: string }) { const terms = adminQuestionSearchTerms(query).map((term) => term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")); if (!terms.length) return <>{text}</>; const expression = new RegExp(`(${terms.join("|")})`, "gi"); return <>{text.split(expression).map((part, index) => terms.some((term) => new RegExp(`^${term}$`, "i").test(part)) ? <mark className="rounded bg-amber-100 px-0.5" key={`${part}-${index}`}>{part}</mark> : part)}</>; }

export function AdminLawQuestions({ law, initialStructure }: { law: Law; initialStructure: AdminQuestionStructureNode[] }) {
  const [nodes, setNodes] = useState(initialStructure);
  const [query, setQuery] = useState(""); const [debouncedQuery, setDebouncedQuery] = useState(""); const [filter, setFilter] = useState<AdminQuestionSearchFilter>("all"); const [article, setArticle] = useState(""); const [structureId, setStructureId] = useState<number | null>(null);
  const [page, setPage] = useState(1); const [results, setResults] = useState<SearchResult[]>([]); const [total, setTotal] = useState(0); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [refresh, setRefresh] = useState(0);
  const [editorOpen, setEditorOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [form, setForm] = useState<AdminQuestionForm>(blankAdminQuestionForm()); const [original, setOriginal] = useState<AdminQuestionForm | null>(null); const [saving, setSaving] = useState(false); const [editorError, setEditorError] = useState("");
  const [deletionSummary, setDeletionSummary] = useState<DeletionSummary | null>(null); const [deleteConfirmation, setDeleteConfirmation] = useState(""); const [moveOpen, setMoveOpen] = useState(false); const [moveDestination, setMoveDestination] = useState<number | null>(null);
  const titleRef = useRef<HTMLDivElement>(null); const savingRef = useRef(false);
  const structureMap = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const structurePath = (target: number | null) => { const names: string[] = []; for (let node = target ? structureMap.get(target) : undefined; node; node = node.parent_id ? structureMap.get(node.parent_id) : undefined) names.unshift(node.nome); return names.join(" › "); };
  const resultIds = results.map((item) => item.id); const previousId = editingId ? questionResultNeighbor(resultIds, editingId, -1) : null; const nextId = editingId ? questionResultNeighbor(resultIds, editingId, 1) : null;

  useEffect(() => { const timeout = window.setTimeout(() => { setDebouncedQuery(query.trim()); setPage(1); }, 350); return () => window.clearTimeout(timeout); }, [query]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); const params = new URLSearchParams({ law_slug: law.slug, mode: "search", q: debouncedQuery, filter, article, page: String(page), limit: "30" }); if (structureId) params.set("structure_id", String(structureId)); void fetch(`/api/admin/questoes?${params}`, { cache: "no-store", signal: controller.signal }).then(readJson).then((body: SearchResponse) => { setResults(body.results); setTotal(body.total); setPages(body.pages); }).catch((caught) => { if (!(caught instanceof DOMException && caught.name === "AbortError")) setError(caught instanceof Error ? caught.message : "Não foi possível pesquisar as questões."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [law.slug, debouncedQuery, filter, article, structureId, page, refresh]);
  useEffect(() => { if (!editorOpen) return; const overflow = document.body.style.overflow; const focus = document.activeElement instanceof HTMLElement ? document.activeElement : null; const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !savingRef.current) setEditorOpen(false); }; document.body.style.overflow = "hidden"; document.addEventListener("keydown", escape); titleRef.current?.focus(); return () => { document.body.style.overflow = overflow; document.removeEventListener("keydown", escape); focus?.focus(); }; }, [editorOpen]);

  async function reloadStructure() { const body = await fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(law.slug)}`, { cache: "no-store" }).then(readJson) as { structure: AdminQuestionStructureNode[] }; setNodes(body.structure); setRefresh((value) => value + 1); }
  function newQuestion(target = structureId) { setEditingId(null); setForm({ ...blankAdminQuestionForm(), structure_id: target }); setOriginal(null); setEditorError(""); setEditorOpen(true); }
  async function editQuestion(id: string) { setEditorError(""); setError(""); try { const params = new URLSearchParams({ law_slug: law.slug, question_id: id }); const body = await fetch(`/api/admin/questoes?${params}`, { cache: "no-store" }).then(readJson) as { question: FullQuestion }; const next = adminQuestionFormFrom(body.question); setEditingId(body.question.id); setForm(next); setOriginal(next); setEditorOpen(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível abrir a questão."); } }
  function navigateToQuestion(id: string) { if (original && JSON.stringify(form) !== JSON.stringify(original) && !window.confirm("Há alterações não salvas. Deseja descartá-las e abrir outra questão?")) return; void editQuestion(id); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const intent = ((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null)?.value; const savedId = editingId; const goNext = intent === "next" ? nextId : null; savingRef.current = true; setSaving(true); setEditorError(""); setMessage(""); try { const saved = await post({ action: savedId ? "atualizar" : "criar", law_slug: law.slug, id: savedId, data: form }) as FullQuestion; setMessage(savedId ? "Questão atualizada sem alterar o UUID." : "Questão cadastrada com novo UUID."); setRefresh((value) => value + 1); if (goNext) await editQuestion(goNext); else { setEditingId(saved.id); const next = adminQuestionFormFrom(saved); setForm(next); setOriginal(next); } } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível salvar a questão."); } finally { savingRef.current = false; setSaving(false); } }
  function duplicateQuestion() { setEditingId(null); setOriginal(null); setEditorError("Altere a ordem ou o enunciado antes de salvar; a unicidade da importação será validada."); setMessage("Cópia preparada. O novo registro receberá outro UUID ao salvar."); }
  async function askDeleteQuestion() { if (!editingId) return; setSaving(true); setEditorError(""); try { setDeletionSummary(await post({ action: "resumo_exclusao_questao", law_slug: law.slug, id: editingId }) as DeletionSummary); setDeleteConfirmation(""); } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível analisar a exclusão."); } finally { setSaving(false); } }
  async function deleteQuestion() { if (!editingId) return; setSaving(true); try { await post({ action: "excluir_questao", law_slug: law.slug, id: editingId, confirmation: deleteConfirmation }); setDeletionSummary(null); setEditorOpen(false); setEditingId(null); setMessage("Questão e campanhas afetadas excluídas definitivamente."); setRefresh((value) => value + 1); } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível excluir a questão."); } finally { setSaving(false); } }
  async function moveQuestion() { if (!editingId) return; setSaving(true); try { await post({ action: "mover_questao", law_slug: law.slug, id: editingId, structure_id: moveDestination }); setForm((value) => ({ ...value, structure_id: moveDestination })); setOriginal((value) => value ? { ...value, structure_id: moveDestination } : value); setMoveOpen(false); setMessage("Questão movida dentro da mesma lei."); setRefresh((value) => value + 1); } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível mover a questão."); } finally { setSaving(false); } }

  return <section className="grid gap-5">
    <header className="law-center-page-heading"><div><p className="law-center-kicker">Questões</p><h2>{law.titulo}</h2><p>{total} questão(ões) no resultado atual · pesquisa e manutenção preservando UUIDs.</p></div><div className="law-center-quick-actions"><Link className="admin-button secondary" href={`/admin/leis/${encodeURIComponent(law.slug)}`}>← Central da Lei</Link><button type="button" className="admin-button primary" onClick={() => newQuestion()}>Nova questão</button></div></header>
    <article className="commercial-card grid gap-4"><label className="text-base font-bold">Pesquisar nesta lei<input autoFocus className="mt-1 min-h-14 w-full text-base" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Enunciado, artigo, assunto, ordem, estrutura ou justificativa" /></label><div className="grid gap-3 sm:grid-cols-2"><label>Artigo<input value={article} onChange={(event) => { setArticle(event.target.value); setPage(1); }} placeholder="Ex.: Art. 12" /></label><label>Gabarito<select value={filter} onChange={(event) => { setFilter(event.target.value as AdminQuestionSearchFilter); setPage(1); }}>{answers.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div></article>
    {message ? <p className="admin-alert success" role="status">{message}</p> : null}{error ? <p className="admin-alert error" role="alert">{error}</p> : null}
    <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(260px,340px)_minmax(0,1fr)]"><aside className="grid content-start gap-3"><article className="commercial-card"><div className="flex items-center justify-between gap-2"><h3 className="font-black">Estrutura da lei</h3>{structureId ? <button type="button" className="admin-link-button" onClick={() => setStructureId(null)}>Limpar</button> : null}</div><StructureFilter nodes={nodes} selected={structureId} onSelect={(id) => { setStructureId(id); setPage(1); }} /></article><details><summary className="admin-button secondary cursor-pointer">Gerenciar estruturas</summary><div className="mt-3"><LawStructureAdmin lawSlug={law.slug} nodes={nodes} onReload={reloadStructure} onSelectNode={(node) => { setStructureId(node.id); setPage(1); }} selectNodeLabel="Filtrar questões" /></div></details></aside>
      <section className="grid min-w-0 content-start gap-3" aria-live="polite" aria-busy={loading}><div className="flex items-center justify-between gap-3"><h3 className="text-lg font-black">Questões encontradas</h3><span className="text-sm text-slate-600">{total} item(ns)</span></div>{loading ? <p className="commercial-card commercial-loading">Pesquisando…</p> : results.map((question) => <button type="button" key={question.id} onClick={() => void editQuestion(question.id)} className="commercial-card grid w-full gap-2 text-left transition hover:border-blue-300 hover:shadow-sm"><div className="flex flex-wrap items-center gap-2"><strong className="text-blue-800">#{question.ordem}</strong><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${question.resposta === "Certo" ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}`}>{question.resposta}</span>{question.artigo ? <span className="text-sm font-bold text-slate-700">{question.artigo}</span> : null}</div><p className="line-clamp-3 text-sm text-slate-800"><HighlightedText text={question.pergunta_trecho || "Questão sem trecho disponível"} query={debouncedQuery} /></p><div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500">{question.assunto ? <span>Assunto: {question.assunto}</span> : null}<span>Estrutura: {structurePath(question.structure_id) || "Sem estrutura"}</span></div></button>)}{!loading && !results.length ? <article className="commercial-card law-center-empty"><h3>Nenhuma questão encontrada</h3><p>Ajuste a busca ou os filtros selecionados.</p><div className="flex flex-wrap gap-2"><button type="button" className="admin-button primary" onClick={() => newQuestion()}>Cadastrar questão</button><Link className="admin-button secondary" href={`/admin/leis/${encodeURIComponent(law.slug)}/anki`}>Abrir Anki</Link></div></article> : null}</section>
    </div>
    {pages > 1 ? <nav className="flex items-center justify-center gap-3" aria-label="Paginação das questões"><button type="button" className="admin-button secondary" disabled={loading || page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Anterior</button><span className="text-sm">Página {page} de {pages}</span><button type="button" className="admin-button secondary" disabled={loading || page >= pages} onClick={() => setPage((value) => value + 1)}>Próxima</button></nav> : null}
    {editorOpen ? <div className="fixed inset-0 z-50 bg-slate-950/45" role="presentation"><div ref={titleRef} tabIndex={-1} className="absolute inset-0 overflow-y-auto bg-slate-50 p-3 outline-none xl:left-auto xl:w-[min(94vw,1120px)] xl:p-5" role="dialog" aria-modal="true" aria-labelledby="admin-question-editor-title"><div className="mb-3 flex justify-end"><button type="button" className="admin-button secondary" disabled={saving} onClick={() => setEditorOpen(false)}>Fechar</button></div><AdminQuestionEditor lawName={law.titulo} nodes={nodes} value={form} original={original} editing={Boolean(editingId)} saving={saving} error={editorError} onChange={setForm} onSubmit={(event) => void save(event)} onCancel={() => setEditorOpen(false)} onPrevious={previousId ? () => navigateToQuestion(previousId) : undefined} onNext={nextId ? () => navigateToQuestion(nextId) : undefined} onDuplicate={duplicateQuestion} onMove={() => { setMoveDestination(form.structure_id); setMoveOpen(true); }} onDelete={() => void askDeleteQuestion()} showPreview /></div></div> : null}
    {deletionSummary ? <DeletionConfirmation summary={deletionSummary} confirmation={deleteConfirmation} saving={saving} targetLabel="questão" onConfirmation={setDeleteConfirmation} onCancel={() => setDeletionSummary(null)} onConfirm={() => void deleteQuestion()} /> : null}
    {moveOpen ? <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="move-question-title"><h2 id="move-question-title">Mover para outra estrutura</h2><label>Destino<select value={moveDestination ?? ""} onChange={(event) => setMoveDestination(event.target.value ? Number(event.target.value) : null)}><option value="">Sem estrutura</option>{nodes.map((node) => <option key={node.id} value={node.id}>{structurePath(node.id)}</option>)}</select></label><div className="admin-modal-actions"><button className="admin-button secondary" type="button" onClick={() => setMoveOpen(false)}>Cancelar</button><button className="admin-button primary" type="button" disabled={saving} onClick={() => void moveQuestion()}>Mover</button></div></section></div> : null}
  </section>;
}

function StructureFilter({ nodes, selected, onSelect, parentId = null, depth = 0 }: { nodes: AdminQuestionStructureNode[]; selected: number | null; onSelect: (id: number) => void; parentId?: number | null; depth?: number }) { const children = nodes.filter((node) => node.parent_id === parentId).sort((a, b) => a.ordem - b.ordem || a.nome.localeCompare(b.nome, "pt-BR")); if (!children.length && depth === 0) return <p className="mt-3 text-sm text-slate-500">Sem estrutura cadastrada.</p>; return <ul className={depth ? "mt-1" : "mt-3"}>{children.map((node) => <li key={node.id}><button type="button" aria-pressed={selected === node.id} className={`w-full rounded-lg px-2 py-1.5 text-left text-sm ${selected === node.id ? "bg-blue-100 font-black text-blue-800" : "hover:bg-slate-100"}`} style={{ paddingLeft: 8 + depth * 14 }} onClick={() => onSelect(node.id)}>{node.nome}</button><StructureFilter nodes={nodes} selected={selected} onSelect={onSelect} parentId={node.id} depth={depth + 1} /></li>)}</ul>; }

function DeletionConfirmation({ summary, confirmation, saving, targetLabel, onConfirmation, onCancel, onConfirm }: { summary: DeletionSummary; confirmation: string; saving: boolean; targetLabel: string; onConfirmation: (value: string) => void; onCancel: () => void; onConfirm: () => void }) {
  return <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="delete-question-title"><h2 id="delete-question-title">Excluir {targetLabel} definitivamente?</h2><p>Serão removidas {summary.questions_count} questão(ões), {summary.campaigns_count} campanha(s), {summary.answers_count} resposta(s) e {summary.progresses_count} progresso(s) ativo(s).</p>{summary.campaigns.length ? <div><h3 className="font-bold">Campanhas afetadas e titulares</h3><ul>{summary.campaigns.map((campaign) => <li key={campaign.id}>{campaign.nome || "Aluno sem nome"} · {campaign.email || campaign.aluno_id}{campaign.is_requesting_admin ? " · conta administrativa" : " · outro aluno"}</li>)}</ul></div> : <p>Nenhuma campanha será removida.</p>}<p className="admin-alert error">A exclusão é definitiva e não possui lixeira ou restauração.</p>{summary.requires_confirmation ? <label>Para confirmar campanhas de outros alunos, digite <strong>EXCLUIR</strong><input autoFocus value={confirmation} onChange={(event) => onConfirmation(event.target.value)} /></label> : null}<div className="admin-modal-actions"><button className="admin-button secondary" type="button" disabled={saving} onClick={onCancel}>Cancelar</button><button className="admin-button danger" type="button" disabled={saving || (summary.requires_confirmation && confirmation !== "EXCLUIR")} onClick={onConfirm}>{saving ? "Excluindo…" : `Excluir ${targetLabel} e campanhas afetadas`}</button></div></section></div>;
}
