"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { buildScopeTree, descendantsForScope, normalizeScopeSelection, type ScopeTreeNode } from "@/lib/law-question-scope-resolution";

type ScopeNode = { id: number; parent_id: number | null; tipo: string; nome: string };
type Status = "ativa" | "em_breve" | "inativa";
type LawScope = { id: string; nome: string; descricao: string | null; ativo: boolean; status_publicacao?: Status; structure_ids: number[]; question_count: number };

async function api<T>(url: string, init?: RequestInit) {
  const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || "Erro na operação.");
  return body as T;
}

export function LawScopesPanel({ lawSlug }: { lawSlug: string }) {
  const [nodes, setNodes] = useState<ScopeNode[]>([]); const [questions, setQuestions] = useState<Array<{ id: string; structure_id: number | null }>>([]); const [scopes, setScopes] = useState<LawScope[]>([]); const [unstructured, setUnstructured] = useState(0); const [editing, setEditing] = useState<LawScope | null>(null); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [status, setStatus] = useState<Status>("ativa"); const [selected, setSelected] = useState<number[]>([]); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const result = await api<{ structure: ScopeNode[]; questions: Array<{ id: string; structure_id: number | null }>; recortes: LawScope[]; unstructured_questions: number }>(`/api/admin/questoes?law_slug=${encodeURIComponent(lawSlug)}&recortes=1`); setNodes(result.structure); setQuestions(result.questions); setScopes(result.recortes); setUnstructured(result.unstructured_questions); } finally { setLoading(false); } }, [lawSlug]);
  useEffect(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "Não foi possível carregar os recortes.")); }, [load]);
  const tree = useMemo(() => buildScopeTree(nodes), [nodes]); const effectiveSelected = useMemo(() => new Set(descendantsForScope(nodes, selected)), [nodes, selected]); const questionCount = useMemo(() => questions.filter((question) => question.structure_id !== null && effectiveSelected.has(question.structure_id)).length, [effectiveSelected, questions]);
  const begin = (scope?: LawScope) => { setOpen(true); setEditing(scope ?? null); setName(scope?.nome ?? ""); setDescription(scope?.descricao ?? ""); setStatus(scope?.status_publicacao ?? (scope?.ativo === false ? "inativa" : "ativa")); setSelected(normalizeScopeSelection(nodes, scope?.structure_ids ?? [])); setError(""); };
  const close = () => { setOpen(false); setEditing(null); setName(""); setDescription(""); setSelected([]); };
  const toggle = (nodeId: number, checked: boolean) => setSelected((current) => normalizeScopeSelection(nodes, checked ? [...current, nodeId] : current.filter((id) => id !== nodeId)));
  const save = async () => { setSaving(true); setError(""); try { await api("/api/admin/questoes", { method: "POST", body: JSON.stringify({ action: "salvar_recorte", law_slug: lawSlug, id: editing?.id, nome: name, descricao: description, status_publicacao: status, structure_ids: normalizeScopeSelection(nodes, selected) }) }); await load(); close(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar o recorte."); } finally { setSaving(false); } };
  const statusLabel = (scope: LawScope) => scope.status_publicacao === "em_breve" ? "Em breve" : scope.status_publicacao === "inativa" || !scope.ativo ? "Inativo" : "Ativo";
  return <article className="commercial-card"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="law-center-kicker">Recortes</p><h2>Recortes da lei</h2><p className="text-sm text-slate-600">Reaproveitam questões canônicas por estrutura.</p></div><button type="button" className="admin-button secondary" onClick={() => begin()}>+ Novo recorte</button></div>{unstructured ? <p className="admin-alert error">⚠ {unstructured} questões desta lei ainda não estão vinculadas a uma estrutura e não podem ser selecionadas por recorte.</p> : null}{error ? <p className="admin-alert error" role="alert">{error}</p> : null}{loading ? <p className="commercial-loading" role="status">Carregando recortes…</p> : null}{!loading && !scopes.length && !open ? <div className="admin-empty law-center-empty"><h3>Nenhum recorte cadastrado</h3><p>Crie um recorte quando precisar oferecer apenas uma parte da estrutura desta lei.</p><button type="button" className="admin-button primary" onClick={() => begin()}>Criar primeiro recorte</button></div> : null}{scopes.map((scope) => <p key={scope.id} className="mt-3 flex flex-wrap items-center gap-2"><strong>{scope.nome}</strong><span>{scope.question_count} questões</span><span>{statusLabel(scope)}</span><button type="button" className="admin-link-button" onClick={() => begin(scope)}>Editar</button></p>)}{open ? <section className="mt-4 border-t pt-4"><label>Nome<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Descrição opcional<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Status de publicação<select value={status} onChange={(event) => setStatus(event.target.value as Status)}><option value="ativa">Ativa</option><option value="em_breve">Em breve</option><option value="inativa">Inativa</option></select></label><p className="mt-3 text-sm font-bold">Selecionar estrutura</p><ScopeSelectionTree nodes={tree} selected={selected} effectiveSelected={effectiveSelected} onToggle={toggle} /><p className="mt-3 font-bold">Questões alcançadas: {questionCount}</p><div className="mt-3 flex gap-2"><button type="button" disabled={saving || !name.trim() || !selected.length} className="admin-button primary" onClick={() => void save()}>{saving ? "Salvando…" : "Salvar recorte"}</button><button type="button" className="admin-button secondary" disabled={saving} onClick={close}>Cancelar</button></div></section> : null}</article>;
}

function ScopeSelectionTree({ nodes, selected, effectiveSelected, onToggle }: { nodes: Array<ScopeTreeNode<ScopeNode>>; selected: number[]; effectiveSelected: Set<number>; onToggle: (id: number, checked: boolean) => void }) { const explicit = new Set(selected); return <ul className="scope-selection-tree">{nodes.map((node) => { const inherited = effectiveSelected.has(node.id) && !explicit.has(node.id); return <li key={node.id}><label className={inherited ? "scope-inherited" : ""}><input type="checkbox" checked={effectiveSelected.has(node.id)} disabled={inherited} onChange={(event) => onToggle(node.id, event.target.checked)} /> <span><strong>{node.tipo}:</strong> {node.nome}</span>{inherited ? <small>Incluído pelo pai</small> : null}</label>{node.children.length ? <ScopeSelectionTree nodes={node.children} selected={selected} effectiveSelected={effectiveSelected} onToggle={onToggle} /> : null}</li>; })}</ul>; }
