"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { AdminQuestionEditor, adminQuestionFormFrom, blankAdminQuestionForm, type AdminQuestionForm, type AdminQuestionStructureNode } from "@/components/admin/admin-question-editor";
import { AdminQuestionConference } from "@/components/admin/admin-question-conference";
import { QuestionRichEditor } from "@/components/admin/question-rich-editor";
import { LawStructureAdmin } from "@/components/admin/law-structure-admin";
import { LawQuestionShadows } from "@/components/admin/law-question-shadows";
import { adminQuestionSearchTerms, type AdminQuestionSearchFilter, type AdminQuestionSearchSort } from "@/lib/admin-question-search";
import { questionResultNeighbor } from "@/lib/admin-question-management";
import { QUESTION_BULK_FIELD_LABELS, questionFieldDisplayValue, type BulkQuestionEditScope } from "@/lib/admin-question-bulk-edit";
import { QUESTION_ANSWERS, type QuestionEditableField } from "@/lib/admin-questoes";

type Law = { id: number; slug: string; titulo: string };
type SearchResult = { id: string; structure_id: number | null; pergunta_trecho: string; resposta: "Certo" | "Errado"; artigo: string | null; assunto: string | null; ordem: string; ativo: boolean; updated_at: string };
type SearchResponse = { results: SearchResult[]; total: number; page: number; limit: number; pages: number };
type FullQuestion = AdminQuestionForm & { id: string; ativo: boolean };
type DeletionCampaign = { id: string; aluno_id: string; nome: string | null; email: string | null; concluida: boolean; abandonada: boolean; is_requesting_admin: boolean };
type DeletionSummary = { questions_count: number; structures_count: number; substructures_count: number; campaigns: DeletionCampaign[]; campaigns_count: number; answers_count: number; progresses_count: number; requires_confirmation: boolean; dependencies_count: number };
type BulkScope = "structure" | "results" | "all";
type BulkEditPreview = { field: QuestionEditableField; value: unknown; selection_count: number; changed_count: number; unchanged_count: number; sample: Array<{ id: string; before: unknown; after: unknown }>; expected: Array<{ id: string; before: unknown }> };

const answers: Array<{ value: AdminQuestionSearchFilter; label: string }> = [{ value: "all", label: "Todos os gabaritos" }, { value: "certo", label: "Certo" }, { value: "errado", label: "Errado" }, { value: "unstructured", label: "Sem estrutura" }];
const sortOptions: Array<{ value: AdminQuestionSearchSort; label: string }> = [{ value: "recent", label: "Mais recentes" }, { value: "ordem_asc", label: "Ordem crescente" }, { value: "ordem_desc", label: "Ordem decrescente" }];
async function readJson(response: Response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Não foi possível concluir a operação."); return body; }
async function post(body: Record<string, unknown>) { return fetch("/api/admin/questoes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }).then(readJson); }
function HighlightedText({ text, query }: { text: string; query: string }) { const terms = adminQuestionSearchTerms(query).map((term) => term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")); if (!terms.length) return <>{text}</>; const expression = new RegExp(`(${terms.join("|")})`, "gi"); return <>{text.split(expression).map((part, index) => terms.some((term) => new RegExp(`^${term}$`, "i").test(part)) ? <mark className="rounded bg-amber-100 px-0.5" key={`${part}-${index}`}>{part}</mark> : part)}</>; }

export function AdminLawQuestions({ law, initialStructure, initialQuestion = null, initialDraft = null, sourceLegisBotId = null, returnHref = "" }: { law: Law; initialStructure: AdminQuestionStructureNode[]; initialQuestion?: FullQuestion | null; initialDraft?: AdminQuestionForm | null; sourceLegisBotId?: number | null; returnHref?: string }) {
  const [nodes, setNodes] = useState(initialStructure);
  const [reviewedStructures, setReviewedStructures] = useState<Set<number>>(new Set()); const [lawReviewed, setLawReviewed] = useState(false); const [reviewSaving, setReviewSaving] = useState<number | "law" | null>(null);
  const [query, setQuery] = useState(""); const [debouncedQuery, setDebouncedQuery] = useState(""); const [filter, setFilter] = useState<AdminQuestionSearchFilter>("all"); const [sort, setSort] = useState<AdminQuestionSearchSort>("recent"); const [article, setArticle] = useState(""); const [structureId, setStructureId] = useState<number | null>(null);
  const [page, setPage] = useState(1); const [results, setResults] = useState<SearchResult[]>([]); const [total, setTotal] = useState(0); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [refresh, setRefresh] = useState(0); const [shadowVersion, setShadowVersion] = useState(0);
  const initialForm = initialQuestion ? adminQuestionFormFrom(initialQuestion) : initialDraft;
  const [editorOpen, setEditorOpen] = useState(Boolean(initialQuestion || initialDraft)); const [editingId, setEditingId] = useState<string | null>(initialQuestion?.id ?? null); const [form, setForm] = useState<AdminQuestionForm>(initialForm ?? blankAdminQuestionForm()); const [original, setOriginal] = useState<AdminQuestionForm | null>(initialForm); const [saving, setSaving] = useState(false); const [editorError, setEditorError] = useState("");
  const [deletionSummary, setDeletionSummary] = useState<DeletionSummary | null>(null); const [deleteConfirmation, setDeleteConfirmation] = useState(""); const [moveOpen, setMoveOpen] = useState(false); const [moveDestination, setMoveDestination] = useState<number | null>(null);
  const [bulkOpen, setBulkOpen] = useState(false); const [bulkScope, setBulkScope] = useState<BulkScope>("results"); const [bulkSummary, setBulkSummary] = useState<DeletionSummary | null>(null); const [bulkConfirmation, setBulkConfirmation] = useState("");
  const [conferenceOpen, setConferenceOpen] = useState(false);
  const [questionView, setQuestionView] = useState<"ativas" | "sombra">("ativas");
  const [selectedQuestionIds, setSelectedQuestionIds] = useState<string[]>([]); const [bulkEditOpen, setBulkEditOpen] = useState(false); const [bulkEditScope, setBulkEditScope] = useState<BulkQuestionEditScope>("selected"); const [bulkEditField, setBulkEditField] = useState<QuestionEditableField>("total_artigos"); const [bulkEditValue, setBulkEditValue] = useState<unknown>(null); const [bulkEditPreview, setBulkEditPreview] = useState<BulkEditPreview | null>(null);
  const titleRef = useRef<HTMLDivElement>(null); const savingRef = useRef(false);
  const structureMap = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const structurePath = (target: number | null) => { const names: string[] = []; for (let node = target ? structureMap.get(target) : undefined; node; node = node.parent_id ? structureMap.get(node.parent_id) : undefined) names.unshift(node.nome); return names.join(" › "); };
  const selectedStructurePath = structureId ? structurePath(structureId).split(" › ").filter(Boolean) : [];
  const resultIds = results.map((item) => item.id); const previousId = editingId ? questionResultNeighbor(resultIds, editingId, -1) : null; const nextId = editingId ? questionResultNeighbor(resultIds, editingId, 1) : null;

  useEffect(() => { const timeout = window.setTimeout(() => { setDebouncedQuery(query.trim()); setPage(1); }, 350); return () => window.clearTimeout(timeout); }, [query]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); const params = new URLSearchParams({ law_slug: law.slug, mode: "search", q: debouncedQuery, filter, sort, article, page: String(page), limit: "30" }); if (structureId) params.set("structure_id", String(structureId)); void fetch(`/api/admin/questoes?${params}`, { cache: "no-store", signal: controller.signal }).then(readJson).then((body: SearchResponse) => { setResults(body.results); setTotal(body.total); setPages(body.pages); }).catch((caught) => { if (!(caught instanceof DOMException && caught.name === "AbortError")) setError(caught instanceof Error ? caught.message : "Não foi possível pesquisar as questões."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [law.slug, debouncedQuery, filter, sort, article, structureId, page, refresh]);
  useEffect(() => { const controller = new AbortController(); void fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(law.slug)}&mode=structure-reviews`, { cache: "no-store", signal: controller.signal }).then(readJson).then((body: { reviewed: number[]; law_reviewed: boolean }) => { setReviewedStructures(new Set(body.reviewed)); setLawReviewed(body.law_reviewed); }).catch((caught) => { if (!(caught instanceof DOMException && caught.name === "AbortError")) setError(caught instanceof Error ? caught.message : "Não foi possível carregar as marcações de conferência."); }); return () => controller.abort(); }, [law.slug]);
  useEffect(() => { if (!editorOpen) return; const overflow = document.body.style.overflow; const focus = document.activeElement instanceof HTMLElement ? document.activeElement : null; const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !savingRef.current) setEditorOpen(false); }; document.body.style.overflow = "hidden"; document.addEventListener("keydown", escape); titleRef.current?.focus(); return () => { document.body.style.overflow = overflow; document.removeEventListener("keydown", escape); focus?.focus(); }; }, [editorOpen]);

  async function reloadStructure() { const body = await fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(law.slug)}`, { cache: "no-store" }).then(readJson) as { structure: AdminQuestionStructureNode[] }; setNodes(body.structure); setRefresh((value) => value + 1); }
  function newQuestion(target = structureId) { setEditingId(null); setForm({ ...blankAdminQuestionForm(), structure_id: target }); setOriginal(null); setEditorError(""); setEditorOpen(true); }
  function newShadowQuestion(data: AdminQuestionForm, notice: string) { setQuestionView("ativas"); setEditingId(null); setForm(data); setOriginal(null); setEditorError(""); setMessage(notice); setEditorOpen(true); }
  async function editQuestion(id: string) { setEditorError(""); setError(""); try { const params = new URLSearchParams({ law_slug: law.slug, question_id: id }); const body = await fetch(`/api/admin/questoes?${params}`, { cache: "no-store" }).then(readJson) as { question: FullQuestion }; const next = adminQuestionFormFrom(body.question); setEditingId(body.question.id); setForm(next); setOriginal(next); setEditorOpen(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível abrir a questão."); } }
  function navigateToQuestion(id: string) { if (original && JSON.stringify(form) !== JSON.stringify(original) && !window.confirm("Há alterações não salvas. Deseja descartá-las e abrir outra questão?")) return; void editQuestion(id); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const intent = ((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null)?.value; const savedId = editingId; const goNext = intent === "next" ? nextId : null; savingRef.current = true; setSaving(true); setEditorError(""); setMessage(""); try { const saved = await post({ action: savedId ? "atualizar" : "criar", law_slug: law.slug, id: savedId, data: form, legisbot_id: !savedId ? sourceLegisBotId : null }) as FullQuestion; setMessage(savedId ? "Questão atualizada sem alterar o UUID." : "Questão cadastrada com novo UUID."); setRefresh((value) => value + 1); setShadowVersion((value) => value + 1); if (returnHref && savedId === initialQuestion?.id) { window.location.assign(returnHref); return; } if (goNext) await editQuestion(goNext); else { setEditingId(saved.id); const next = adminQuestionFormFrom(saved); setForm(next); setOriginal(next); } } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível salvar a questão."); } finally { savingRef.current = false; setSaving(false); } }
  function duplicateQuestion() { setEditingId(null); setOriginal(null); setEditorError("Altere a ordem ou o enunciado antes de salvar; a unicidade da importação será validada."); setMessage("Cópia preparada. O novo registro receberá outro UUID ao salvar."); }
  async function askDeleteQuestion() { if (!editingId) return; setSaving(true); setEditorError(""); try { setDeletionSummary(await post({ action: "resumo_exclusao_questao", law_slug: law.slug, id: editingId }) as DeletionSummary); setDeleteConfirmation(""); } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível analisar a exclusão."); } finally { setSaving(false); } }
  async function deleteQuestion() { if (!editingId) return; setSaving(true); try { await post({ action: "excluir_questao", law_slug: law.slug, id: editingId, confirmation: deleteConfirmation }); setDeletionSummary(null); setEditorOpen(false); setEditingId(null); setMessage("Questão e campanhas afetadas excluídas definitivamente."); setRefresh((value) => value + 1); } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível excluir a questão."); } finally { setSaving(false); } }
  function bulkPayload() { return { law_slug: law.slug, scope: bulkScope, structure_id: bulkScope === "structure" ? structureId : null, query: debouncedQuery, filter, article }; }
  async function askBulkDelete() { if (bulkScope === "structure" && !structureId) { setError("Selecione uma estrutura antes de excluir suas questões e descendentes."); return; } setSaving(true); setError(""); try { setBulkSummary(await post({ action: "resumo_exclusao_questoes", ...bulkPayload() }) as DeletionSummary); setBulkConfirmation(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível analisar a exclusão em massa."); } finally { setSaving(false); } }
  async function deleteBulkQuestions() { setSaving(true); try { await post({ action: "excluir_questoes", ...bulkPayload(), confirmation: bulkConfirmation }); setBulkSummary(null); setBulkOpen(false); setMessage("Questões e campanhas afetadas excluídas definitivamente; a estrutura foi preservada."); setRefresh((value) => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível excluir as questões."); } finally { setSaving(false); } }
  function bulkEditPayload() { return { law_slug: law.slug, scope: bulkEditScope, field: bulkEditField, value: bulkEditValue, question_ids: bulkEditScope === "selected" ? selectedQuestionIds : undefined, query: debouncedQuery, filter, article, structure_id: structureId }; }
  async function previewBulkEdit() { if (bulkEditScope === "selected" && !selectedQuestionIds.length) { setError("Selecione ao menos uma questão para esta abrangência."); return; } setSaving(true); setError(""); try { setBulkEditPreview(await post({ action: "previsualizar_edicao_lote", ...bulkEditPayload() }) as BulkEditPreview); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível gerar a prévia da edição em lote."); } finally { setSaving(false); } }
  async function applyBulkEdit() { if (!bulkEditPreview) return; setSaving(true); setError(""); try { const result = await post({ action: "aplicar_edicao_lote", ...bulkEditPayload(), expected: bulkEditPreview.expected }) as { changed_count: number }; setBulkEditOpen(false); setBulkEditPreview(null); setMessage(`${result.changed_count} questão(ões) atualizada(s), sem alterar UUIDs, campanhas ou progresso.`); setRefresh((value) => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível aplicar a edição em lote."); } finally { setSaving(false); } }
  function toggleQuestion(id: string) { setSelectedQuestionIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function toggleAllVisibleQuestions() { setSelectedQuestionIds((current) => { const visible = results.map((question) => question.id); const visibleSet = new Set(visible); const allVisibleSelected = visible.length > 0 && visible.every((id) => current.includes(id)); return allVisibleSelected ? current.filter((id) => !visibleSet.has(id)) : [...new Set([...current, ...visible])]; }); }
  async function moveQuestion() { if (!editingId) return; setSaving(true); try { await post({ action: "mover_questao", law_slug: law.slug, id: editingId, structure_id: moveDestination }); setForm((value) => ({ ...value, structure_id: moveDestination })); setOriginal((value) => value ? { ...value, structure_id: moveDestination } : value); setMoveOpen(false); setMessage("Questão movida dentro da mesma lei."); setRefresh((value) => value + 1); } catch (caught) { setEditorError(caught instanceof Error ? caught.message : "Não foi possível mover a questão."); } finally { setSaving(false); } }
  async function toggleStructureReview(structure: AdminQuestionStructureNode | null) { const reviewed = structure ? !reviewedStructures.has(structure.id) : !lawReviewed; const previous = new Set(reviewedStructures); const previousLawReviewed = lawReviewed; if (structure) setReviewedStructures((current) => { const next = new Set(current); if (reviewed) next.add(structure.id); else next.delete(structure.id); return next; }); else setLawReviewed(reviewed); setReviewSaving(structure?.id ?? "law"); setError(""); try { await post({ action: "marcar_revisao_estrutura", law_slug: law.slug, structure_id: structure?.id ?? null, reviewed }); } catch (caught) { setReviewedStructures(previous); setLawReviewed(previousLawReviewed); setError(caught instanceof Error ? caught.message : "Não foi possível salvar a marcação de conferência."); } finally { setReviewSaving(null); } }

  return <section className="grid gap-5">
    <header className="law-center-page-heading"><div><p className="law-center-kicker">Questões</p><h2>{law.titulo}</h2><p>{questionView === "ativas" ? `${total} questão(ões) no resultado atual · pesquisa e manutenção preservando UUIDs.` : "Identifique dispositivos sem questão, por trecho ou pela lei inteira."}</p></div><div className="law-center-quick-actions"><Link className="admin-button secondary" href={`/admin/leis/${encodeURIComponent(law.slug)}`}>← Central da Lei</Link>{questionView === "ativas" ? <><button type="button" className="admin-button secondary" disabled={Boolean(nodes.length && !structureId)} title={nodes.length ? structureId ? "Conferir todas as questões deste bloco" : "Selecione um bloco estrutural primeiro" : "Conferir todas as questões desta lei"} onClick={() => setConferenceOpen(true)}>Modo conferência</button><button type="button" className="admin-button secondary" onClick={() => { setBulkEditOpen(true); setBulkEditPreview(null); }}>Editar em lote{selectedQuestionIds.length ? ` (${selectedQuestionIds.length})` : ""}</button><button type="button" className="admin-button danger" onClick={() => { setBulkOpen(true); setBulkSummary(null); setBulkConfirmation(""); }}>Excluir questões</button><button type="button" className="admin-button primary" onClick={() => newQuestion()}>Nova questão</button></> : null}</div></header>
    <nav className="flex border-b border-slate-200" role="tablist" aria-label="Visão de questões"><button type="button" role="tab" aria-selected={questionView === "ativas"} className={`px-4 py-3 text-sm font-black ${questionView === "ativas" ? "border-b-2 border-blue-600 text-blue-700" : "text-slate-600 hover:text-slate-900"}`} onClick={() => setQuestionView("ativas")}>Questões ativas</button><button type="button" role="tab" aria-selected={questionView === "sombra"} className={`px-4 py-3 text-sm font-black ${questionView === "sombra" ? "border-b-2 border-blue-600 text-blue-700" : "text-slate-600 hover:text-slate-900"}`} onClick={() => setQuestionView("sombra")}>Artigo Sombra</button></nav>
    {questionView === "ativas" ? <article className="commercial-card grid gap-4"><label className="grid gap-2 text-base font-bold">Pesquisar nesta lei<input autoFocus className="min-h-14 w-full text-base" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Enunciado, artigo, assunto, ordem, estrutura, justificativa ou UUID" /></label><div className="grid gap-4 sm:grid-cols-3"><label className="grid gap-2 font-medium">Artigo<input value={article} onChange={(event) => { setArticle(event.target.value); setPage(1); }} placeholder="Ex.: Art. 12" /></label><label className="grid gap-2 font-medium">Gabarito<select value={filter} onChange={(event) => { setFilter(event.target.value as AdminQuestionSearchFilter); setPage(1); }}>{answers.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="grid gap-2 font-medium">Ordenar por<select value={sort} onChange={(event) => { setSort(event.target.value as AdminQuestionSearchSort); setPage(1); }}>{sortOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div></article> : null}
    {questionView === "sombra" ? <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(260px,340px)_minmax(0,1fr)]"><aside className="grid content-start gap-3"><article className="commercial-card"><div className="flex items-center justify-between gap-2"><h3 className="font-black">Estrutura da lei</h3>{structureId ? <button type="button" className="admin-link-button" onClick={() => setStructureId(null)}>Limpar</button> : null}</div><StructureFilter nodes={nodes} selected={structureId} onSelect={(id) => { setStructureId(id); setPage(1); }} reviewed={reviewedStructures} lawReviewed={lawReviewed} reviewSaving={reviewSaving} onToggleReview={(node) => void toggleStructureReview(node)} /></article><details><summary className="admin-button secondary cursor-pointer">Gerenciar estruturas</summary><div className="mt-3"><LawStructureAdmin lawSlug={law.slug} nodes={nodes} onReload={reloadStructure} onSelectNode={(node) => { setStructureId(node.id); setPage(1); }} selectNodeLabel="Filtrar Artigos Sombra" /></div></details></aside><LawQuestionShadows key={shadowVersion} lawSlug={law.slug} structurePath={selectedStructurePath} onCreate={newShadowQuestion} /></div> : null}
    {message ? <p className="admin-alert success" role="status">{message}</p> : null}{error ? <p className="admin-alert error" role="alert">{error}</p> : null}
    {questionView === "ativas" ? <><div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(260px,340px)_minmax(0,1fr)]"><aside className="grid content-start gap-3"><article className="commercial-card"><div className="flex items-center justify-between gap-2"><h3 className="font-black">Estrutura da lei</h3>{structureId ? <button type="button" className="admin-link-button" onClick={() => setStructureId(null)}>Limpar</button> : null}</div><StructureFilter nodes={nodes} selected={structureId} onSelect={(id) => { setStructureId(id); setPage(1); }} reviewed={reviewedStructures} lawReviewed={lawReviewed} reviewSaving={reviewSaving} onToggleReview={(node) => void toggleStructureReview(node)} /></article><details><summary className="admin-button secondary cursor-pointer">Gerenciar estruturas</summary><div className="mt-3"><LawStructureAdmin lawSlug={law.slug} nodes={nodes} onReload={reloadStructure} onSelectNode={(node) => { setStructureId(node.id); setPage(1); }} selectNodeLabel="Filtrar questões" /></div></details></aside>
      <section className="grid min-w-0 content-start gap-3" aria-live="polite" aria-busy={loading}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-black">Questões encontradas</h3><div className="flex flex-wrap items-center justify-end gap-2"><span className="text-sm text-slate-600">{total} item(ns){selectedQuestionIds.length ? ` · ${selectedQuestionIds.length} selecionada(s)` : ""}</span><button type="button" className="admin-button secondary" disabled={loading || !results.length} onClick={toggleAllVisibleQuestions}>{results.length > 0 && results.every((question) => selectedQuestionIds.includes(question.id)) ? "Desmarcar todas desta página" : "Selecionar todas desta página"}</button></div></div>{loading ? <p className="commercial-card commercial-loading">Pesquisando…</p> : results.map((question) => <div key={question.id} className="relative"><label className="absolute right-3 top-3 z-10 flex items-center gap-2 rounded bg-white/90 px-2 py-1 text-xs font-bold text-slate-700 shadow-sm"><input type="checkbox" checked={selectedQuestionIds.includes(question.id)} onChange={() => toggleQuestion(question.id)} />Selecionar</label><button type="button" onClick={() => void editQuestion(question.id)} className="commercial-card grid w-full gap-2 pr-28 text-left transition hover:border-blue-300 hover:shadow-sm"><div className="flex flex-wrap items-center gap-2"><strong className="text-blue-800">#{question.ordem}</strong><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${question.resposta === "Certo" ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}`}>{question.resposta}</span>{question.artigo ? <span className="text-sm font-bold text-slate-700">{question.artigo}</span> : null}</div><p className="line-clamp-3 text-sm text-slate-800"><HighlightedText text={question.pergunta_trecho || "Questão sem trecho disponível"} query={debouncedQuery} /></p><div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500">{question.assunto ? <span>Assunto: {question.assunto}</span> : null}<span>Estrutura: {structurePath(question.structure_id) || "Sem estrutura"}</span></div></button></div>)}{!loading && !results.length ? <article className="commercial-card law-center-empty"><h3>Nenhuma questão encontrada</h3><p>Ajuste a busca ou os filtros selecionados.</p><div className="flex flex-wrap gap-2"><button type="button" className="admin-button primary" onClick={() => newQuestion()}>Cadastrar questão</button><Link className="admin-button secondary" href={`/admin/leis/${encodeURIComponent(law.slug)}/anki`}>Abrir Anki</Link></div></article> : null}</section>
    </div>
    {pages > 1 ? <nav className="flex items-center justify-center gap-3" aria-label="Paginação das questões"><button type="button" className="admin-button secondary" disabled={loading || page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Anterior</button><span className="text-sm">Página {page} de {pages}</span><button type="button" className="admin-button secondary" disabled={loading || page >= pages} onClick={() => setPage((value) => value + 1)}>Próxima</button></nav> : null}</> : null}
    {editorOpen ? <div className="fixed inset-0 z-50 bg-slate-950/45" role="presentation"><div ref={titleRef} tabIndex={-1} className="absolute inset-0 overflow-y-auto bg-slate-50 p-3 outline-none xl:left-auto xl:w-[min(94vw,1120px)] xl:p-5" role="dialog" aria-modal="true" aria-labelledby="admin-question-editor-title"><div className="mb-3 flex justify-end"><button type="button" className="admin-button secondary" disabled={saving} onClick={() => returnHref ? window.location.assign(returnHref) : setEditorOpen(false)}>Fechar</button></div><AdminQuestionEditor lawName={law.titulo} nodes={nodes} value={form} original={original} editing={Boolean(editingId)} saving={saving} error={editorError} onChange={setForm} onSubmit={(event) => void save(event)} onCancel={() => returnHref ? window.location.assign(returnHref) : setEditorOpen(false)} onPrevious={previousId ? () => navigateToQuestion(previousId) : undefined} onNext={nextId ? () => navigateToQuestion(nextId) : undefined} onDuplicate={duplicateQuestion} onMove={() => { setMoveDestination(form.structure_id); setMoveOpen(true); }} onDelete={() => void askDeleteQuestion()} showPreview /></div></div> : null}
    {deletionSummary ? <DeletionConfirmation summary={deletionSummary} confirmation={deleteConfirmation} saving={saving} targetLabel="questão" onConfirmation={setDeleteConfirmation} onCancel={() => setDeletionSummary(null)} onConfirm={() => void deleteQuestion()} /> : null}
    {bulkOpen ? <BulkDeletionDialog scope={bulkScope} selectedStructure={structureId !== null} summary={bulkSummary} confirmation={bulkConfirmation} saving={saving} onScope={setBulkScope} onConfirmText={setBulkConfirmation} onPreview={() => void askBulkDelete()} onCancel={() => { setBulkOpen(false); setBulkSummary(null); }} onDelete={() => void deleteBulkQuestions()} /> : null}
    {bulkEditOpen ? <BulkQuestionEditDialog scope={bulkEditScope} field={bulkEditField} value={bulkEditValue} nodes={nodes} structurePath={structurePath} selectedCount={selectedQuestionIds.length} preview={bulkEditPreview} saving={saving} onScope={(scope) => { setBulkEditScope(scope); setBulkEditPreview(null); }} onField={(field) => { setBulkEditField(field); setBulkEditValue(field === "resposta" ? "Certo" : field === "total_artigos" || field === "structure_id" ? null : ""); setBulkEditPreview(null); }} onValue={(value) => { setBulkEditValue(value); setBulkEditPreview(null); }} onPreview={() => void previewBulkEdit()} onCancel={() => { setBulkEditOpen(false); setBulkEditPreview(null); }} onApply={() => void applyBulkEdit()} /> : null}
    {moveOpen ? <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="move-question-title"><h2 id="move-question-title">Mover para outra estrutura</h2><label>Destino<select value={moveDestination ?? ""} onChange={(event) => setMoveDestination(event.target.value ? Number(event.target.value) : null)}><option value="">Sem estrutura</option>{nodes.map((node) => <option key={node.id} value={node.id}>{structurePath(node.id)}</option>)}</select></label><div className="admin-modal-actions"><button className="admin-button secondary" type="button" onClick={() => setMoveOpen(false)}>Cancelar</button><button className="admin-button primary" type="button" disabled={saving} onClick={() => void moveQuestion()}>Mover</button></div></section></div> : null}
    {conferenceOpen && (structureId || !nodes.length) ? <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-3 sm:p-6"><main className="mx-auto max-w-5xl"><AdminQuestionConference law={law} nodes={nodes} structureId={structureId} structureName={structureId ? structurePath(structureId) : "Lei completa"} onClose={() => setConferenceOpen(false)} onChanged={() => setRefresh((value) => value + 1)} /></main></div> : null}
  </section>;
}

function StructureFilter({ nodes, selected, onSelect, reviewed, lawReviewed, reviewSaving, onToggleReview, parentId = null, depth = 0 }: { nodes: AdminQuestionStructureNode[]; selected: number | null; onSelect: (id: number) => void; reviewed: Set<number>; lawReviewed: boolean; reviewSaving: number | "law" | null; onToggleReview: (node: AdminQuestionStructureNode | null) => void; parentId?: number | null; depth?: number }) { const children = nodes.filter((node) => node.parent_id === parentId).sort((a, b) => a.ordem - b.ordem || a.nome.localeCompare(b.nome, "pt-BR")); if (!children.length && depth === 0) return <div className="mt-3 flex items-center justify-between gap-2 rounded-lg bg-slate-50 px-2 py-1.5"><span className="text-sm font-bold text-slate-700">Lei completa</span><button type="button" className={`shrink-0 rounded px-1.5 py-1 text-xs ${lawReviewed ? "font-black text-green-700" : "text-slate-400 hover:text-slate-700"}`} aria-pressed={lawReviewed} aria-label={lawReviewed ? "Desmarcar lei completa como conferida" : "Marcar lei completa como conferida"} title={lawReviewed ? "Desmarcar como conferido" : "Marcar como conferido"} disabled={reviewSaving === "law"} onClick={(event) => { event.stopPropagation(); onToggleReview(null); }}>{lawReviewed ? "✓ Conferido" : "Marcar como conferido"}</button></div>; return <ul className={depth ? "mt-1" : "mt-3"}>{children.map((node) => <li key={node.id}><div className="flex items-center gap-1" style={{ paddingLeft: depth * 14 }}><button type="button" aria-pressed={selected === node.id} className={`min-w-0 flex-1 rounded-lg px-2 py-1.5 text-left text-sm ${selected === node.id ? "bg-blue-100 font-black text-blue-800" : "hover:bg-slate-100"}`} onClick={() => onSelect(node.id)}>{node.nome}</button><button type="button" className={`shrink-0 rounded px-1.5 py-1 text-xs ${reviewed.has(node.id) ? "font-black text-green-700" : "text-slate-400 hover:text-slate-700"}`} aria-pressed={reviewed.has(node.id)} aria-label={reviewed.has(node.id) ? `Desmarcar ${node.nome} como conferido` : `Marcar ${node.nome} como conferido`} title={reviewed.has(node.id) ? "Desmarcar como conferido" : "Marcar como conferido"} disabled={reviewSaving === node.id} onClick={(event) => { event.stopPropagation(); onToggleReview(node); }}>{reviewed.has(node.id) ? "✓ Conferido" : "Marcar como conferido"}</button></div><StructureFilter nodes={nodes} selected={selected} onSelect={onSelect} reviewed={reviewed} lawReviewed={lawReviewed} reviewSaving={reviewSaving} onToggleReview={onToggleReview} parentId={node.id} depth={depth + 1} /></li>)}</ul>; }

function DeletionConfirmation({ summary, confirmation, saving, targetLabel, onConfirmation, onCancel, onConfirm }: { summary: DeletionSummary; confirmation: string; saving: boolean; targetLabel: string; onConfirmation: (value: string) => void; onCancel: () => void; onConfirm: () => void }) {
  return <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="delete-question-title"><h2 id="delete-question-title">Excluir {targetLabel} definitivamente?</h2><p>Serão removidas {summary.questions_count} questão(ões), {summary.campaigns_count} campanha(s), {summary.answers_count} resposta(s) e {summary.progresses_count} progresso(s) ativo(s).</p>{summary.campaigns.length ? <div><h3 className="font-bold">Campanhas afetadas e titulares</h3><ul>{summary.campaigns.map((campaign) => <li key={campaign.id}>{campaign.nome || "Aluno sem nome"} · {campaign.email || campaign.aluno_id}{campaign.is_requesting_admin ? " · conta administrativa" : " · outro aluno"}</li>)}</ul></div> : <p>Nenhuma campanha será removida.</p>}<p className="admin-alert error">A exclusão é definitiva e não possui lixeira ou restauração.</p>{summary.requires_confirmation ? <label>Para confirmar campanhas de outros alunos, digite <strong>EXCLUIR</strong><input autoFocus value={confirmation} onChange={(event) => onConfirmation(event.target.value)} /></label> : null}<div className="admin-modal-actions"><button className="admin-button secondary" type="button" disabled={saving} onClick={onCancel}>Cancelar</button><button className="admin-button danger" type="button" disabled={saving || (summary.requires_confirmation && confirmation !== "EXCLUIR")} onClick={onConfirm}>{saving ? "Excluindo…" : `Excluir ${targetLabel} e campanhas afetadas`}</button></div></section></div>;
}

function BulkDeletionDialog({ scope, selectedStructure, summary, confirmation, saving, onScope, onConfirmText, onPreview, onCancel, onDelete }: { scope: BulkScope; selectedStructure: boolean; summary: DeletionSummary | null; confirmation: string; saving: boolean; onScope: (scope: BulkScope) => void; onConfirmText: (value: string) => void; onPreview: () => void; onCancel: () => void; onDelete: () => void }) {
  return <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="bulk-delete-questions-title"><h2 id="bulk-delete-questions-title">Excluir questões definitivamente</h2><p>As estruturas serão preservadas. A prévia calcula campanhas inteiras, respostas e progressos que precisam ser removidos.</p><label>Escopo<select value={scope} disabled={saving || Boolean(summary)} onChange={(event) => onScope(event.target.value as BulkScope)}><option value="structure" disabled={!selectedStructure}>Da estrutura selecionada e descendentes{selectedStructure ? "" : " (selecione uma estrutura antes)"}</option><option value="results">Do resultado atual dos filtros</option><option value="all">Todas as questões desta lei</option></select></label>{!summary ? <div className="admin-modal-actions"><button type="button" className="admin-button secondary" disabled={saving} onClick={onCancel}>Cancelar</button><button type="button" className="admin-button danger" disabled={saving || (scope === "structure" && !selectedStructure)} onClick={onPreview}>{saving ? "Calculando…" : "Ver prévia"}</button></div> : <><p>Serão removidas <strong>{summary.questions_count} questão(ões)</strong>, <strong>{summary.campaigns_count} campanha(s)</strong>, {summary.answers_count} resposta(s) e {summary.progresses_count} progresso(s). Nenhuma estrutura será excluída.</p>{summary.campaigns.length ? <details open><summary>Campanhas e titulares afetados</summary><ul>{summary.campaigns.map((campaign) => <li key={campaign.id}>{campaign.nome || "Aluno sem nome"} · {campaign.email || campaign.aluno_id}{campaign.is_requesting_admin ? " · conta administrativa" : " · outro aluno"}</li>)}</ul></details> : <p>Nenhuma campanha será removida.</p>}<label>Digite <strong>EXCLUIR</strong> para confirmar.<input autoFocus value={confirmation} disabled={saving} onChange={(event) => onConfirmText(event.target.value)} /></label><p className="admin-alert error">A exclusão em massa é definitiva e será executada em uma única transação.</p><div className="admin-modal-actions"><button type="button" className="admin-button secondary" disabled={saving} onClick={onCancel}>Cancelar</button><button type="button" className="admin-button danger" disabled={saving || confirmation !== "EXCLUIR"} onClick={onDelete}>{saving ? "Excluindo…" : "Excluir questões e campanhas afetadas"}</button></div></>}</section></div>;
}

function BulkQuestionEditDialog({ scope, field, value, nodes, structurePath, selectedCount, preview, saving, onScope, onField, onValue, onPreview, onCancel, onApply }: { scope: BulkQuestionEditScope; field: QuestionEditableField; value: unknown; nodes: AdminQuestionStructureNode[]; structurePath: (id: number | null) => string; selectedCount: number; preview: BulkEditPreview | null; saving: boolean; onScope: (scope: BulkQuestionEditScope) => void; onField: (field: QuestionEditableField) => void; onValue: (value: unknown) => void; onPreview: () => void; onCancel: () => void; onApply: () => void }) {
  const nullable = !["pergunta", "resposta", "ordem"].includes(field);
  const valueControl = field === "resposta" ? <select value={String(value ?? "Certo")} disabled={Boolean(preview) || saving} onChange={(event) => onValue(event.target.value)}>{QUESTION_ANSWERS.map((answer) => <option key={answer}>{answer}</option>)}</select>
    : field === "structure_id" ? <select value={value == null ? "" : String(value)} disabled={Boolean(preview) || saving} onChange={(event) => onValue(event.target.value ? Number(event.target.value) : null)}><option value="">Sem estrutura</option>{nodes.map((node) => <option key={node.id} value={node.id}>{structurePath(node.id)}</option>)}</select>
    : field === "total_artigos" ? <input type="number" min="0" value={value == null ? "" : String(value)} disabled={Boolean(preview) || saving} onChange={(event) => onValue(event.target.value === "" ? null : Number(event.target.value))} />
    : field === "pergunta" || field === "justificativa" || field === "legislacao" ? <QuestionRichEditor label="Novo valor" required={field === "pergunta"} disabled={Boolean(preview) || saving} value={String(value ?? "")} onChange={onValue} />
    : <input value={String(value ?? "")} disabled={Boolean(preview) || saving} onChange={(event) => onValue(event.target.value)} />;
  return <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal max-w-3xl" role="dialog" aria-modal="true" aria-labelledby="bulk-edit-questions-title">
    <header className="border-b border-slate-200 pb-4"><p className="law-center-kicker">Manutenção em lote</p><h2 id="bulk-edit-questions-title" className="mt-1">Editar questões</h2><p className="mt-2 text-sm text-slate-600">Altere um único campo por operação. UUIDs, campanhas e progresso são preservados.</p></header>
    <div className="grid gap-4 py-5 sm:grid-cols-2">
      <label className="grid gap-2 font-bold">Abrangência<select value={scope} disabled={Boolean(preview) || saving} onChange={(event) => onScope(event.target.value as BulkQuestionEditScope)}><option value="selected">Questões selecionadas{selectedCount ? ` (${selectedCount})` : ""}</option><option value="results">Resultado atual dos filtros</option><option value="all">Todas as questões desta lei</option></select></label>
      <label className="grid gap-2 font-bold">Campo<select value={field} disabled={Boolean(preview) || saving} onChange={(event) => onField(event.target.value as QuestionEditableField)}>{Object.entries(QUESTION_BULK_FIELD_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
    </div>
    <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><label className="grid gap-2 font-bold">Novo valor{valueControl}</label>{nullable ? <p className="mt-2 text-sm text-slate-600">Deixe vazio para limpar este campo.</p> : <p className="mt-2 text-sm text-slate-600">Este campo é obrigatório e não pode ficar vazio.</p>}</section>
    {!preview ? <div className="admin-modal-actions mt-5 border-t border-slate-200 pt-4"><button type="button" className="admin-button secondary" disabled={saving} onClick={onCancel}>Cancelar</button><button type="button" className="admin-button primary" disabled={saving || (scope === "selected" && !selectedCount)} onClick={onPreview}>{saving ? "Calculando…" : "Ver prévia"}</button></div> : <><section className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4"><h3 className="font-black">Prévia da alteração</h3><p className="mt-1 text-sm">Lei atual · {scope === "selected" ? "questões selecionadas" : scope === "results" ? "resultado atual dos filtros" : "todas as questões da lei"} · <strong>{QUESTION_BULK_FIELD_LABELS[field]}</strong> → <strong>{questionFieldDisplayValue(preview.value)}</strong></p><p className="mt-2 text-sm"><strong>{preview.changed_count}</strong> questão(ões) serão alteradas; {preview.unchanged_count} já possuem esse valor.</p>{preview.sample.length ? <details open className="mt-3"><summary className="cursor-pointer font-bold">Exemplos de alteração</summary><ul className="mt-2 list-disc pl-5 text-sm">{preview.sample.map((item) => <li key={item.id}><code>{item.id.slice(0, 8)}</code>: {questionFieldDisplayValue(item.before)} → {questionFieldDisplayValue(item.after)}</li>)}</ul></details> : null}</section><p className="mt-4 text-sm text-slate-600">A confirmação verifica novamente os valores anteriores. Se outra edição ocorrer, será exigida uma nova prévia.</p><div className="admin-modal-actions mt-5 border-t border-slate-200 pt-4"><button type="button" className="admin-button secondary" disabled={saving} onClick={onCancel}>Cancelar</button><button type="button" className="admin-button primary" disabled={saving || !preview.changed_count} onClick={onApply}>{saving ? "Aplicando…" : `Confirmar edição de ${preview.changed_count} questão(ões)`}</button></div></>}
  </section></div>;
}
