"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Support = { slug: string; ordem: string };
type Overview = { questions: Array<{ id: string; assunto: string | null; supports: Support[]; combination: { justification: string; decidedAt: string; valid: boolean } | null }>; impactedSupportQuestions: Array<{ id: string; slug: string; ordem: string; assunto: string | null }>; updates: Array<{ id: string; status: string; observacao_interna: string | null; observacao_publica: string | null; marcado_em: string; concluido_em: string | null; steps: Array<{ step: string; completedAt: string | null }> }> };
const names: Record<string, string> = { legislacao: "Legislação conferida", questoes: "Questões principais e de apoio revisadas", mapeamento: "Mapeamento revisado", materiais: "Materiais dos alunos atualizados" };
async function request(method: "GET" | "POST", body?: Record<string, unknown>) { const url = method === "GET" ? `/api/admin/artigos/atualizacoes?slug=${encodeURIComponent(String(body?.slug ?? ""))}&ordem=${encodeURIComponent(String(body?.ordem ?? ""))}` : "/api/admin/artigos/atualizacoes"; const response = await fetch(url, { method, headers: body && method === "POST" ? { "Content-Type": "application/json" } : undefined, body: method === "POST" ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível concluir a operação."); return data; }
function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }

export function ArticleLegislativeUpdates({ slug, ordem }: { slug: string; ordem: string }) {
  const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [observation, setObservation] = useState(""); const [questionId, setQuestionId] = useState(""); const [supports, setSupports] = useState(""); const [justification, setJustification] = useState(""); const [publicNote, setPublicNote] = useState("");
  const load = async () => { try { setError(""); setData(await request("GET", { slug, ordem })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar o controle de atualização."); } };
  useEffect(() => { void load(); }, [slug, ordem]);
  const act = async (body: Record<string, unknown>) => { try { setBusy(true); setError(""); await request("POST", body); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar."); } finally { setBusy(false); } };
  const parseSupports = () => supports.split(/[,\n]+/).map((item) => { const [supportSlug, supportOrder] = item.trim().split(/[:\s]+/, 2); return { slug: supportSlug, ordem: supportOrder }; });
  const open = data?.updates.find((item) => item.status !== "concluida") ?? null;
  return <section className="article-legislative-updates commercial-card"><header><div><h2>Atualização legislativa e dispositivos de apoio</h2><p>O dispositivo principal permanece em Assunto e Ordem. Vínculos de apoio e revisões são registrados separadamente.</p></div></header>{error ? <p className="admin-alert error" role="alert">{error}</p> : null}
    <section className="grid gap-3"><h3>Combinações intencionais por questão</h3>{data?.questions.map((question) => <article className="rounded-lg border border-slate-200 p-3" key={question.id}><strong>{question.assunto || "Questão sem assunto"}</strong>{question.supports.length ? <p className="text-sm">Apoio: {question.supports.map((item) => `${item.slug.toUpperCase()} · ${item.ordem}`).join("; ")}</p> : <p className="text-sm text-slate-600">Sem dispositivo de apoio registrado.</p>}{question.combination ? <p className={question.combination.valid ? "text-sm text-emerald-800" : "text-sm text-amber-800"}><strong>{question.combination.valid ? "Combinação intencional validada:" : "Combinação precisa ser revista:"}</strong> {question.combination.justification}</p> : null}</article>)}</section>
    <details className="mt-4"><summary className="admin-button secondary">Justificar combinação</summary><div className="mt-3 grid gap-3"><label>Questão<select value={questionId} onChange={(event) => setQuestionId(event.target.value)}><option value="">Selecione</option>{data?.questions.map((item) => <option key={item.id} value={item.id}>{item.assunto || item.id}</option>)}</select></label><label>Dispositivos de apoio<small>Um por linha ou separado por vírgula: <code>slug:ordem</code></small><textarea value={supports} onChange={(event) => setSupports(event.target.value)} placeholder={`${slug.toLowerCase()}:0002.0.00.0.00.0`} /></label><label>Justificativa editorial<textarea value={justification} onChange={(event) => setJustification(event.target.value)} /></label><button type="button" className="admin-button primary" disabled={busy || !questionId || !supports.trim() || !justification.trim()} onClick={() => void act({ action: "salvar_combinacao", slug, ordem, question_id: questionId, supports: parseSupports(), justification })}>Registrar combinação</button></div></details>
    <section className="mt-5 grid gap-3"><h3>Revisão por atualização legislativa</h3>{data?.impactedSupportQuestions.length ? <div className="admin-alert"><strong>{data.impactedSupportQuestions.length} questão(ões) impactada(s) por apoio:</strong><ul>{data.impactedSupportQuestions.map((item) => <li key={item.id}><Link href={`/admin/leis/${encodeURIComponent(item.slug)}/questoes?question_id=${encodeURIComponent(item.id)}`}>{item.assunto || `${item.slug.toUpperCase()} · ${item.ordem}`}</Link></li>)}</ul><span>A revisão do conteúdo continua manual.</span></div> : null}{!open ? <div className="grid gap-2"><p>Não há atualização em aberto para este dispositivo.</p><label>Observação interna opcional<textarea value={observation} onChange={(event) => setObservation(event.target.value)} /></label><button type="button" className="admin-button primary justify-self-start" disabled={busy} onClick={() => void act({ action: "marcar_atualizacao", slug, ordem, observation })}>Marcar para atualização legislativa</button></div> : <article className="rounded-lg border border-amber-200 bg-amber-50 p-4"><p><strong>{open.status === "pendente" ? "Pendente" : "Em revisão"}</strong> desde {formatDate(open.marcado_em)}.</p>{open.steps.map((step) => <label className="mt-2 flex gap-2" key={step.step}><input type="checkbox" disabled={busy} checked={Boolean(step.completedAt)} onChange={(event) => void act({ action: "etapa_atualizacao", update_id: open.id, step: step.step, completed: event.target.checked })}/><span>{names[step.step] ?? step.step}{step.completedAt ? ` · concluída em ${formatDate(step.completedAt)}` : ""}</span></label>)}<label className="mt-3 grid gap-1">Observação pública para alunos<textarea value={publicNote} onChange={(event) => setPublicNote(event.target.value)} placeholder="Material revisado e atualizado." /></label><button type="button" className="admin-button primary mt-2 justify-self-start" disabled={busy || !open.steps.every((step) => step.completedAt)} onClick={() => void act({ action: "concluir_atualizacao", update_id: open.id, public_note: publicNote })}>Concluir e disponibilizar atualização</button></article>}{data?.updates.filter((item) => item.status === "concluida").map((item) => <p className="text-sm text-emerald-800" key={item.id}>Atualização concluída em {item.concluido_em ? formatDate(item.concluido_em) : "—"}{item.observacao_publica ? ` · ${item.observacao_publica}` : ""}</p>)}</section>
  </section>;
}
