"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { AdminQuestionForm } from "@/components/admin/admin-question-editor";

type Source = { id: number | null; titulo: string; url_externa: string; google_document_id: string; direct: boolean };
type Draft = { key: string; ordem: string | null; assunto: string; tipo: "caput" | "paragrafo"; texto_html: string; texto_plano: string; caminho_estrutural: string[]; ambiguous: boolean; warnings: string[] };
type Shadow = Draft & { id: string; decision: "nao_cabe_questao" | "revogado" | null; status: "coberta" | "sombra" | "dispensada" | "conflito" | "ambigua"; absent_from_latest: boolean; question_ids: string[]; conflict_question_ids: string[] };
type Dashboard = { units: Shadow[]; last_analysis: { id: string; created_at: string; complete: boolean; partial: boolean; warnings: string[] } | null };
const labels = { coberta: "Cobertas", sombra: "Artigos Sombra", dispensada: "Dispensadas", conflito: "Com conflito", ambigua: "Ambíguas" } as const;

async function json(response: Response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Não foi possível concluir a análise."); return body; }
async function post(body: Record<string, unknown>) { return fetch("/api/admin/questoes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }).then(json); }

export function LawQuestionShadows({ lawSlug, structurePath = [], onCreate }: { lawSlug: string; structurePath?: string[]; onCreate: (data: AdminQuestionForm, notice: string) => void }) {
  const [sources, setSources] = useState<Source[]>([]); const [selectedSource, setSelectedSource] = useState<number | "">("");
  const [directSourceUrl, setDirectSourceUrl] = useState("");
  const [pastedText, setPastedText] = useState(""); const [pasteOpen, setPasteOpen] = useState(false);
  const [showHidden, setShowHidden] = useState(false);
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [preview, setPreview] = useState<{ analysis_id: string; analyzed_at: string; source: Source; units: Draft[]; warnings: string[]; complete: boolean; changes: { novas: string[]; alteradas: string[]; ausentes: string[] } } | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const [sourceData, shadowData] = await Promise.all([fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(lawSlug)}&mode=shadow-sources`, { cache: "no-store" }).then(json), fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(lawSlug)}&mode=shadows`, { cache: "no-store" }).then(json)]); setSources(sourceData.sources); setSelectedSource(sourceData.selected_material_id ?? (sourceData.sources.length === 1 ? sourceData.sources[0].id : "")); setDirectSourceUrl(sourceData.selected_material_id ? "" : (sourceData.selected_source_url ?? "")); setDashboard(shadowData); }, [lawSlug]);
  useEffect(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "Não foi possível carregar Artigos Sombra.")); }, [load]);
  const totals = useMemo(() => Object.fromEntries(Object.keys(labels).map((status) => [status, dashboard?.units.filter((unit) => unit.status === status).length ?? 0])) as Record<keyof typeof labels, number>, [dashboard]);
  const visibleUnits = useMemo(() => (dashboard?.units ?? []).filter((unit) => {
    const withinStructure = !structurePath.length || structurePath.every((name, index) => unit.caminho_estrutural[index] === name);
    const hiddenByDefault = unit.status === "coberta" || Boolean(unit.decision);
    return withinStructure && (showHidden || !hiddenByDefault);
  }), [dashboard, showHidden, structurePath]);
  const hiddenCount = dashboard?.units.filter((unit) => unit.status === "coberta" || Boolean(unit.decision)).length ?? 0;
  async function analyze() { setBusy(true); setError(""); setNotice(""); try { setPreview(await post({ action: "analisar_sombras_docs", law_slug: lawSlug, material_id: directSourceUrl.trim() ? null : selectedSource || null, source_url: directSourceUrl.trim() || null })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível ler o Google Docs."); } finally { setBusy(false); } }
  async function analyzePastedText() { setBusy(true); setError(""); setNotice(""); try { const next = await post({ action: "analisar_sombras_texto", law_slug: lawSlug, texto_legal: pastedText }); setPreview(next); setPasteOpen(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível analisar o texto colado."); } finally { setBusy(false); } }
  function change(index: number, key: keyof Draft, value: string) { setPreview((current) => current ? { ...current, units: current.units.map((unit, itemIndex) => itemIndex === index ? { ...unit, [key]: value === "" && key === "ordem" ? null : value } : unit) } : current); }
  async function confirm() { if (!preview) return; setBusy(true); setError(""); try { await post({ action: "confirmar_sombras_docs", law_slug: lawSlug, analysis_id: preview.analysis_id, units: preview.units }); setPreview(null); setNotice("Inventário confirmado. Cobertura calculada sem criar ou alterar questões."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível confirmar o inventário."); } finally { setBusy(false); } }
  async function decide(unit: Shadow, decision: Shadow["decision"]) { setBusy(true); setError(""); try { const next = await post({ action: "decidir_sombra", law_slug: lawSlug, unit_id: unit.id, decision }); setDashboard(next); setNotice(decision ? "Decisão salva; ela pode ser desfeita quando necessário." : "Decisão removida."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar a decisão."); } finally { setBusy(false); } }
  async function createQuestion(unit: Shadow) { setBusy(true); setError(""); try { const draft = await fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(lawSlug)}&mode=shadow-draft&unit_id=${encodeURIComponent(unit.id)}`, { cache: "no-store" }).then(json); onCreate(draft.data as AdminQuestionForm, draft.structure_warning ? `Rascunho criado. ${draft.structure_warning}` : "Rascunho criado a partir do Artigo Sombra; complete enunciado, gabarito e justificativa."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível preparar a questão."); } finally { setBusy(false); } }
  return <section className="commercial-card grid gap-4" aria-labelledby="law-shadow-title"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="law-center-kicker">Artigo Sombra</p><h3 id="law-shadow-title">Cobertura de questões</h3><p className="text-sm text-slate-600">Cole a lei inteira ou o trecho em conferência. Cobertura indica vínculo de questão, não exaustividade de cobrança.</p></div><button type="button" className="admin-button primary" disabled={busy} onClick={() => setPasteOpen(true)}>Analisar texto da lei</button></header>
    <details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer font-bold">Analisar pelo Google Docs (opcional)</summary><div className="mt-3 grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Colar link público do Google Docs<input type="url" inputMode="url" value={directSourceUrl} placeholder="https://docs.google.com/document/d/..." onChange={(event) => setDirectSourceUrl(event.target.value)} disabled={busy} /><span className="text-xs font-normal text-slate-600">O documento precisa estar como visualizador para qualquer pessoa com o link.</span></label><label className="grid gap-1 text-sm font-bold">Ou usar Google Docs cadastrado<select value={selectedSource} onChange={(event) => { setSelectedSource(event.target.value ? Number(event.target.value) : ""); if (event.target.value) setDirectSourceUrl(""); }} disabled={busy || sources.length <= 1}><option value="">{sources.length ? "Selecione o documento" : "Nenhum Google Docs cadastrado"}</option>{sources.map((source) => <option value={source.id ?? ""} key={source.id ?? source.google_document_id}>{source.titulo}</option>)}</select><span className="text-xs font-normal text-slate-600">Usa a conta de serviço configurada; indicado para documento privado.</span></label></div><div><button type="button" className="admin-button secondary" disabled={busy} onClick={() => void analyze()}>{busy ? "Analisando…" : "Analisar cobertura pelo Docs"}</button><p className="mt-2 text-xs text-slate-600">O sistema só aceita URLs `docs.google.com/document/d/...` e confirma a exportação HTML antes de analisar.</p></div></div></details>
    {notice ? <p className="admin-alert success" role="status">{notice}</p> : null}{error ? <p className="admin-alert error" role="alert">{error}</p> : null}
    {dashboard ? <><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-5">{(Object.keys(labels) as Array<keyof typeof labels>).map((status) => <div className="rounded-lg border border-slate-200 bg-slate-50 p-3" key={status}><strong>{totals[status]}</strong><br /><span>{labels[status]}</span></div>)}</div>{dashboard.last_analysis ? <p className="text-sm text-slate-600">Última análise: {new Date(dashboard.last_analysis.created_at).toLocaleString("pt-BR")}{dashboard.last_analysis.partial ? " · trecho colado: apenas esta parte foi avaliada" : dashboard.last_analysis.complete ? "" : " · leitura incompleta"}.</p> : <p className="text-sm text-slate-600">Ainda não há inventário confirmado para esta lei.</p>}<div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-bold">{structurePath.length ? `Estrutura: ${structurePath.join(" › ")}` : "Toda a lei"} · {visibleUnits.length} item(ns)</p>{hiddenCount ? <button type="button" className="admin-button secondary" onClick={() => setShowHidden((value) => !value)}>{showHidden ? "Ocultar itens concluídos" : `Mostrar itens concluídos (${hiddenCount})`}</button> : null}</div><div className="grid gap-2">{visibleUnits.map((unit) => <article className="rounded-xl border border-slate-200 px-4 py-3" key={unit.id}><div className="flex flex-wrap items-center justify-between gap-2"><strong>{unit.assunto}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{labels[unit.status]}</span></div>{unit.ordem ? <p className="mt-1 text-xs text-slate-500">{unit.ordem}</p> : <p className="mt-1 text-xs text-amber-700">Sem Ordem confiável</p>}{unit.absent_from_latest ? <p className="mt-2 text-xs text-amber-700">Preservado: não localizado na última análise.</p> : null}{unit.status === "conflito" ? <p className="mt-2 text-xs text-amber-700">Conflito de vínculo; não comprova cobertura.</p> : null}<div className="mt-3 flex flex-wrap gap-2">{unit.status === "sombra" ? <button type="button" className="admin-button primary" disabled={busy} onClick={() => void createQuestion(unit)}>Criar questão</button> : null}<button type="button" className="admin-button secondary" disabled={busy} onClick={() => void decide(unit, unit.decision === "nao_cabe_questao" ? null : "nao_cabe_questao")}>{unit.decision === "nao_cabe_questao" ? "Desfazer não cabe" : "Não cabe questão"}</button><button type="button" className="admin-button secondary" disabled={busy} onClick={() => void decide(unit, unit.decision === "revogado" ? null : "revogado")}>{unit.decision === "revogado" ? "Desfazer revogado" : "Revogado"}</button></div></article>)}{!visibleUnits.length ? <p className="rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-600">Nenhum Artigo Sombra nesta visualização.</p> : null}</div></> : null}
    {pasteOpen ? <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal max-w-3xl" role="dialog" aria-modal="true" aria-labelledby="shadow-paste-title"><h2 id="shadow-paste-title">Analisar texto da lei</h2><p>Cole a lei inteira ou apenas o capítulo atual. Quando for um trecho, somente as unidades encontradas nele serão atualizadas: o restante da lei não será considerado ausente.</p><label className="mt-4 grid gap-1 text-sm font-bold">Texto legal<textarea className="min-h-80" value={pastedText} onChange={(event) => setPastedText(event.target.value)} placeholder={"Art. 1º ...\n\n§ 1º ..."} disabled={busy} /></label><div className="admin-modal-actions mt-4"><button type="button" className="admin-button secondary" disabled={busy} onClick={() => setPasteOpen(false)}>Cancelar</button><button type="button" className="admin-button primary" disabled={busy || !pastedText.trim()} onClick={() => void analyzePastedText()}>{busy ? "Analisando…" : "Gerar prévia"}</button></div></section></div> : null}
    {preview ? <div className="admin-modal-backdrop" role="presentation"><section className="admin-modal max-w-5xl" role="dialog" aria-modal="true" aria-labelledby="shadow-preview-title"><h2 id="shadow-preview-title">Prévia do Artigo Sombra</h2><p>Revise as unidades antes de confirmar. Incisos e alíneas permanecem no caput/parágrafo correspondente; remissões e tabelas não criam unidades próprias.</p><p className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{preview.changes.novas.length}</strong> nova(s) · <strong>{preview.changes.alteradas.length}</strong> com texto alterado · <strong>{preview.changes.ausentes.length}</strong> ausente(s) do Docs. Unidades ausentes serão preservadas, sem decisão automática.</p>{preview.warnings.length ? <ul className="admin-alert"><li>{preview.warnings.join(" ")}</li></ul> : null}<div className="max-h-[58vh] overflow-auto grid gap-3">{preview.units.map((unit, index) => <article className="rounded-lg border border-slate-200 p-3" key={`${unit.key}-${index}`}><div className="grid gap-2 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Referência<input value={unit.assunto} onChange={(event) => change(index, "assunto", event.target.value)} /></label><label className="grid gap-1 text-sm font-bold">Ordem<input value={unit.ordem ?? ""} placeholder="Ex.: 0001.0.00.0.00.0" onChange={(event) => change(index, "ordem", event.target.value)} /></label></div><label className="mt-2 grid gap-1 text-sm font-bold">Texto legal (HTML preservado)<textarea className="min-h-28" value={unit.texto_html} onChange={(event) => change(index, "texto_html", event.target.value)} /></label>{unit.warnings.length ? <p className="mt-2 text-sm text-amber-700">{unit.warnings.join(" ")}</p> : null}</article>)}</div><div className="admin-modal-actions mt-4"><button type="button" className="admin-button secondary" disabled={busy} onClick={() => setPreview(null)}>Cancelar</button><button type="button" className="admin-button primary" disabled={busy || !preview.complete} onClick={() => void confirm()}>{busy ? "Confirmando…" : `Confirmar inventário de ${preview.units.length} unidade(s)`}</button></div></section></div> : null}
  </section>;
}
