"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { AdminQuestionForm } from "@/components/admin/admin-question-editor";

type Shadow = { id: string; ordem: string | null; assunto: string; decision: "nao_cabe_questao" | "revogado" | null; status: "coberta" | "sombra" | "dispensada" | "conflito" | "ambigua"; caminho_estrutural: string[] };
type Dashboard = { units: Shadow[] };
const labels = { coberta: "Cobertas", sombra: "Questões Sombra", dispensada: "Dispensadas", conflito: "Com conflito", ambigua: "Ambíguas" } as const;
async function json(response: Response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Não foi possível concluir a operação."); return body; }
async function post(body: Record<string, unknown>) { return fetch("/api/admin/questoes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }).then(json); }

export function LawQuestionShadows({ lawSlug, structurePath = [], onCreate }: { lawSlug: string; structurePath?: string[]; onCreate: (data: AdminQuestionForm, notice: string) => void }) {
  const [showHidden, setShowHidden] = useState(false); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(lawSlug)}&mode=shadows`, { cache: "no-store" }); setDashboard(await json(response)); }, [lawSlug]);
  useEffect(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "Não foi possível carregar Questões Sombra.")); }, [load]);
  const totals = useMemo(() => Object.fromEntries(Object.keys(labels).map((status) => [status, dashboard?.units.filter((unit) => unit.status === status).length ?? 0])) as Record<keyof typeof labels, number>, [dashboard]);
  const visibleUnits = useMemo(() => (dashboard?.units ?? []).filter((unit) => { const withinStructure = !structurePath.length || structurePath.every((name, index) => unit.caminho_estrutural[index] === name); return withinStructure && (showHidden || (unit.status !== "coberta" && !unit.decision)); }), [dashboard, showHidden, structurePath]);
  const hiddenCount = dashboard?.units.filter((unit) => unit.status === "coberta" || Boolean(unit.decision)).length ?? 0;
  async function decide(unit: Shadow, decision: Shadow["decision"]) { setBusy(true); setError(""); try { setDashboard(await post({ action: "decidir_sombra", law_slug: lawSlug, unit_id: unit.id, decision })); setNotice(decision ? "Decisão salva; ela pode ser desfeita quando necessário." : "Decisão removida."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar a decisão."); } finally { setBusy(false); } }
  async function createQuestion(unit: Shadow) { setBusy(true); setError(""); try { const draft = await fetch(`/api/admin/questoes?law_slug=${encodeURIComponent(lawSlug)}&mode=shadow-draft&unit_id=${encodeURIComponent(unit.id)}`, { cache: "no-store" }).then(json); onCreate(draft.data as AdminQuestionForm, draft.structure_warning ? `Rascunho criado. ${draft.structure_warning}` : "Rascunho criado a partir da Questão Sombra; complete assertiva, gabarito e justificativa."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível preparar a questão."); } finally { setBusy(false); } }
  return <section className="commercial-card grid gap-4" aria-labelledby="law-shadow-title"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="law-center-kicker">Questões Sombra</p><h3 id="law-shadow-title">Contextos prontos para criar questões</h3><p className="text-sm text-slate-600">Uma Sombra guarda referência, legislação e estrutura, mas não é uma questão ativa até você criar a assertiva.</p></div><Link className="admin-button primary" href={`/admin/artigos?aba=mapeamento&lei=${encodeURIComponent(lawSlug)}`}>Abrir Mapeamento</Link></header>
    {notice ? <p className="admin-alert success" role="status">{notice}</p> : null}{error ? <p className="admin-alert error" role="alert">{error}</p> : null}
    {dashboard ? <><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-5">{(Object.keys(labels) as Array<keyof typeof labels>).map((status) => <div className="rounded-lg border border-slate-200 bg-slate-50 p-3" key={status}><strong>{totals[status]}</strong><br /><span>{labels[status]}</span></div>)}</div><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-bold">{structurePath.length ? `Estrutura: ${structurePath.join(" › ")}` : "Toda a lei"} · {visibleUnits.length} item(ns)</p>{hiddenCount ? <button type="button" className="admin-button secondary" onClick={() => setShowHidden((value) => !value)}>{showHidden ? "Ocultar itens concluídos" : `Mostrar itens concluídos (${hiddenCount})`}</button> : null}</div><div className="grid gap-2">{visibleUnits.map((unit) => <article className="rounded-xl border border-slate-200 px-4 py-3" key={unit.id}><div className="flex flex-wrap items-center justify-between gap-2"><strong>{unit.assunto}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{labels[unit.status]}</span></div>{unit.ordem ? <p className="mt-1 text-xs text-slate-500">{unit.ordem}</p> : <p className="mt-1 text-xs text-amber-700">Sem Ordem confiável</p>}{unit.status === "conflito" ? <p className="mt-2 text-xs text-amber-700">Conflito de vínculo; não comprova cobertura.</p> : null}<div className="mt-3 flex flex-wrap gap-2">{unit.status === "sombra" ? <button type="button" className="admin-button primary" disabled={busy} onClick={() => void createQuestion(unit)}>Criar questão</button> : null}<button type="button" className="admin-button secondary" disabled={busy} onClick={() => void decide(unit, unit.decision === "nao_cabe_questao" ? null : "nao_cabe_questao")}>{unit.decision === "nao_cabe_questao" ? "Desfazer não cabe" : "Não cabe questão"}</button><button type="button" className="admin-button secondary" disabled={busy} onClick={() => void decide(unit, unit.decision === "revogado" ? null : "revogado")}>{unit.decision === "revogado" ? "Desfazer revogado" : "Revogado"}</button></div></article>)}{!visibleUnits.length ? <p className="rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-600">Nenhuma Questão Sombra nesta visualização.</p> : null}</div></> : null}
  </section>;
}
