"use client";
import { useEffect, useState } from "react";
type Notice = any;
type Recipient = { id: string; nome: string | null; email: string | null };

export default function LawUpdateNoticesAdmin() {
  const [items, setItems] = useState<Notice[]>([]), [tab, setTab] = useState("draft"), [busy, setBusy] = useState(""), [recipients, setRecipients] = useState<Record<string, Recipient[]>>({});
  const load = () => fetch("/api/admin/avisos").then((response) => response.json()).then(setItems);
  useEffect(() => { void load(); }, []);
  async function act(action: string, notice: Notice, extra: Record<string, unknown> = {}) { if (action === "enviar_resend" && !confirm("Enviar e-mail manualmente aos alunos revisados?")) return; setBusy(`${notice.id}:${action}`); try { const response = await fetch("/api/admin/avisos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, id: notice.id, title: notice.title, message: notice.message, destination_url: notice.destination_url, ...extra }) }); if (action === "exportar") { if (!response.ok) throw new Error((await response.json()).error); const file = await response.blob(), link = document.createElement("a"); link.href = URL.createObjectURL(file); link.download = "avisos-alunos.csv"; link.click(); URL.revokeObjectURL(link.href); } else if (!response.ok) throw new Error((await response.json()).error); await load(); if (action === "destinatario") await loadRecipients(notice.id); } catch (error) { alert(error instanceof Error ? error.message : "Falha no aviso."); } finally { setBusy(""); } }
  async function loadRecipients(id: string) { if (recipients[id]) { setRecipients((current) => { const next = { ...current }; delete next[id]; return next; }); return; } setBusy(`${id}:recipients`); try { const response = await fetch(`/api/admin/avisos?id=${encodeURIComponent(id)}&recipients=1`), body = await response.json(); if (!response.ok) throw new Error(body.error); setRecipients((current) => ({ ...current, [id]: body })); } catch (error) { alert(error instanceof Error ? error.message : "Falha ao carregar destinatários."); } finally { setBusy(""); } }
  const filtered = items.filter((notice) => notice.status === tab);
  return <section className="commercial-admin"><div className="commercial-card"><div className="flex flex-wrap gap-2">{[["draft", "Pendentes"], ["published", "Publicados"], ["discarded", "Descartados"]].map(([value, label]) => <button className="admin-button secondary" key={value} onClick={() => setTab(value)}>{label} {value === "draft" ? items.filter((notice) => notice.status === "draft").length : ""}</button>)}</div></div>{filtered.map((notice) => <article className="commercial-card" key={notice.id}><h2>{notice.title}</h2><p>{notice.message}</p><p><strong>Lei:</strong> {notice.leis?.titulo} · {notice.leis?.slug}<br /><strong>Alterações:</strong> {notice.law_update_notice_changes?.length ?? 0} · <strong>Alunos revisados:</strong> {notice.recipient_count}</p><button className="admin-button secondary" disabled={busy === `${notice.id}:recipients`} onClick={() => void loadRecipients(notice.id)}>{recipients[notice.id] ? "Fechar destinatários" : "Revisar destinatários"}</button>{recipients[notice.id] ? <div className="law-notice-recipients"><strong>Destinatários ({recipients[notice.id].length})</strong>{recipients[notice.id].map((student) => <div key={student.id}><span>{student.nome || "Nome não informado"} · {student.email || "Sem e-mail"}</span>{notice.status !== "discarded" && notice.email_status !== "sent_resend" ? <button className="admin-link-button" disabled={Boolean(busy)} onClick={() => void act("destinatario", notice, { student_id: student.id, excluded: true })}>Remover</button> : null}</div>)}</div> : null}{notice.status === "draft" ? <div className="mt-4 grid gap-4"><label className="block font-bold">Título<input className="mt-1 block w-full" defaultValue={notice.title} onBlur={(event) => notice.title = event.target.value} /></label><label className="block font-bold">Mensagem<textarea className="mt-1 block min-h-28 w-full" defaultValue={notice.message} onBlur={(event) => notice.message = event.target.value} /></label><div className="flex flex-wrap gap-2"><button className="admin-button secondary" disabled={Boolean(busy)} onClick={() => void act("editar", notice)}>Salvar</button><button className="admin-button primary" disabled={Boolean(busy)} onClick={() => void act("publicar", notice)}>Publicar</button><button className="admin-button danger" disabled={Boolean(busy)} onClick={() => void act("descartar", notice)}>Descartar</button></div></div> : notice.status === "published" ? <div className="flex flex-wrap gap-2"><button className="admin-button secondary" disabled={Boolean(busy) || notice.email_status === "sent_resend"} onClick={() => void act("enviar_resend", notice)}>{notice.email_status === "sent_resend" ? "E-mail enviado" : "Enviar por Resend"}</button><button className="admin-button secondary" disabled={Boolean(busy)} onClick={() => void act("exportar", notice)}>Exportar e-mails</button></div> : null}</article>)}{!filtered.length ? <p>Nenhum aviso nesta lista.</p> : null}</section>;
}
