"use client";

import { FormEvent, useEffect, useState } from "react";
import { LEGISCAST_ORIGINAL_MAX_BYTES, formatLegiscastAudioSize, isAcceptedLegiscastOriginal } from "@/lib/legiscast-audio-processing";

type Law = { id: number; slug: string; titulo: string };
type Audio = { id: string; titulo: string; ordem: number; ativo: boolean; leis?: { titulo?: string } | null };
type Job = { id: string; titulo: string; status: "pendente" | "processando" | "concluido" | "erro"; statusLabel: string; original_size_bytes: number; final_size_bytes?: number | null; duracao_segundos?: number | null; tentativas: number; leis?: { titulo?: string } | null };
type AuthorizeResponse = { jobId: string; uploadUrl: string; operationToken: string };
async function readResponse(response: Response) { const text = await response.text(); try { return JSON.parse(text) as Record<string, unknown>; } catch { return { error: text || "Não foi possível concluir a operação." }; } }
function apiError(body: Record<string, unknown>, fallback: string) { return typeof body.error === "string" ? body.error : fallback; }
function reduction(job: Job) { return job.final_size_bytes ? Math.max(0, Math.round((1 - job.final_size_bytes / job.original_size_bytes) * 100)) : null; }

export function LegiscastAudiosAdmin() {
  const [laws, setLaws] = useState<Law[]>([]); const [audios, setAudios] = useState<Audio[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/admin/legiscast-audios", { cache: "no-store" }); const body = await readResponse(response); if (!response.ok) throw new Error(apiError(body, "Não foi possível carregar os áudios.")); setLaws(Array.isArray(body.laws) ? body.laws as Law[] : []); setAudios(Array.isArray(body.audios) ? body.audios as Audio[] : []); setJobs(Array.isArray(body.jobs) ? body.jobs as Job[] : []); }
  useEffect(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "Não foi possível carregar os áudios.")); }, []);
  useEffect(() => { if (!jobs.some((job) => job.status === "pendente" || job.status === "processando")) return; const interval = window.setInterval(() => void load().catch(() => undefined), 10_000); return () => window.clearInterval(interval); }, [jobs]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const file = values.get("file"); setBusy(true); setError(""); setMessage("");
    try {
      if (!(file instanceof File) || !file.size) throw new Error("Selecione um arquivo MP3, M4A ou WAV."); if (!isAcceptedLegiscastOriginal(file.name, file.type)) throw new Error("Aceitamos somente arquivos MP3, M4A ou WAV."); if (file.size > LEGISCAST_ORIGINAL_MAX_BYTES) throw new Error(`O original possui ${formatLegiscastAudioSize(file.size)} e ultrapassa o limite de 500 MB.`);
      const authorizeResponse = await fetch("/api/admin/legiscast-audios", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: "authorize-original", lawId: values.get("lei_id"), titulo: values.get("titulo"), descricao: values.get("descricao"), ordem: values.get("ordem"), ativo: values.get("ativo") === "true", fileName: file.name, mime: file.type, sizeBytes: file.size }) }); const authorizeBody = await readResponse(authorizeResponse); if (!authorizeResponse.ok) throw new Error(apiError(authorizeBody, "Não foi possível autorizar o original.")); const authorization = authorizeBody as unknown as AuthorizeResponse;
      if (!authorization.jobId || !authorization.uploadUrl || !authorization.operationToken) throw new Error("Autorização de upload inválida."); setMessage("Enviando original para o armazenamento temporário…"); const upload = await fetch(authorization.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!upload.ok) throw new Error("Não foi possível enviar o arquivo original.");
      setMessage("Original enviado. Colocando o áudio na fila…"); const confirmResponse = await fetch("/api/admin/legiscast-audios", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: "confirm-original", jobId: authorization.jobId, operationToken: authorization.operationToken }) }); const confirmBody = await readResponse(confirmResponse); if (!confirmResponse.ok) throw new Error(apiError(confirmBody, "Não foi possível iniciar o processamento.")); form.reset(); setMessage("Áudio na fila de processamento."); await load();
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível enviar o áudio."); } finally { setBusy(false); }
  }
  async function retry(jobId: string) { setError(""); try { const response = await fetch("/api/admin/legiscast-audios", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: "retry", jobId }) }); const body = await readResponse(response); if (!response.ok) throw new Error(apiError(body, "Não foi possível repetir o processamento.")); setMessage("Nova tentativa colocada na fila."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível repetir o processamento."); } }
  return <section className="commercial-card"><h2>Áudios do LegisCast</h2><p>Envie o original em MP3, M4A ou WAV (até 500 MB). O sistema converte para voz em M4A otimizado antes de publicar.</p><form className="commercial-form-grid" onSubmit={(event) => void submit(event)}><select name="lei_id" required defaultValue=""><option value="" disabled>Selecione a lei</option>{laws.map((law) => <option key={law.id} value={law.id}>{law.titulo}</option>)}</select><input name="titulo" required placeholder="Título da faixa" /><textarea name="descricao" placeholder="Descrição opcional" /><input name="ordem" type="number" min="0" defaultValue="0" /><label>Original MP3, M4A ou WAV<input name="file" type="file" accept="audio/mpeg,audio/mp4,audio/x-m4a,audio/wav,.mp3,.m4a,.wav" required /></label><select name="ativo" defaultValue="true"><option value="true">Publicar ao concluir</option><option value="false">Manter inativo ao concluir</option></select><button className="admin-button primary" disabled={busy}>{busy ? "Enviando…" : "Enviar e processar"}</button></form>{error ? <p className="admin-alert error" role="alert">{error}</p> : null}{message ? <p className="admin-alert success" role="status">{message}</p> : null}<div className="mt-6 grid gap-2"><h3 className="font-black">Processamentos recentes</h3>{jobs.map((job) => <article key={job.id} className="rounded-lg border border-slate-200 px-3 py-3"><strong>{job.titulo}</strong> · {job.leis?.titulo ?? "Lei"}<p className="text-sm">{job.statusLabel} · original {formatLegiscastAudioSize(job.original_size_bytes)}{job.final_size_bytes ? <> · final {formatLegiscastAudioSize(job.final_size_bytes)} · redução {reduction(job)}%{job.duracao_segundos ? ` · ${job.duracao_segundos}s` : ""}</> : null}</p>{job.status === "erro" ? <><p className="text-sm text-red-700">Não foi possível processar este áudio.</p>{job.tentativas < 3 ? <button type="button" className="admin-button" onClick={() => void retry(job.id)}>Tentar novamente ({3 - job.tentativas})</button> : null}</> : null}</article>)}</div><ul className="mt-6 grid gap-2">{audios.map((audio) => <li key={audio.id} className="rounded-lg border border-slate-200 px-3 py-2"><strong>{audio.titulo}</strong> · {audio.leis?.titulo ?? "Lei"} · ordem {audio.ordem} · {audio.ativo ? "ativo" : "inativo"}</li>)}</ul></section>;
}
