"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Diagnosis = "never_sent" | "send_failed" | "auth_existing" | "invalid_email" | "inconclusive";
type Item = { compraId: string; nome: string | null; email: string | null; produto: string; etapaAtual: number; etapaTitulo: string | null; e3Diagnosis: Diagnosis | null; failureMessage: string | null; notificationStatus?: string | null };
type Editorial = { subject: string; title: string; message: string; buttonText: string; footer: string };
type Summary = { total: number; etapa_1: number; etapa_2: number; etapa_3: number; etapa_4: number; etapa_5: number; etapa_6: number };
type Preview = { selected: number; eligible: number; ignored: number; flows: { existing_account: number; first_access: number }; editorial: Editorial; sample: { compraId: string; destinatario: string; tipoFluxo: string; destinoBotao: string }[] };
const labels: Record<Diagnosis, string> = { never_sent: "Nunca enviado", send_failed: "Falha no envio", auth_existing: "Auth existente", invalid_email: "E-mail inválido", inconclusive: "Inconclusivo" };
const initialEditorial: Editorial = { subject: "Seu acesso ao Legis Flashcards está disponível", title: "Seu acesso está liberado", message: "Olá, {{nome}}. Seu acesso a {{produto}} já está liberado.", buttonText: "Acessar minha conta", footer: "Use a recuperação de acesso se não lembrar sua senha." };

async function request(body: Record<string, unknown>) { const response = await fetch("/api/admin/comercial/alunos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Operação indisponível."); return data; }

export default function PostSalePendingCenter() {
  const [items, setItems] = useState<Item[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [stage, setStage] = useState(0); const [diagnosis, setDiagnosis] = useState<"all" | Diagnosis>("all"); const [selected, setSelected] = useState<Set<string>>(new Set()); const [preview, setPreview] = useState<Preview | null>(null); const [editorial, setEditorial] = useState<Editorial>(initialEditorial); const [history, setHistory] = useState<Record<string, unknown>[] | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  async function load() { setBusy(true); try { const data = await request({ action: "crm_central_pendencias" }); setItems(data.items ?? []); setSummary(data.resumo ?? null); } catch (e) { setError(e instanceof Error ? e.message : "Central indisponível."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []); useEffect(() => { setSelected(new Set()); setDiagnosis("all"); }, [stage]);
  const filtered = useMemo(() => items.filter((item) => (!stage || item.etapaAtual === stage) && (stage !== 3 || diagnosis === "all" || item.e3Diagnosis === diagnosis)), [items, stage, diagnosis]);
  async function prepare() { setBusy(true); try { const data = await request({ action: "crm_previa_email_acesso", compra_ids: [...selected], editorial }); setPreview(data); setEditorial(data.editorial); } catch (e) { setError(e instanceof Error ? e.message : "Prévia indisponível."); } finally { setBusy(false); } }
  async function send() { setBusy(true); try { await request({ action: "crm_enviar_email_acesso_lote", compra_ids: [...selected], editorial }); setPreview(null); setSelected(new Set()); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Envio indisponível."); } finally { setBusy(false); } }
  async function showHistory(compraId: string) { setBusy(true); try { const data = await request({ action: "crm_historico_email_acesso", compra_id: compraId }); setHistory(data.attempts ?? []); } catch (e) { setError(e instanceof Error ? e.message : "Histórico indisponível."); } finally { setBusy(false); } }
  const setField = (field: keyof Editorial, value: string) => setEditorial((current) => ({ ...current, [field]: value }));
  return <section className="post-sale-center"><header className="commercial-card"><Link className="admin-central-link" href="/admin/alunos">← Painel de Alunos</Link><h2>Pós-vendas pendentes</h2><p><strong>{summary?.total ?? "—"}</strong> compras precisam de atenção</p><div className="post-sale-stage-filters"><button className={!stage ? "active" : ""} onClick={() => setStage(0)}>Todos {summary?.total ?? 0}</button>{[1, 2, 3, 4, 5, 6].map((value) => <button key={value} className={stage === value ? "active" : ""} onClick={() => setStage(value)}>E{value} {summary?.[`etapa_${value}` as keyof Summary] ?? 0}</button>)}</div></header>
    {stage === 3 ? <section className="commercial-card"><h3>Diagnóstico da Etapa 3</h3>{(["all", "never_sent", "send_failed", "auth_existing", "invalid_email", "inconclusive"] as const).map((value) => <button key={value} className={diagnosis === value ? "active" : ""} onClick={() => setDiagnosis(value)}>{value === "all" ? "Todos" : labels[value]}</button>)}</section> : null}{error ? <p className="admin-alert error">{error}</p> : null}
    <section className="post-sale-center-list">{busy && !items.length ? <p>Carregando…</p> : <><label className="post-sale-select-all"><input type="checkbox" checked={filtered.length > 0 && filtered.every((item) => selected.has(item.compraId))} onChange={() => { const all = filtered.every((item) => selected.has(item.compraId)); setSelected((old) => { const next = new Set(old); filtered.forEach((item) => all ? next.delete(item.compraId) : next.add(item.compraId)); return next; }); }} /> Selecionar todos os {filtered.length} registros exibidos</label>{filtered.map((item) => <article className="post-sale-pending-card" key={item.compraId}><label><input type="checkbox" checked={selected.has(item.compraId)} onChange={() => setSelected((old) => { const next = new Set(old); next.has(item.compraId) ? next.delete(item.compraId) : next.add(item.compraId); return next; })} /></label><div><strong>{item.nome || "Aluno sem nome"}</strong><p>{item.produto}</p><small>Etapa {item.etapaAtual} · {item.etapaTitulo}</small>{item.e3Diagnosis ? <p>Diagnóstico: {labels[item.e3Diagnosis]}</p> : null}{item.failureMessage ? <p>Motivo: {item.failureMessage}</p> : null}{item.notificationStatus === "enviado" ? <button className="admin-button secondary" onClick={() => void showHistory(item.compraId)}>Ver e-mail enviado</button> : null}</div></article>)}</>}</section>
    {selected.size ? <aside className="post-sale-bulk-bar"><strong>{selected.size} selecionados</strong><button className="admin-button primary" disabled={busy} onClick={() => void prepare()}>Preparar envio</button><button className="admin-button secondary" onClick={() => setSelected(new Set())}>Limpar</button></aside> : null}
    {preview ? <div className="post-sale-preview-backdrop"><section className="commercial-card post-sale-preview" role="dialog" aria-modal="true"><h2>Confirmar envio</h2><p>Você está prestes a enviar este conteúdo para {preview.eligible} destinatários.</p><p>Conta existente: {preview.flows.existing_account} · Primeiro acesso: {preview.flows.first_access}</p><label>Assunto<input value={editorial.subject} onChange={(e) => setField("subject", e.target.value)} /></label><label>Título<input value={editorial.title} onChange={(e) => setField("title", e.target.value)} /></label><label>Mensagem<textarea value={editorial.message} onChange={(e) => setField("message", e.target.value)} /></label><label>Texto do botão<input value={editorial.buttonText} onChange={(e) => setField("buttonText", e.target.value)} /></label><label>Rodapé<textarea value={editorial.footer} onChange={(e) => setField("footer", e.target.value)} /></label><small>Somente texto e &#123;&#123;nome&#125;&#125;, &#123;&#123;produto&#125;&#125; e &#123;&#123;email&#125;&#125;. Links e tokens não são editáveis.</small>{preview.sample.map((sample) => <p key={sample.compraId}><b>{sample.tipoFluxo}</b> · {sample.destinatario} · {sample.destinoBotao}</p>)}<button className="admin-button primary" disabled={busy || !preview.eligible} onClick={() => void send()}>{`Enviar ${preview.eligible} e-mails`}</button><button className="admin-button secondary" onClick={() => void prepare()}>Atualizar prévia</button><button className="admin-button secondary" onClick={() => setPreview(null)}>Fechar</button></section></div> : null}
    {history ? <div className="post-sale-preview-backdrop"><section className="commercial-card post-sale-preview" role="dialog" aria-modal="true"><h2>Histórico de e-mails</h2>{history.length ? history.map((attempt) => <article key={String(attempt.id)}><p><b>{String(attempt.status)}</b> · {String(attempt.destinatario)}</p><p>Assunto: {String(attempt.assunto)}</p><pre>{String(attempt.text_snapshot)}</pre><small>Botão: {String(attempt.botao_texto)} · {String(attempt.destino_botao)}</small></article>) : <p>Conteúdo exato não foi armazenado neste envio anterior.</p>}<button onClick={() => setHistory(null)}>Fechar</button></section></div> : null}
  </section>;
}
