"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Diagnosis = "never_sent" | "send_failed" | "auth_existing" | "invalid_email" | "inconclusive";
type Item = { compraId: string; alunoId: string | null; nome: string | null; email: string | null; produto: string; etapaAtual: number; etapaTitulo: string | null; e3Diagnosis: Diagnosis | null; failureMessage: string | null };
type Summary = { total: number; etapa_1: number; etapa_2: number; etapa_3: number; etapa_4: number; etapa_5: number; etapa_6: number };
const labels: Record<Diagnosis, string> = { never_sent: "Nunca enviado", send_failed: "Falha no envio", auth_existing: "Auth existente", invalid_email: "E-mail inválido", inconclusive: "Inconclusivo" };
const reasons: Record<string, string> = { invalid_email: "e-mails inválidos", access_inactive: "acessos não estão mais ativos", e3_completed: "E3 já concluída", inconsistent: "dados inconsistentes" };

async function request(body: Record<string, unknown>) {
  const response = await fetch("/api/admin/comercial/alunos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível concluir a operação.");
  return data;
}

export default function PostSalePendingCenter() {
  const [items, setItems] = useState<Item[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [stage, setStage] = useState(0); const [diagnosis, setDiagnosis] = useState<"all" | Diagnosis>("all"); const [selected, setSelected] = useState<Set<string>>(new Set()); const [preview, setPreview] = useState<{ selected: number; eligible: number; ignored: number; reasons: Record<string, number> } | null>(null); const [result, setResult] = useState<{ summary: { sent: number; ignored: number; blocked: number; failed: number }; results: { compraId: string; status: string; reason: string }[] } | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  async function load() { setBusy(true); setError(""); try { const data = await request({ action: "crm_central_pendencias" }); setItems(data.items ?? []); setSummary(data.resumo ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar a Central."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  useEffect(() => { setSelected(new Set()); setDiagnosis("all"); }, [stage]);
  const filtered = useMemo(() => items.filter((item) => (!stage || item.etapaAtual === stage) && (stage !== 3 || diagnosis === "all" || item.e3Diagnosis === diagnosis)), [items, stage, diagnosis]);
  const diagnosisCounts = useMemo(() => Object.fromEntries((["never_sent", "send_failed", "auth_existing", "invalid_email", "inconclusive"] as Diagnosis[]).map((value) => [value, items.filter((item) => item.etapaAtual === 3 && item.e3Diagnosis === value).length])) as Record<Diagnosis, number>, [items]);
  const allSelected = filtered.length > 0 && filtered.every((item) => selected.has(item.compraId));
  function toggleAll() { setSelected((current) => { const next = new Set(current); if (allSelected) filtered.forEach((item) => next.delete(item.compraId)); else filtered.forEach((item) => next.add(item.compraId)); return next; }); }
  async function prepare() { setBusy(true); setError(""); try { setPreview(await request({ action: "crm_previa_email_acesso", compra_ids: [...selected] })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível preparar a prévia."); } finally { setBusy(false); } }
  async function send() { setBusy(true); setError(""); try { const next = await request({ action: "crm_enviar_email_acesso_lote", compra_ids: [...selected] }); setResult(next); setSelected(new Set()); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível enviar os e-mails."); } finally { setBusy(false); } }
  return <section className="post-sale-center">
    <header className="commercial-card"><Link className="admin-central-link" href="/admin/alunos">← Painel de Alunos</Link><h2>Pós-vendas pendentes</h2><p><strong>{summary?.total ?? "—"}</strong> compras precisam de atenção</p><div className="post-sale-stage-filters" aria-label="Filtrar pendências por etapa"><button className={!stage ? "active" : ""} onClick={() => setStage(0)}>Todos {summary?.total ?? 0}</button>{[1,2,3,4,5,6].map((value) => <button key={value} className={stage === value ? "active" : ""} onClick={() => setStage(value)}>E{value} {summary?.[`etapa_${value}` as keyof Summary] ?? 0}</button>)}</div></header>
    {stage === 3 ? <section className="commercial-card"><h3>Diagnóstico da Etapa 3</h3><div className="post-sale-diagnosis-filters"><button className={diagnosis === "all" ? "active" : ""} onClick={() => setDiagnosis("all")}>Todos {summary?.etapa_3 ?? 0}</button>{(["never_sent", "send_failed", "auth_existing", "invalid_email", "inconclusive"] as Diagnosis[]).map((value) => <button key={value} className={diagnosis === value ? "active" : ""} onClick={() => setDiagnosis(value)}>{labels[value]} {diagnosisCounts[value]}</button>)}</div></section> : null}
    {error ? <p className="admin-alert error">{error}</p> : null}
    <section className="post-sale-center-list" aria-live="polite">{busy && !items.length ? <p>Carregando pendências…</p> : <><label className="post-sale-select-all"><input type="checkbox" checked={allSelected} onChange={toggleAll} /> Selecionar todos os {filtered.length} registros exibidos</label>{filtered.map((item) => <article className="post-sale-pending-card" key={item.compraId}><label><input type="checkbox" checked={selected.has(item.compraId)} onChange={() => setSelected((current) => { const next = new Set(current); next.has(item.compraId) ? next.delete(item.compraId) : next.add(item.compraId); return next; })} aria-label={`Selecionar ${item.nome ?? "compra"}`} /></label><div><strong>{item.nome || "Aluno sem nome"}</strong><p>{item.produto}</p><small>Etapa {item.etapaAtual} · {item.etapaTitulo}</small>{item.etapaAtual === 3 && item.e3Diagnosis ? <p className="post-sale-diagnosis"><b>Diagnóstico:</b> {labels[item.e3Diagnosis]}</p> : null}{item.failureMessage ? <p className="post-sale-failure">Motivo: {item.failureMessage}</p> : null}<a href="/admin/alunos">Ir ao Painel de Alunos</a></div></article>)}{!filtered.length ? <p>Nenhuma compra pendente neste filtro.</p> : null}</>}</section>
    {selected.size ? <aside className="post-sale-bulk-bar"><strong>{selected.size} selecionados</strong><button className="admin-button primary" disabled={busy} onClick={() => void prepare()}>Preparar envio</button><button className="admin-button secondary" disabled={busy} onClick={() => setSelected(new Set())}>Limpar</button></aside> : null}
    {preview ? <div className="post-sale-preview-backdrop" role="presentation"><section className="commercial-card post-sale-preview" role="dialog" aria-modal="true" aria-label="Prévia de envio de acesso">{result ? <><h2>Resultado do lote</h2><p><strong>{result.summary.sent} enviados</strong> · {result.summary.ignored} ignorados · {result.summary.blocked} bloqueados · {result.summary.failed} falharam</p>{result.results.filter((item) => item.status !== "sent").length ? <ul>{result.results.filter((item) => item.status !== "sent").map((item) => <li key={item.compraId}>{item.reason}</li>)}</ul> : null}<button className="admin-button secondary" onClick={() => { setPreview(null); setResult(null); }}>Fechar</button></> : <><h2>Prévia do envio</h2><p>{preview.selected} selecionados</p><p><strong>{preview.eligible} aptos</strong> · {preview.ignored} ignorados</p>{preview.ignored ? <ul>{Object.entries(preview.reasons).filter(([, count]) => count).map(([reason, count]) => <li key={reason}>{count} — {reasons[reason] ?? "casos inconclusivos"}</li>)}</ul> : null}{preview.eligible ? <button className="admin-button primary" disabled={busy} onClick={() => void send()}>{busy ? "Enviando…" : `Enviar ${preview.eligible} e-mails`}</button> : null}<button className="admin-button secondary" disabled={busy} onClick={() => setPreview(null)}>Fechar</button></>}</section></div> : null}
  </section>;
}
