"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { StudentPostSaleCrm } from "@/components/admin/student-postsale-crm";

type Row = Record<string, unknown>;
const text = (value: unknown) => value == null ? "" : String(value);
const relation = (row: Row, key: string) => row[key] && typeof row[key] === "object" && !Array.isArray(row[key]) ? row[key] as Row : {};
const date = (value: unknown) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(String(value))) : "—";
function wa(student: Row) { const phone = text(student.telefone).replace(/\D/g, ""); return phone ? `https://wa.me/${phone.startsWith("55") ? phone : `55${phone}`}` : ""; }
async function requestJson(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(text(data.error) || "Não foi possível concluir a operação."); return data; }

export default function StudentsAdmin() {
  const [items, setItems] = useState<Row[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Row | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [acquisitions, setAcquisitions] = useState<Row[]>([]); const [releases, setReleases] = useState<Row[]>([]); const [editing, setEditing] = useState(false); const [message, setMessage] = useState("");
  const [pendingSales, setPendingSales] = useState<Row[]>([]); const [pendingCounts, setPendingCounts] = useState<number[]>([0,0,0,0,0,0]); const [pendingWarning, setPendingWarning] = useState(""); const [focusPurchase, setFocusPurchase] = useState("");
  const load = useCallback(async (search = "") => { setBusy(true); setError(""); try { const data = await requestJson(`/api/admin/comercial/alunos?q=${encodeURIComponent(search)}&limit=25`); setItems(data.items ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível buscar alunos."); } finally { setBusy(false); } }, []);
  useEffect(() => { void load(""); }, [load]);
  useEffect(() => { void (async () => { try { const data = await requestJson("/api/admin/comercial/alunos", { method: "POST", body: JSON.stringify({ action: "crm_pendencias" }) }); setPendingSales(data.items ?? []); setPendingCounts(data.counts ?? [0,0,0,0,0,0]); setPendingWarning(data.unavailable ? text(data.message) : ""); } catch (caught) { setPendingWarning(caught instanceof Error ? caught.message : "Não foi possível carregar as pendências."); } })(); }, []);
  async function open(student: Row, compraId = "") { setSelected(student); setFocusPurchase(compraId); setBusy(true); setError(""); setEditing(false); const id = encodeURIComponent(text(student.id)); try { const [purchases, laws] = await Promise.all([requestJson(`/api/admin/comercial/aquisicoes?aluno_id=${id}&limit=50`), requestJson(`/api/admin/comercial/liberacoes?aluno_id=${id}&limit=50`)]); setAcquisitions(purchases.items ?? []); setReleases(laws.items ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar a ficha do aluno."); } finally { setBusy(false); } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); setError(""); try { const data = Object.fromEntries(new FormData(event.currentTarget)); const updated = await requestJson("/api/admin/comercial/alunos", { method: "POST", body: JSON.stringify({ action: "atualizar_ficha", id: selected.id, data }) }); setSelected({ ...selected, ...updated }); setItems((current) => current.map((row) => text(row.id) === text(selected.id) ? { ...row, ...updated } : row)); setEditing(false); setMessage("Dados atualizados."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível atualizar o aluno."); } finally { setBusy(false); } }
  async function email() { if (!selected) return; setBusy(true); try { await requestJson("/api/admin/comercial/alunos", { method: "POST", body: JSON.stringify({ action: "enviar_email_acesso", id: selected.id }) }); setMessage("E-mail de acesso enviado."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Falha no envio de e-mail."); } finally { setBusy(false); } }
  return <section className="students-admin">
    <form className="students-search" onSubmit={(event) => { event.preventDefault(); void load(query); }}><label>Buscar aluno<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, e-mail, telefone ou UUID" /></label><button className="admin-button primary" disabled={busy}>Buscar</button></form>
    {error ? <p className="admin-alert error" role="alert">{error}</p> : null}{message ? <p className="admin-alert success">{message}</p> : null}
    {!selected ? <section className="post-sale-pending"><h2>Pós-vendas pendentes</h2><p><strong>{pendingSales.length}</strong> compras precisam de atenção</p>{pendingWarning ? <p className="admin-alert error">{pendingWarning}</p> : null}<div className="pending-counts">{pendingCounts.map((count, index) => <span key={index}>Etapa {index + 1}: {count}</span>)}</div>{pendingSales.length ? <div className="pending-list">{pendingSales.map((sale) => <button type="button" key={text(sale.compra_id)} onClick={() => void open({ id: sale.aluno_id, nome: sale.nome, email: sale.email, telefone: sale.telefone }, text(sale.compra_id))}><strong>{text(sale.nome) || "Nome não informado"}</strong><span>{text(sale.produto)}</span><small>Etapa {text(sale.proxima_etapa)} · { ["Compra registrada","Acesso liberado","E-mail de acesso","Primeiro acesso","Confirmar acesso","Confirmar Anki"][Number(sale.proxima_etapa)-1] }</small></button>)}</div> : <p>Nenhum pós-venda pendente.</p>}</section> : null}
    {!selected ? <div className="students-list" aria-label="Lista de alunos">{items.map((student) => <article key={text(student.id)} className="student-card"><button type="button" className="student-card-name" onClick={() => void open(student)}><strong>{text(student.nome) || "Nome não informado"} ›</strong><span>Abrir ficha e Mini-CRM</span></button>{text(student.nome_publico) ? <small>Nome público: {text(student.nome_publico)}</small> : null}<a href={`mailto:${text(student.email)}`}>{text(student.email)}</a>{wa(student) ? <a href={wa(student)} target="_blank" rel="noreferrer">{text(student.telefone)}</a> : <small>Telefone não informado</small>}<small>{text(student.produtos_ativos) || "0"} produto(s) ativo(s) · {student.primeiro_acesso_em ? "já acessou" : "primeiro acesso pendente"}</small><button type="button" className="student-card-crm" onClick={() => void open(student)}>Pós-venda · abrir Mini-CRM</button></article>)}{!busy && !items.length ? <p>Nenhum aluno encontrado.</p> : null}</div> : <article className="student-detail">
      <button type="button" className="admin-button secondary" onClick={() => { setSelected(null); setError(""); }}>← Voltar à lista</button>
      <header>{editing ? <form className="student-inline-edit" onSubmit={save}><label>Nome completo<input name="nome" defaultValue={text(selected.nome)} /></label><label>Nome público<input name="nome_publico" defaultValue={text(selected.nome_publico)} /></label><label>E-mail<input value={text(selected.email)} readOnly /></label><label>Telefone<input name="telefone" defaultValue={text(selected.telefone)} /></label><div className="student-detail-actions"><button className="admin-button primary" disabled={busy}>Salvar</button><button type="button" className="admin-button secondary" onClick={() => setEditing(false)}>Cancelar</button></div></form> : <><div><h2>{text(selected.nome) || "Nome completo: Não informado"}</h2><p><b>Nome público:</b> {text(selected.nome_publico) || "Não informado"}<br /><b>E-mail:</b> <a href={`mailto:${text(selected.email)}`}>{text(selected.email)}</a><br /><b>Telefone:</b> {wa(selected) ? <a href={wa(selected)} target="_blank" rel="noreferrer">{text(selected.telefone)}</a> : "Não informado"}</p></div><div className="student-detail-actions"><button type="button" className="admin-button primary" onClick={() => void email()} disabled={busy}>Enviar e-mail</button><button type="button" className="admin-button secondary" onClick={() => setEditing(true)}>Editar</button></div></>}</header>
      <StudentPostSaleCrm student={selected} focusPurchase={focusPurchase} />
      <details open><summary>Acessos e conta</summary><p><b>Conta:</b> {selected.user_id ? "vinculada ao Auth" : "sem conta vinculada"}</p><p><b>Primeiro acesso:</b> {date(selected.primeiro_acesso_em)} · <b>Último:</b> {date(selected.ultimo_acesso_em)}</p></details>
      <details><summary>Compras e aquisições ({acquisitions.length})</summary>{acquisitions.length ? <ul>{acquisitions.map((item) => <li key={text(item.id)}>{text(relation(item, "produtos").nome) || "Produto"} · {text(item.status_acesso)} · {date(item.adquirida_em)}</li>)}</ul> : <p>Nenhuma aquisição.</p>}</details>
      <details><summary>Leis liberadas ({releases.length})</summary>{releases.length ? <ul>{releases.map((item) => <li key={text(item.id)}>{text(relation(item, "leis").titulo) || "Lei"} · {text(item.status)}</li>)}</ul> : <p>Nenhuma liberação.</p>}</details>
    </article>}
  </section>;
}
