begin;

create table if not exists public.law_update_notices (
  id uuid primary key default gen_random_uuid(), law_id bigint not null references public.leis(id) on delete cascade,
  title text not null, message text not null, destination_url text,
  status text not null default 'draft' check (status in ('draft','published','discarded')),
  origin text not null default 'automatic', email_status text not null default 'not_sent' check (email_status in ('not_sent','sending_resend','sent_resend','failed_resend','exported')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  published_at timestamptz, discarded_at timestamptz, email_sent_at timestamptz, email_exported_at timestamptz,
  email_recipient_count integer not null default 0, email_error text
);
create unique index if not exists law_update_notices_one_draft_per_law on public.law_update_notices(law_id) where status='draft';
create index if not exists law_update_notices_status_created_idx on public.law_update_notices(status,created_at desc);
create index if not exists law_update_notices_law_idx on public.law_update_notices(law_id);

create table if not exists public.law_update_notice_changes (
  id bigint generated by default as identity primary key, notice_id uuid not null references public.law_update_notices(id) on delete cascade,
  kind text not null check (kind in ('question_added','question_changed','question_removed','structure_changed','law_content_changed')),
  summary text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists law_update_notice_changes_notice_idx on public.law_update_notice_changes(notice_id,created_at);

create table if not exists public.law_update_notice_deliveries (
  notice_id uuid not null references public.law_update_notices(id) on delete cascade,
  student_id uuid not null references public.alunos(id) on delete cascade,
  read_at timestamptz, created_at timestamptz not null default now(), primary key(notice_id,student_id)
);
create index if not exists law_update_notice_deliveries_student_unread_idx on public.law_update_notice_deliveries(student_id,created_at desc) where read_at is null;

create or replace function public.law_update_notice_touch() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists law_update_notice_touch on public.law_update_notices;
create trigger law_update_notice_touch before update on public.law_update_notices for each row execute function public.law_update_notice_touch();

-- Canonical aggregation entry point. The partial unique index serializes competing drafts per law.
create or replace function public.record_law_update_notice_event(p_law_id bigint,p_kind text,p_summary text,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path=pg_catalog as $$
declare v_notice uuid; v_law public.leis; v_title text;
begin
  if p_kind not in ('question_added','question_changed','question_removed','structure_changed','law_content_changed') or coalesce(btrim(p_summary),'')='' then raise exception 'Invalid notice event'; end if;
  select * into v_law from public.leis where id=p_law_id; if not found then raise exception 'Law not found'; end if;
  v_title:=coalesce(nullif(v_law.nome_curto,''),v_law.titulo)||' atualizada';
  insert into public.law_update_notices(law_id,title,message,destination_url)
  values(p_law_id,v_title,'Atualizamos questões e conteúdos desta lei. Confira as alterações no Legis Questões.','/questoes/'||v_law.slug||'/estudar')
  on conflict (law_id) where status='draft' do update set updated_at=now()
  returning id into v_notice;
  insert into public.law_update_notice_changes(notice_id,kind,summary,metadata) values(v_notice,p_kind,p_summary,coalesce(p_metadata,'{}'::jsonb));
  return v_notice;
end $$;

create or replace function public.publish_law_update_notice(p_notice_id uuid)
returns integer language plpgsql security definer set search_path=pg_catalog as $$
declare v_law bigint; v_status text; v_count integer;
begin
  select law_id,status into v_law,v_status from public.law_update_notices where id=p_notice_id for update;
  if not found or v_status='discarded' then raise exception 'Draft notice not found'; end if;
  if v_status='published' then select count(*)::integer into v_count from public.law_update_notice_deliveries where notice_id=p_notice_id; return v_count; end if;
  update public.law_update_notices set status='published',published_at=now() where id=p_notice_id;
  insert into public.law_update_notice_deliveries(notice_id,student_id)
    select p_notice_id,l.aluno_id from public.liberacoes_leis l where l.lei_id=v_law and l.status='ativo'
    on conflict (notice_id,student_id) do nothing;
  get diagnostics v_count=row_count; return v_count;
end $$;

create or replace function public.claim_law_update_notice_resend(p_notice_id uuid)
returns boolean language plpgsql security definer set search_path=pg_catalog as $$
begin
  update public.law_update_notices set email_status='sending_resend',email_error=null
  where id=p_notice_id and status='published' and email_status='not_sent';
  return found;
end $$;

create or replace function public.finish_law_update_notice_resend(p_notice_id uuid,p_success boolean,p_count integer,p_error text default null)
returns void language plpgsql security definer set search_path=pg_catalog as $$
begin
  update public.law_update_notices set email_status=case when p_success then 'sent_resend' else 'failed_resend' end,
    email_sent_at=case when p_success then now() else null end,email_recipient_count=p_count,email_error=p_error
  where id=p_notice_id and email_status='sending_resend';
end $$;

-- These statement triggers keep the content change and notice event in one database transaction.
-- Transition tables make imports aggregate once per law instead of once per row.
create or replace function public.capture_question_notice_changes() returns trigger language plpgsql security definer set search_path=pg_catalog as $$
declare r record;
begin
  if tg_op='INSERT' then for r in select lei_id,count(*)::integer as n from new_rows group by lei_id loop perform public.record_law_update_notice_event(r.lei_id,'question_added',r.n||' questão(ões) adicionada(s).',jsonb_build_object('count',r.n,'bulk',r.n>1)); end loop;
  elsif tg_op='DELETE' then for r in select lei_id,count(*)::integer as n from old_rows group by lei_id loop perform public.record_law_update_notice_event(r.lei_id,'question_removed',r.n||' questão(ões) removida(s).',jsonb_build_object('count',r.n,'bulk',r.n>1)); end loop;
  else
    for r in select n.lei_id,count(*)::integer as n from new_rows n join old_rows o using(id) where n.pergunta is distinct from o.pergunta or n.resposta is distinct from o.resposta or n.justificativa is distinct from o.justificativa or n.legislacao is distinct from o.legislacao or n.ativo is distinct from o.ativo group by n.lei_id loop perform public.record_law_update_notice_event(r.lei_id,'question_changed',r.n||' questão(ões) alterada(s).',jsonb_build_object('count',r.n,'bulk',r.n>1)); end loop;
  end if; return null;
end $$;
create or replace function public.capture_structure_notice_changes() returns trigger language plpgsql security definer set search_path=pg_catalog as $$
declare r record;
begin
  if tg_op='INSERT' then for r in select lei_id,count(*)::integer as n from new_rows group by lei_id loop perform public.record_law_update_notice_event(r.lei_id,'structure_changed','Estrutura da lei atualizada.',jsonb_build_object('count',r.n,'bulk',r.n>1)); end loop;
  elsif tg_op='DELETE' then for r in select lei_id,count(*)::integer as n from old_rows group by lei_id loop perform public.record_law_update_notice_event(r.lei_id,'structure_changed','Estrutura da lei removida.',jsonb_build_object('count',r.n,'bulk',r.n>1)); end loop;
  else for r in select n.lei_id,count(*)::integer as n from new_rows n join old_rows o using(id) where n.nome is distinct from o.nome or n.ativo is distinct from o.ativo group by n.lei_id loop perform public.record_law_update_notice_event(r.lei_id,'structure_changed','Estrutura da lei atualizada.',jsonb_build_object('count',r.n,'bulk',r.n>1)); end loop; end if; return null;
end $$;
drop trigger if exists law_update_notice_questions_insert on public.questions;
drop trigger if exists law_update_notice_questions_update on public.questions;
drop trigger if exists law_update_notice_questions_delete on public.questions;
create trigger law_update_notice_questions_insert after insert on public.questions referencing new table as new_rows for each statement execute function public.capture_question_notice_changes();
create trigger law_update_notice_questions_update after update on public.questions referencing old table as old_rows new table as new_rows for each statement execute function public.capture_question_notice_changes();
create trigger law_update_notice_questions_delete after delete on public.questions referencing old table as old_rows for each statement execute function public.capture_question_notice_changes();
drop trigger if exists law_update_notice_structure_insert on public.law_structure;
drop trigger if exists law_update_notice_structure_update on public.law_structure;
drop trigger if exists law_update_notice_structure_delete on public.law_structure;
create trigger law_update_notice_structure_insert after insert on public.law_structure referencing new table as new_rows for each statement execute function public.capture_structure_notice_changes();
create trigger law_update_notice_structure_update after update on public.law_structure referencing old table as old_rows new table as new_rows for each statement execute function public.capture_structure_notice_changes();
create trigger law_update_notice_structure_delete after delete on public.law_structure referencing old table as old_rows for each statement execute function public.capture_structure_notice_changes();
create or replace function public.capture_law_editorial_notice_changes() returns trigger language plpgsql security definer set search_path=pg_catalog as $$
begin
  if tg_table_name='leis' then
    if new.descricao is distinct from old.descricao or new.houve_alteracao_legislativa is distinct from old.houve_alteracao_legislativa or new.ultima_alteracao_referencia is distinct from old.ultima_alteracao_referencia or new.ultima_alteracao_data is distinct from old.ultima_alteracao_data or new.situacao_atualizacao is distinct from old.situacao_atualizacao or new.norma_originaria_referencia is distinct from old.norma_originaria_referencia then perform public.record_law_update_notice_event(new.id,'law_content_changed','Conteúdo editorial da lei atualizado.','{}'::jsonb); end if;
  elsif new.titulo is distinct from old.titulo or new.descricao is distinct from old.descricao or new.url_externa is distinct from old.url_externa or new.quantidade_itens is distinct from old.quantidade_itens or new.versao_material is distinct from old.versao_material or new.revisado_em is distinct from old.revisado_em or new.publicado_em is distinct from old.publicado_em or new.ativo is distinct from old.ativo then perform public.record_law_update_notice_event(new.lei_id,'law_content_changed','Material de estudo da lei atualizado.','{}'::jsonb); end if;
  return null;
end $$;
drop trigger if exists law_update_notice_law_editorial on public.leis;
drop trigger if exists law_update_notice_material_editorial on public.materiais_leis;
create trigger law_update_notice_law_editorial after update on public.leis for each row execute function public.capture_law_editorial_notice_changes();
create trigger law_update_notice_material_editorial after update on public.materiais_leis for each row execute function public.capture_law_editorial_notice_changes();

alter table public.law_update_notices enable row level security;
alter table public.law_update_notice_changes enable row level security;
alter table public.law_update_notice_deliveries enable row level security;
revoke all on public.law_update_notices,public.law_update_notice_changes,public.law_update_notice_deliveries from public,anon,authenticated;
grant select,insert,update,delete on public.law_update_notices,public.law_update_notice_changes,public.law_update_notice_deliveries to service_role;
grant select on public.law_update_notices,public.law_update_notice_changes,public.law_update_notice_deliveries to authenticated;
grant update(read_at) on public.law_update_notice_deliveries to authenticated;
create policy law_update_notice_deliveries_student_read on public.law_update_notice_deliveries for select to authenticated using (student_id in (select id from public.alunos where user_id=auth.uid()));
create policy law_update_notice_deliveries_student_mark_read on public.law_update_notice_deliveries for update to authenticated using (student_id in (select id from public.alunos where user_id=auth.uid())) with check (student_id in (select id from public.alunos where user_id=auth.uid()));
create policy law_update_notices_student_read on public.law_update_notices for select to authenticated using (exists (select 1 from public.law_update_notice_deliveries d join public.alunos a on a.id=d.student_id where d.notice_id=id and a.user_id=auth.uid()));
create policy law_update_notice_changes_student_read on public.law_update_notice_changes for select to authenticated using (exists (select 1 from public.law_update_notice_deliveries d join public.alunos a on a.id=d.student_id where d.notice_id=notice_id and a.user_id=auth.uid()));
revoke all on function public.record_law_update_notice_event(bigint,text,text,jsonb),public.publish_law_update_notice(uuid),public.claim_law_update_notice_resend(uuid),public.finish_law_update_notice_resend(uuid,boolean,integer,text) from public,anon,authenticated;
grant execute on function public.record_law_update_notice_event(bigint,text,text,jsonb),public.publish_law_update_notice(uuid),public.claim_law_update_notice_resend(uuid),public.finish_law_update_notice_resend(uuid,boolean,integer,text) to service_role;
commit;
