begin;

create table if not exists public.hotmart_eventos (
  id bigint generated by default as identity primary key,
  identificador_evento text not null,
  codigo_transacao text,
  hotmart_product_id text,
  tipo_evento text,
  status_transacao text,
  email_comprador text,
  payload_bruto jsonb not null,
  payload_normalizado jsonb not null,
  recebido_em timestamptz not null default pg_catalog.now(),
  constraint hotmart_eventos_identificador_evento_key unique (identificador_evento)
);

create index if not exists hotmart_eventos_codigo_transacao_idx
  on public.hotmart_eventos (codigo_transacao) where codigo_transacao is not null;
create index if not exists hotmart_eventos_recebido_em_idx
  on public.hotmart_eventos (recebido_em desc);

alter table public.hotmart_eventos enable row level security;
revoke all on public.hotmart_eventos from public, anon, authenticated;
revoke all on sequence public.hotmart_eventos_id_seq from public, anon, authenticated;
grant select, insert on public.hotmart_eventos to service_role;
grant usage, select on sequence public.hotmart_eventos_id_seq to service_role;

comment on table public.hotmart_eventos is
  'Eventos recebidos da Hotmart para auditoria e processamento posterior. A recepção não cria compras ou acessos.';

commit;
