-- Estrutura de persistência do LegisBot 2 (Supabase/PostgreSQL).

do $$
begin
  create type public.legisbot_comentario_status as enum (
    'pendente',
    'processando',
    'concluido',
    'erro'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.legisbot_comentarios (
  id bigint generated by default as identity primary key,
  slug varchar(50) not null,
  ordem varchar(20) not null,
  titulo varchar(255) not null,
  assunto varchar(255) not null,
  legislacao text not null,
  comentario text,
  status public.legisbot_comentario_status not null default 'pendente',
  modelo_ia varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint legisbot_comentarios_slug_ordem_unique unique (slug, ordem),
  constraint legisbot_comentarios_slug_not_blank check (btrim(slug) <> ''),
  constraint legisbot_comentarios_ordem_not_blank check (btrim(ordem) <> ''),
  constraint legisbot_comentarios_titulo_not_blank check (btrim(titulo) <> ''),
  constraint legisbot_comentarios_assunto_not_blank check (btrim(assunto) <> ''),
  constraint legisbot_comentarios_legislacao_not_blank check (btrim(legislacao) <> '')
);

-- Mantidos separadamente conforme a especificação. A restrição UNIQUE acima
-- também cria um índice composto para consultas por slug + ordem.
create index if not exists legisbot_comentarios_slug_idx
  on public.legisbot_comentarios (slug);

create index if not exists legisbot_comentarios_status_idx
  on public.legisbot_comentarios (status);

create or replace function public.set_legisbot_comentarios_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_legisbot_comentarios_updated_at
  on public.legisbot_comentarios;

create trigger set_legisbot_comentarios_updated_at
before update on public.legisbot_comentarios
for each row
execute function public.set_legisbot_comentarios_updated_at();

alter table public.legisbot_comentarios enable row level security;

drop policy if exists "Ler comentarios concluidos do LegisBot"
  on public.legisbot_comentarios;
create policy "Ler comentarios concluidos do LegisBot"
  on public.legisbot_comentarios
  for select
  to anon, authenticated
  using (status = 'concluido');

drop policy if exists "Criar solicitacoes pendentes do LegisBot"
  on public.legisbot_comentarios;
create policy "Criar solicitacoes pendentes do LegisBot"
  on public.legisbot_comentarios
  for insert
  to anon, authenticated
  with check (
    status = 'pendente'
    and comentario is null
    and modelo_ia is null
  );

comment on table public.legisbot_comentarios is
  'Comentários gerados pelo LegisBot, identificados exclusivamente por slug e ordem.';
comment on column public.legisbot_comentarios.ordem is
  'Identificador textual do trecho; zeros e pontuação devem ser preservados.';
comment on column public.legisbot_comentarios.comentario is
  'Resposta formatada gerada pela IA; pode conter texto ou HTML sanitizado.';

