begin;

create table if not exists public.editais_personalizados_alunos (
  id bigint generated by default as identity primary key,
  aluno_id uuid not null references public.alunos(id) on delete cascade,
  nome text not null default 'Meu Edital',
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint editais_personalizados_alunos_aluno_key unique (aluno_id),
  constraint editais_personalizados_alunos_nome_check check (pg_catalog.length(pg_catalog.btrim(nome)) between 1 and 80)
);

create table if not exists public.editais_personalizados_leis (
  edital_id bigint not null references public.editais_personalizados_alunos(id) on delete cascade,
  lei_id bigint not null references public.leis(id) on delete restrict,
  ordem integer not null,
  created_at timestamptz not null default pg_catalog.now(),
  primary key (edital_id, lei_id),
  constraint editais_personalizados_leis_ordem_check check (ordem >= 0),
  constraint editais_personalizados_leis_ordem_key unique (edital_id, ordem)
);

create index if not exists editais_personalizados_leis_ordem_idx on public.editais_personalizados_leis (edital_id, ordem, lei_id);

do $do$
begin
  if not exists (select 1 from pg_catalog.pg_trigger where tgrelid='public.editais_personalizados_alunos'::pg_catalog.regclass and tgname='editais_personalizados_alunos_updated_at') then
    create trigger editais_personalizados_alunos_updated_at before update on public.editais_personalizados_alunos for each row execute function public.definir_updated_at();
  end if;
end;
$do$;

alter table public.editais_personalizados_alunos enable row level security;
alter table public.editais_personalizados_leis enable row level security;
revoke all on public.editais_personalizados_alunos, public.editais_personalizados_leis from public, anon, authenticated;
revoke all on sequence public.editais_personalizados_alunos_id_seq from public, anon, authenticated;
grant all on public.editais_personalizados_alunos, public.editais_personalizados_leis to service_role;
grant usage, select, update on sequence public.editais_personalizados_alunos_id_seq to service_role;

create or replace function public.meu_edital_id()
returns bigint language plpgsql security definer set search_path=pg_catalog as $function$
declare v_aluno uuid; v_id bigint;
begin
  select id into v_aluno from public.alunos where user_id=auth.uid();
  if v_aluno is null then raise exception using errcode='42501', message='Aluno nao autenticado.'; end if;
  insert into public.editais_personalizados_alunos(aluno_id) values(v_aluno)
    on conflict(aluno_id) do update set nome=public.editais_personalizados_alunos.nome
    returning id into v_id;
  return v_id;
end;
$function$;

create or replace function public.obter_meus_editais()
returns jsonb language sql stable security definer set search_path=pg_catalog as $function$
  with aluno as (select id from public.alunos where user_id=auth.uid()),
  personalizado as (select e.id,e.nome from public.editais_personalizados_alunos e join aluno a on a.id=e.aluno_id),
  progresso as (select p.lei_id,p.em_estudo,p.questoes_finalizadas from public.progresso_leis_alunos p join aluno a on a.id=p.aluno_id),
  meu as (
    select jsonb_build_object('id',coalesce((select id from personalizado limit 1),0),'tipo','personalizado','nome',coalesce((select nome from personalizado limit 1),'Meu Edital'),'leis',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'slug',l.slug,'titulo',l.titulo,'ordem',pl.ordem,'em_estudo',coalesce(pr.em_estudo,false),'revisao',coalesce(pr.questoes_finalizadas,false)) order by pl.ordem,l.id) from personalizado p join public.editais_personalizados_leis pl on pl.edital_id=p.id join public.leis l on l.id=pl.lei_id and l.ativo=true left join progresso pr on pr.lei_id=l.id),'[]'::jsonb)) as item
  ),
  produtos as (
    select jsonb_build_object('id',p.id::text,'tipo','produto','nome',p.nome,'leis',coalesce(jsonb_agg(jsonb_build_object('id',l.id,'slug',l.slug,'titulo',l.titulo,'ordem',pl.ordem,'em_estudo',coalesce(pr.em_estudo,false),'revisao',coalesce(pr.questoes_finalizadas,false)) order by pl.ordem,l.id),'[]'::jsonb)) as item
    from public.produtos p join public.produto_leis pl on pl.produto_id=p.id join public.leis l on l.id=pl.lei_id and l.ativo=true left join progresso pr on pr.lei_id=l.id
    where p.tipo_produto='edital' and p.ativo=true and exists(select 1 from public.liberacoes_leis r join aluno a on a.id=r.aluno_id where r.produto_id=p.id and r.status='ativo')
    group by p.id,p.nome,p.ordem
  )
  select jsonb_build_object('editais',coalesce((select jsonb_agg(item order by pos) from (select 0 pos,item from meu union all select 1,item from produtos) x),'[]'::jsonb));
$function$;

create or replace function public.atualizar_nome_meu_edital(p_nome text)
returns text language plpgsql security definer set search_path=pg_catalog as $function$
declare v_nome text; v_id bigint;
begin
  v_nome:=pg_catalog.btrim(coalesce(p_nome,''));
  if pg_catalog.length(v_nome) not between 1 and 80 then raise exception using errcode='22023',message='Nome do edital invalido.'; end if;
  v_id:=public.meu_edital_id(); update public.editais_personalizados_alunos set nome=v_nome where id=v_id; return v_nome;
end;
$function$;

create or replace function public.adicionar_lei_meu_edital(p_lei_id bigint)
returns void language plpgsql security definer set search_path=pg_catalog as $function$
declare v_id bigint;
begin
  v_id:=public.meu_edital_id();
  if not exists(select 1 from public.liberacoes_leis r join public.alunos a on a.id=r.aluno_id where a.user_id=auth.uid() and r.lei_id=p_lei_id and r.status='ativo') then raise exception using errcode='42501',message='Lei nao liberada.'; end if;
  insert into public.editais_personalizados_leis(edital_id,lei_id,ordem) select v_id,p_lei_id,coalesce(max(ordem)+1,0) from public.editais_personalizados_leis where edital_id=v_id on conflict(edital_id,lei_id) do nothing;
end;
$function$;

create or replace function public.remover_lei_meu_edital(p_lei_id bigint)
returns void language plpgsql security definer set search_path=pg_catalog as $function$
declare v_id bigint;
begin v_id:=public.meu_edital_id(); delete from public.editais_personalizados_leis where edital_id=v_id and lei_id=p_lei_id; end;
$function$;

create or replace function public.reordenar_meu_edital(p_leis bigint[])
returns void language plpgsql security definer set search_path=pg_catalog as $function$
declare v_id bigint; v_total integer; v_base integer;
begin
  v_id:=public.meu_edital_id();
  select count(*) into v_total from public.editais_personalizados_leis where edital_id=v_id;
  if p_leis is null or cardinality(p_leis)<>v_total or (select count(distinct x) from unnest(p_leis) x)<>v_total or exists(select 1 from unnest(p_leis) x where not exists(select 1 from public.editais_personalizados_leis where edital_id=v_id and lei_id=x)) then raise exception using errcode='22023',message='Ordem do edital invalida.'; end if;
  if v_total=0 then return; end if;
  select coalesce(max(ordem),-1)+v_total+1 into v_base from public.editais_personalizados_leis where edital_id=v_id;
  update public.editais_personalizados_leis set ordem=v_base+ordem where edital_id=v_id;
  update public.editais_personalizados_leis e set ordem=s.ordem from (select x as lei_id,ord::integer-1 as ordem from unnest(p_leis) with ordinality as t(x,ord)) s where e.edital_id=v_id and e.lei_id=s.lei_id;
end;
$function$;

revoke all on function public.meu_edital_id(), public.obter_meus_editais(), public.atualizar_nome_meu_edital(text), public.adicionar_lei_meu_edital(bigint), public.remover_lei_meu_edital(bigint), public.reordenar_meu_edital(bigint[]) from public,anon,authenticated,service_role;
grant execute on function public.obter_meus_editais(), public.atualizar_nome_meu_edital(text), public.adicionar_lei_meu_edital(bigint), public.remover_lei_meu_edital(bigint), public.reordenar_meu_edital(bigint[]) to authenticated;
commit;
