begin;

-- O reset preserva tentativas já respondidas para observabilidade, sem
-- tratá-las como concluídas ou como a campanha ativa do aluno.
alter table public.campanhas_leis_alunos
  add column if not exists abandonada boolean not null default false;
drop index if exists public.campanhas_leis_alunos_ativa_unica_idx;
create unique index if not exists campanhas_leis_alunos_ativa_unica_idx
  on public.campanhas_leis_alunos (aluno_id, lei_id)
  where not concluida and not abandonada;

-- Histórico observável e imutável de respostas. `respondido_em` é o instante
-- semântico da resposta, não o `updated_at` mutável da campanha ou do nível.
create table if not exists public.campanhas_leis_respostas (
  id bigint generated by default as identity primary key,
  campanha_id uuid not null references public.campanhas_leis_alunos(id) on delete cascade,
  nivel_id bigint not null references public.campanhas_leis_niveis(id) on delete cascade,
  questao_id text not null,
  correta boolean not null,
  chave_idempotencia uuid not null,
  unique (campanha_id, chave_idempotencia),
  respondido_em timestamptz not null default now()
);

create index if not exists campanhas_leis_respostas_campanha_respondido_idx
  on public.campanhas_leis_respostas (campanha_id, respondido_em desc, id desc);

alter table public.campanhas_leis_respostas enable row level security;
revoke all on public.campanhas_leis_respostas from public, anon, authenticated;
revoke all on sequence public.campanhas_leis_respostas_id_seq from public, anon, authenticated;
grant select, insert on public.campanhas_leis_respostas to service_role;
grant usage, select on sequence public.campanhas_leis_respostas_id_seq to service_role;

comment on table public.campanhas_leis_respostas is 'Histórico de cada resposta do Estudo Ativo da Lei.';
comment on column public.campanhas_leis_respostas.respondido_em is 'Momento UTC em que o aluno respondeu a questão.';

-- A assinatura anterior não pode continuar aceitando respostas sem criar evento.
drop function if exists public.registrar_resposta_campanha(uuid,bigint,text,boolean,integer,jsonb,integer,boolean);

create or replace function public.registrar_resposta_campanha(
  p_campanha_id uuid,
  p_nivel_id bigint,
  p_questao_id text,
  p_correta boolean,
  p_chave_idempotencia uuid,
  p_proxima_posicao integer,
  p_proximas_pendencias jsonb,
  p_total_erros_nivel integer,
  p_conclui_nivel boolean
)
returns table(score_competitivo_acertos integer,score_competitivo_erros integer,score integer)
language plpgsql security definer set search_path=public as $$
declare
  v_nivel public.campanhas_leis_niveis;
  v_campanha public.campanhas_leis_alunos;
  v_esperada text;
begin
  select * into v_campanha
  from public.campanhas_leis_alunos as c
  where c.id=p_campanha_id and c.score_version=2
  for update;
  if not found then raise exception using errcode='P0001',message='Campanha não está apta para score competitivo.'; end if;

  if exists (select 1 from public.campanhas_leis_respostas as r where r.campanha_id=p_campanha_id and r.chave_idempotencia=p_chave_idempotencia) then
    score_competitivo_acertos:=v_campanha.score_competitivo_acertos;
    score_competitivo_erros:=v_campanha.score_competitivo_erros;
    score:=v_campanha.score;
    return next;
    return;
  end if;
  if v_campanha.concluida then raise exception using errcode='P0001',message='Campanha não está apta para score competitivo.'; end if;

  select * into v_nivel
  from public.campanhas_leis_niveis as n
  where n.id=p_nivel_id and n.campanha_id=p_campanha_id and not concluido
  for update;
  if not found then raise exception using errcode='P0001',message='Nível atual foi atualizado.'; end if;

  v_esperada:=case when v_nivel.proxima_posicao<jsonb_array_length(v_nivel.questoes_ids) then v_nivel.questoes_ids->>v_nivel.proxima_posicao else v_nivel.pendencias_ids->>0 end;
  if v_esperada is distinct from p_questao_id then raise exception using errcode='P0001',message='Questão atual foi atualizada.'; end if;

  insert into public.campanhas_leis_respostas(campanha_id,nivel_id,questao_id,correta,chave_idempotencia)
  values(p_campanha_id,p_nivel_id,p_questao_id,p_correta,p_chave_idempotencia);

  update public.campanhas_leis_niveis as n
  set proxima_posicao=p_proxima_posicao,
      pendencias_ids=p_proximas_pendencias,
      total_erros=p_total_erros_nivel,
      score_competitivo_acertos=n.score_competitivo_acertos+case when p_correta then 1 else 0 end,
      score_competitivo_erros=n.score_competitivo_erros+case when p_correta then 0 else 1 end,
      concluido=p_conclui_nivel
  where n.id=p_nivel_id;

  update public.campanhas_leis_alunos as c
  set score_competitivo_acertos=c.score_competitivo_acertos+case when p_correta then 1 else 0 end,
      score_competitivo_erros=c.score_competitivo_erros+case when p_correta then 0 else 1 end,
      score=greatest(0,(c.score_competitivo_acertos+case when p_correta then 1 else 0 end)*5-(c.score_competitivo_erros+case when p_correta then 0 else 1 end)),
      score_competitivo_atualizado_em=case when c.score is distinct from greatest(0,(c.score_competitivo_acertos+case when p_correta then 1 else 0 end)*5-(c.score_competitivo_erros+case when p_correta then 0 else 1 end)) then now() else c.score_competitivo_atualizado_em end
  where c.id=p_campanha_id
  returning c.score_competitivo_acertos,c.score_competitivo_erros,c.score
  into score_competitivo_acertos,score_competitivo_erros,score;

  return next;
end;$$;

revoke all on function public.registrar_resposta_campanha(uuid,bigint,text,boolean,uuid,integer,jsonb,integer,boolean) from public,anon,authenticated;
grant execute on function public.registrar_resposta_campanha(uuid,bigint,text,boolean,uuid,integer,jsonb,integer,boolean) to service_role;

commit;
