begin;

alter table public.leis
  add column if not exists norma_originaria_referencia text,
  add column if not exists norma_originaria_data date,
  add column if not exists houve_alteracao_legislativa boolean not null default false,
  add column if not exists ultima_alteracao_referencia text,
  add column if not exists ultima_alteracao_data date,
  add column if not exists situacao_atualizacao text not null default 'revisao_pendente';

do $do$
begin
  if not exists (select 1 from pg_catalog.pg_constraint where conrelid='public.leis'::pg_catalog.regclass and conname='leis_norma_originaria_coerente_check') then
    alter table public.leis add constraint leis_norma_originaria_coerente_check check (
      norma_originaria_referencia is null or pg_catalog.btrim(norma_originaria_referencia)<>''
    );
  end if;
  if not exists (select 1 from pg_catalog.pg_constraint where conrelid='public.leis'::pg_catalog.regclass and conname='leis_ultima_alteracao_coerente_check') then
    alter table public.leis add constraint leis_ultima_alteracao_coerente_check check (
      (houve_alteracao_legislativa=false and ultima_alteracao_referencia is null and ultima_alteracao_data is null)
      or (houve_alteracao_legislativa=true and ultima_alteracao_referencia is not null and pg_catalog.btrim(ultima_alteracao_referencia)<>'' and ultima_alteracao_data is not null)
    );
  end if;
  if not exists (select 1 from pg_catalog.pg_constraint where conrelid='public.leis'::pg_catalog.regclass and conname='leis_situacao_atualizacao_check') then
    alter table public.leis add constraint leis_situacao_atualizacao_check check (
      situacao_atualizacao in ('atualizado','revisao_pendente','desatualizado','em_revisao')
    );
  end if;
end;
$do$;

alter table public.materiais_leis
  add column if not exists quantidade_itens integer,
  add column if not exists versao_material text,
  add column if not exists revisado_em date,
  add column if not exists publicado_em date,
  add column if not exists observacao_interna text;

do $do$
begin
  if not exists (select 1 from pg_catalog.pg_constraint where conrelid='public.materiais_leis'::pg_catalog.regclass and conname='materiais_leis_quantidade_itens_check') then
    alter table public.materiais_leis add constraint materiais_leis_quantidade_itens_check check (quantidade_itens is null or quantidade_itens>=0);
  end if;
  if not exists (select 1 from pg_catalog.pg_constraint where conrelid='public.materiais_leis'::pg_catalog.regclass and conname='materiais_leis_versao_material_check') then
    alter table public.materiais_leis add constraint materiais_leis_versao_material_check check (versao_material is null or pg_catalog.btrim(versao_material)<>'');
  end if;
end;
$do$;

create table if not exists public.historico_atualizacoes_leis (
  id bigint generated by default as identity primary key,
  lei_id bigint not null,
  material_lei_id bigint,
  tipo text not null,
  importancia text not null,
  titulo text not null,
  descricao_resumida text,
  referencia_normativa text,
  data_referencia_normativa date,
  versao_anterior text,
  versao_nova text,
  quantidade_flashcards_anterior integer,
  quantidade_flashcards_nova integer,
  quantidade_questoes_adicionadas integer,
  quantidade_questoes_corrigidas integer,
  quantidade_flashcards_revisados integer,
  visivel_aluno boolean not null default true,
  visivel_catalogo boolean not null default false,
  observacao_interna text,
  criado_por uuid,
  data_publicacao timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint historico_atualizacoes_leis_lei_id_fkey foreign key (lei_id) references public.leis(id) on delete restrict,
  constraint historico_atualizacoes_leis_material_lei_id_fkey foreign key (material_lei_id) references public.materiais_leis(id) on delete restrict,
  constraint historico_atualizacoes_leis_criado_por_fkey foreign key (criado_por) references auth.users(id) on delete set null,
  constraint historico_atualizacoes_leis_tipo_check check (tipo in ('alteracao_legislativa','nova_versao_flashcards','novas_questoes','correcao_questoes','correcao_flashcards','melhoria_material','outro')),
  constraint historico_atualizacoes_leis_importancia_check check (importancia in ('informativa','recomendada','essencial')),
  constraint historico_atualizacoes_leis_titulo_check check (pg_catalog.btrim(titulo)<>''),
  constraint historico_atualizacoes_leis_referencia_check check (
    referencia_normativa is null or pg_catalog.btrim(referencia_normativa)<>''
  ),
  constraint historico_atualizacoes_leis_quantidades_check check (
    (quantidade_flashcards_anterior is null or quantidade_flashcards_anterior>=0)
    and (quantidade_flashcards_nova is null or quantidade_flashcards_nova>=0)
    and (quantidade_questoes_adicionadas is null or quantidade_questoes_adicionadas>=0)
    and (quantidade_questoes_corrigidas is null or quantidade_questoes_corrigidas>=0)
    and (quantidade_flashcards_revisados is null or quantidade_flashcards_revisados>=0)
  )
);

create index if not exists historico_atualizacoes_leis_lei_publicacao_idx on public.historico_atualizacoes_leis(lei_id,data_publicacao desc nulls last,created_at desc);
create index if not exists historico_atualizacoes_leis_material_idx on public.historico_atualizacoes_leis(material_lei_id) where material_lei_id is not null;
create index if not exists historico_atualizacoes_leis_visivel_aluno_idx on public.historico_atualizacoes_leis(lei_id,created_at desc) where visivel_aluno=true;
create index if not exists historico_atualizacoes_leis_visivel_catalogo_idx on public.historico_atualizacoes_leis(lei_id,created_at desc) where visivel_catalogo=true;

do $do$
begin
  if not exists (select 1 from pg_catalog.pg_trigger where tgrelid='public.historico_atualizacoes_leis'::pg_catalog.regclass and tgname='historico_atualizacoes_leis_definir_updated_at') then
    create trigger historico_atualizacoes_leis_definir_updated_at before update on public.historico_atualizacoes_leis for each row execute function public.definir_updated_at();
  end if;
end;
$do$;

alter table public.historico_atualizacoes_leis enable row level security;
revoke all on public.historico_atualizacoes_leis from public,anon,authenticated,service_role;
revoke all on sequence public.historico_atualizacoes_leis_id_seq from public,anon,authenticated,service_role;
grant select,insert,update on public.historico_atualizacoes_leis to service_role;
grant usage,select,update on sequence public.historico_atualizacoes_leis_id_seq to service_role;

create or replace view public.resumo_editorial_leis
with (security_barrier=true,security_invoker=true)
as
select
  lei.id as lei_id,
  lei.situacao_atualizacao,
  lei.norma_originaria_referencia,
  lei.norma_originaria_data,
  lei.houve_alteracao_legislativa,
  lei.ultima_alteracao_referencia,
  lei.ultima_alteracao_data,
  coalesce(pg_catalog.sum(material.quantidade_itens) filter (where material.ativo=true and material.tipo='flashcards' and material.quantidade_itens is not null),0)::bigint as quantidade_flashcards,
  (pg_catalog.array_agg(material.versao_material order by material.revisado_em desc nulls last,material.publicado_em desc nulls last,material.id desc) filter (where material.ativo=true and material.tipo='flashcards' and material.versao_material is not null))[1] as versao_material,
  pg_catalog.max(material.revisado_em) filter (where material.ativo=true and material.tipo='flashcards') as revisado_em
from public.leis as lei
left join public.materiais_leis as material on material.lei_id=lei.id
group by lei.id;

revoke all on public.resumo_editorial_leis from public,anon,authenticated,service_role;
grant select on public.resumo_editorial_leis to service_role;

-- Sobrecarga editorial: preserva a assinatura anterior para compatibilidade.
create or replace function public.admin_criar_lei(
  p_ator_user_id uuid,p_slug text,p_titulo text,p_nome_curto text,p_descricao text,p_codigo text,p_categoria text,
  p_ativo boolean,p_ordem integer,p_thumbnail_url text,p_norma_originaria_referencia text,p_norma_originaria_data date,
  p_houve_alteracao_legislativa boolean,p_ultima_alteracao_referencia text,p_ultima_alteracao_data date,p_situacao_atualizacao text
) returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_row public.leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_slug is null or p_slug!~'^[a-z0-9]+(-[a-z0-9]+)*$' or p_titulo is null or pg_catalog.btrim(p_titulo)='' or p_ordem is null or p_ordem<0 then raise exception using errcode='22023',message='Dados da lei invalidos.'; end if;
  insert into public.leis(slug,titulo,nome_curto,descricao,codigo,categoria,ativo,ordem,thumbnail_url,norma_originaria_referencia,norma_originaria_data,houve_alteracao_legislativa,ultima_alteracao_referencia,ultima_alteracao_data,situacao_atualizacao)
  values(p_slug,pg_catalog.btrim(p_titulo),p_nome_curto,p_descricao,p_codigo,p_categoria,p_ativo,p_ordem,p_thumbnail_url,p_norma_originaria_referencia,p_norma_originaria_data,p_houve_alteracao_legislativa,p_ultima_alteracao_referencia,p_ultima_alteracao_data,p_situacao_atualizacao)
  returning * into v_row;
  perform public.admin_comercial_auditar(p_ator_user_id,'criar','lei',v_row.id::text,null,pg_catalog.to_jsonb(v_row));
  return pg_catalog.to_jsonb(v_row);
end;
$function$;

create or replace function public.admin_atualizar_lei(p_ator_user_id uuid,p_lei_id bigint,p_dados jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_before public.leis;v_after public.leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_dados is null or p_dados='{}'::jsonb or p_dados-array['slug','titulo','nome_curto','descricao','codigo','categoria','ativo','ordem','thumbnail_url','norma_originaria_referencia','norma_originaria_data','houve_alteracao_legislativa','ultima_alteracao_referencia','ultima_alteracao_data','situacao_atualizacao']<>'{}'::jsonb then raise exception using errcode='22023',message='Campos da lei invalidos.'; end if;
  select * into v_before from public.leis where id=p_lei_id for update;
  if not found then raise exception using errcode='P0002',message='Lei nao encontrada.'; end if;
  update public.leis set
    slug=case when p_dados?'slug' then p_dados->>'slug' else slug end,
    titulo=case when p_dados?'titulo' then pg_catalog.btrim(p_dados->>'titulo') else titulo end,
    nome_curto=case when p_dados?'nome_curto' then nullif(p_dados->>'nome_curto','') else nome_curto end,
    descricao=case when p_dados?'descricao' then nullif(p_dados->>'descricao','') else descricao end,
    codigo=case when p_dados?'codigo' then nullif(p_dados->>'codigo','') else codigo end,
    categoria=case when p_dados?'categoria' then nullif(p_dados->>'categoria','') else categoria end,
    ativo=case when p_dados?'ativo' then (p_dados->>'ativo')::boolean else ativo end,
    ordem=case when p_dados?'ordem' then (p_dados->>'ordem')::integer else ordem end,
    thumbnail_url=case when p_dados?'thumbnail_url' then nullif(p_dados->>'thumbnail_url','') else thumbnail_url end,
    norma_originaria_referencia=case when p_dados?'norma_originaria_referencia' then nullif(p_dados->>'norma_originaria_referencia','') else norma_originaria_referencia end,
    norma_originaria_data=case when p_dados?'norma_originaria_data' then nullif(p_dados->>'norma_originaria_data','')::date else norma_originaria_data end,
    houve_alteracao_legislativa=case when p_dados?'houve_alteracao_legislativa' then (p_dados->>'houve_alteracao_legislativa')::boolean else houve_alteracao_legislativa end,
    ultima_alteracao_referencia=case when p_dados?'ultima_alteracao_referencia' then nullif(p_dados->>'ultima_alteracao_referencia','') else ultima_alteracao_referencia end,
    ultima_alteracao_data=case when p_dados?'ultima_alteracao_data' then nullif(p_dados->>'ultima_alteracao_data','')::date else ultima_alteracao_data end,
    situacao_atualizacao=case when p_dados?'situacao_atualizacao' then p_dados->>'situacao_atualizacao' else situacao_atualizacao end
  where id=p_lei_id returning * into v_after;
  perform public.admin_comercial_auditar(p_ator_user_id,'atualizar','lei',p_lei_id::text,pg_catalog.to_jsonb(v_before),pg_catalog.to_jsonb(v_after));
  return pg_catalog.to_jsonb(v_after);
end;
$function$;

create or replace function public.admin_criar_material_lei(
  p_ator_user_id uuid,p_lei_id bigint,p_tipo text,p_titulo text,p_descricao text,p_provedor text,p_url_externa text,p_acao text,p_ordem integer,p_ativo boolean,
  p_quantidade_itens integer,p_versao_material text,p_revisado_em date,p_publicado_em date,p_observacao_interna text
) returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_row public.materiais_leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if not exists(select 1 from public.leis where id=p_lei_id) or p_tipo not in ('flashcards','video','pdf','tutorial','audio','outro') or p_provedor not in ('google_drive','youtube','externo','supabase_storage') or p_acao not in ('abrir','baixar','assistir') or p_titulo is null or pg_catalog.btrim(p_titulo)='' or p_url_externa is null or pg_catalog.btrim(p_url_externa)='' or p_ordem is null or p_ordem<0 then raise exception using errcode='22023',message='Dados do material invalidos.'; end if;
  insert into public.materiais_leis(lei_id,tipo,titulo,descricao,provedor,url_externa,acao,ordem,ativo,quantidade_itens,versao_material,revisado_em,publicado_em,observacao_interna)
  values(p_lei_id,p_tipo,pg_catalog.btrim(p_titulo),p_descricao,p_provedor,pg_catalog.btrim(p_url_externa),p_acao,p_ordem,p_ativo,p_quantidade_itens,p_versao_material,p_revisado_em,p_publicado_em,p_observacao_interna)
  returning * into v_row;
  perform public.admin_comercial_auditar(p_ator_user_id,'criar','material_lei',v_row.id::text,null,pg_catalog.to_jsonb(v_row));
  return pg_catalog.to_jsonb(v_row);
end;
$function$;

create or replace function public.admin_atualizar_material_lei(p_ator_user_id uuid,p_material_id bigint,p_dados jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_before public.materiais_leis;v_after public.materiais_leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_dados is null or p_dados='{}'::jsonb or p_dados-array['tipo','titulo','descricao','provedor','url_externa','acao','ordem','ativo','quantidade_itens','versao_material','revisado_em','publicado_em','observacao_interna']<>'{}'::jsonb then raise exception using errcode='22023',message='Campos do material invalidos.'; end if;
  select * into v_before from public.materiais_leis where id=p_material_id for update;
  if not found then raise exception using errcode='P0002',message='Material nao encontrado.'; end if;
  update public.materiais_leis set
    tipo=case when p_dados?'tipo' then p_dados->>'tipo' else tipo end,
    titulo=case when p_dados?'titulo' then pg_catalog.btrim(p_dados->>'titulo') else titulo end,
    descricao=case when p_dados?'descricao' then nullif(p_dados->>'descricao','') else descricao end,
    provedor=case when p_dados?'provedor' then p_dados->>'provedor' else provedor end,
    url_externa=case when p_dados?'url_externa' then pg_catalog.btrim(p_dados->>'url_externa') else url_externa end,
    acao=case when p_dados?'acao' then p_dados->>'acao' else acao end,
    ordem=case when p_dados?'ordem' then (p_dados->>'ordem')::integer else ordem end,
    ativo=case when p_dados?'ativo' then (p_dados->>'ativo')::boolean else ativo end,
    quantidade_itens=case when p_dados?'quantidade_itens' then nullif(p_dados->>'quantidade_itens','')::integer else quantidade_itens end,
    versao_material=case when p_dados?'versao_material' then nullif(p_dados->>'versao_material','') else versao_material end,
    revisado_em=case when p_dados?'revisado_em' then nullif(p_dados->>'revisado_em','')::date else revisado_em end,
    publicado_em=case when p_dados?'publicado_em' then nullif(p_dados->>'publicado_em','')::date else publicado_em end,
    observacao_interna=case when p_dados?'observacao_interna' then nullif(p_dados->>'observacao_interna','') else observacao_interna end
  where id=p_material_id returning * into v_after;
  perform public.admin_comercial_auditar(p_ator_user_id,'atualizar','material_lei',p_material_id::text,pg_catalog.to_jsonb(v_before),pg_catalog.to_jsonb(v_after));
  return pg_catalog.to_jsonb(v_after);
end;
$function$;

create or replace function public.admin_criar_atualizacao_lei(
  p_ator_user_id uuid,p_lei_id bigint,p_material_lei_id bigint,p_tipo text,p_importancia text,p_titulo text,p_descricao_resumida text,
  p_referencia_normativa text,p_data_referencia_normativa date,p_versao_anterior text,p_versao_nova text,p_quantidade_flashcards_anterior integer,
  p_quantidade_flashcards_nova integer,p_quantidade_questoes_adicionadas integer,p_quantidade_questoes_corrigidas integer,p_quantidade_flashcards_revisados integer,
  p_visivel_aluno boolean,p_visivel_catalogo boolean,p_observacao_interna text,p_data_publicacao timestamptz
) returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_row public.historico_atualizacoes_leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_material_lei_id is not null and not exists(select 1 from public.materiais_leis where id=p_material_lei_id and lei_id=p_lei_id) then raise exception using errcode='22023',message='Material nao pertence a lei.'; end if;
  insert into public.historico_atualizacoes_leis(lei_id,material_lei_id,tipo,importancia,titulo,descricao_resumida,referencia_normativa,data_referencia_normativa,versao_anterior,versao_nova,quantidade_flashcards_anterior,quantidade_flashcards_nova,quantidade_questoes_adicionadas,quantidade_questoes_corrigidas,quantidade_flashcards_revisados,visivel_aluno,visivel_catalogo,observacao_interna,criado_por,data_publicacao)
  values(p_lei_id,p_material_lei_id,p_tipo,p_importancia,pg_catalog.btrim(p_titulo),p_descricao_resumida,p_referencia_normativa,p_data_referencia_normativa,p_versao_anterior,p_versao_nova,p_quantidade_flashcards_anterior,p_quantidade_flashcards_nova,p_quantidade_questoes_adicionadas,p_quantidade_questoes_corrigidas,p_quantidade_flashcards_revisados,p_visivel_aluno,p_visivel_catalogo,p_observacao_interna,p_ator_user_id,p_data_publicacao)
  returning * into v_row;
  perform public.admin_comercial_auditar(p_ator_user_id,'criar','atualizacao_lei',v_row.id::text,null,pg_catalog.to_jsonb(v_row));
  return pg_catalog.to_jsonb(v_row);
end;
$function$;

create or replace function public.admin_atualizar_atualizacao_lei(p_ator_user_id uuid,p_atualizacao_id bigint,p_dados jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_before public.historico_atualizacoes_leis;v_after public.historico_atualizacoes_leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_dados is null or p_dados='{}'::jsonb or p_dados-array['material_lei_id','tipo','importancia','titulo','descricao_resumida','referencia_normativa','data_referencia_normativa','versao_anterior','versao_nova','quantidade_flashcards_anterior','quantidade_flashcards_nova','quantidade_questoes_adicionadas','quantidade_questoes_corrigidas','quantidade_flashcards_revisados','visivel_aluno','visivel_catalogo','observacao_interna','data_publicacao']<>'{}'::jsonb then raise exception using errcode='22023',message='Campos da atualizacao invalidos.'; end if;
  select * into v_before from public.historico_atualizacoes_leis where id=p_atualizacao_id for update;
  if not found then raise exception using errcode='P0002',message='Atualizacao nao encontrada.'; end if;
  update public.historico_atualizacoes_leis set
    material_lei_id=case when p_dados?'material_lei_id' then nullif(p_dados->>'material_lei_id','')::bigint else material_lei_id end,
    tipo=case when p_dados?'tipo' then p_dados->>'tipo' else tipo end,
    importancia=case when p_dados?'importancia' then p_dados->>'importancia' else importancia end,
    titulo=case when p_dados?'titulo' then pg_catalog.btrim(p_dados->>'titulo') else titulo end,
    descricao_resumida=case when p_dados?'descricao_resumida' then nullif(p_dados->>'descricao_resumida','') else descricao_resumida end,
    referencia_normativa=case when p_dados?'referencia_normativa' then nullif(p_dados->>'referencia_normativa','') else referencia_normativa end,
    data_referencia_normativa=case when p_dados?'data_referencia_normativa' then nullif(p_dados->>'data_referencia_normativa','')::date else data_referencia_normativa end,
    versao_anterior=case when p_dados?'versao_anterior' then nullif(p_dados->>'versao_anterior','') else versao_anterior end,
    versao_nova=case when p_dados?'versao_nova' then nullif(p_dados->>'versao_nova','') else versao_nova end,
    quantidade_flashcards_anterior=case when p_dados?'quantidade_flashcards_anterior' then nullif(p_dados->>'quantidade_flashcards_anterior','')::integer else quantidade_flashcards_anterior end,
    quantidade_flashcards_nova=case when p_dados?'quantidade_flashcards_nova' then nullif(p_dados->>'quantidade_flashcards_nova','')::integer else quantidade_flashcards_nova end,
    quantidade_questoes_adicionadas=case when p_dados?'quantidade_questoes_adicionadas' then nullif(p_dados->>'quantidade_questoes_adicionadas','')::integer else quantidade_questoes_adicionadas end,
    quantidade_questoes_corrigidas=case when p_dados?'quantidade_questoes_corrigidas' then nullif(p_dados->>'quantidade_questoes_corrigidas','')::integer else quantidade_questoes_corrigidas end,
    quantidade_flashcards_revisados=case when p_dados?'quantidade_flashcards_revisados' then nullif(p_dados->>'quantidade_flashcards_revisados','')::integer else quantidade_flashcards_revisados end,
    visivel_aluno=case when p_dados?'visivel_aluno' then (p_dados->>'visivel_aluno')::boolean else visivel_aluno end,
    visivel_catalogo=case when p_dados?'visivel_catalogo' then (p_dados->>'visivel_catalogo')::boolean else visivel_catalogo end,
    observacao_interna=case when p_dados?'observacao_interna' then nullif(p_dados->>'observacao_interna','') else observacao_interna end,
    data_publicacao=case when p_dados?'data_publicacao' then nullif(p_dados->>'data_publicacao','')::timestamptz else data_publicacao end
  where id=p_atualizacao_id returning * into v_after;
  if v_after.material_lei_id is not null and not exists(select 1 from public.materiais_leis where id=v_after.material_lei_id and lei_id=v_after.lei_id) then raise exception using errcode='22023',message='Material nao pertence a lei.'; end if;
  perform public.admin_comercial_auditar(p_ator_user_id,'atualizar','atualizacao_lei',p_atualizacao_id::text,pg_catalog.to_jsonb(v_before),pg_catalog.to_jsonb(v_after));
  return pg_catalog.to_jsonb(v_after);
end;
$function$;

create or replace function public.admin_ocultar_atualizacao_lei(p_ator_user_id uuid,p_atualizacao_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_before public.historico_atualizacoes_leis;v_after public.historico_atualizacoes_leis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  select * into v_before from public.historico_atualizacoes_leis where id=p_atualizacao_id for update;
  if not found then raise exception using errcode='P0002',message='Atualizacao nao encontrada.'; end if;
  update public.historico_atualizacoes_leis set visivel_aluno=false,visivel_catalogo=false where id=p_atualizacao_id returning * into v_after;
  perform public.admin_comercial_auditar(p_ator_user_id,'ocultar','atualizacao_lei',p_atualizacao_id::text,pg_catalog.to_jsonb(v_before),pg_catalog.to_jsonb(v_after));
  return pg_catalog.to_jsonb(v_after);
end;
$function$;

create or replace function public.admin_publicar_nova_versao_material(
  p_ator_user_id uuid,p_material_lei_id bigint,p_nova_url_externa text,p_nova_versao text,p_nova_quantidade_itens integer,p_revisado_em date,p_publicado_em date,
  p_tipo_atualizacao text,p_importancia text,p_titulo text,p_descricao_resumida text,p_referencia_normativa text,p_data_referencia_normativa date,
  p_quantidade_questoes_adicionadas integer,p_quantidade_questoes_corrigidas integer,p_quantidade_flashcards_revisados integer,p_visivel_aluno boolean,p_visivel_catalogo boolean,p_observacao_interna text
) returns jsonb language plpgsql security definer set search_path=pg_catalog
as $function$
declare v_before public.materiais_leis;v_after public.materiais_leis;v_history jsonb;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  select * into v_before from public.materiais_leis where id=p_material_lei_id and tipo='flashcards' for update;
  if not found then raise exception using errcode='P0002',message='Material de flashcards nao encontrado.'; end if;
  if p_nova_url_externa is null or pg_catalog.btrim(p_nova_url_externa)='' or p_nova_versao is null or pg_catalog.btrim(p_nova_versao)='' or p_nova_quantidade_itens is null or p_nova_quantidade_itens<0 or p_revisado_em is null or p_publicado_em is null then raise exception using errcode='22023',message='Dados da nova versao invalidos.'; end if;
  update public.materiais_leis set url_externa=pg_catalog.btrim(p_nova_url_externa),versao_material=pg_catalog.btrim(p_nova_versao),quantidade_itens=p_nova_quantidade_itens,revisado_em=p_revisado_em,publicado_em=p_publicado_em,observacao_interna=p_observacao_interna,ativo=true where id=p_material_lei_id returning * into v_after;
  v_history:=public.admin_criar_atualizacao_lei(p_ator_user_id,v_before.lei_id,p_material_lei_id,p_tipo_atualizacao,p_importancia,p_titulo,p_descricao_resumida,p_referencia_normativa,p_data_referencia_normativa,v_before.versao_material,v_after.versao_material,v_before.quantidade_itens,v_after.quantidade_itens,p_quantidade_questoes_adicionadas,p_quantidade_questoes_corrigidas,p_quantidade_flashcards_revisados,p_visivel_aluno,p_visivel_catalogo,p_observacao_interna,pg_catalog.now());
  perform public.admin_comercial_auditar(p_ator_user_id,'publicar_versao','material_lei',p_material_lei_id::text,pg_catalog.to_jsonb(v_before),pg_catalog.to_jsonb(v_after),pg_catalog.jsonb_build_object('atualizacao_id',v_history->>'id','substitui_versao_anterior',true,'incremental',false));
  return pg_catalog.jsonb_build_object('material',pg_catalog.to_jsonb(v_after),'atualizacao',v_history);
end;
$function$;

do $do$
declare v_function pg_catalog.regprocedure;
begin
  for v_function in select p.oid::pg_catalog.regprocedure from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=any(array['admin_criar_lei','admin_atualizar_lei','admin_criar_material_lei','admin_atualizar_material_lei','admin_criar_atualizacao_lei','admin_atualizar_atualizacao_lei','admin_ocultar_atualizacao_lei','admin_publicar_nova_versao_material'])
  loop
    execute pg_catalog.format('revoke all on function %s from public, anon, authenticated',v_function);
    execute pg_catalog.format('grant execute on function %s to service_role',v_function);
  end loop;
end;
$do$;

comment on table public.historico_atualizacoes_leis is 'Historico editorial relevante para aluno e catalogo, separado da auditoria administrativa tecnica.';
comment on column public.materiais_leis.observacao_interna is 'Informacao administrativa privada, nunca exposta ao aluno ou catalogo.';
comment on function public.admin_publicar_nova_versao_material(uuid,bigint,text,text,integer,date,date,text,text,text,text,text,date,integer,integer,integer,boolean,boolean,text) is 'Substitui atomicamente o arquivo vigente e registra historico editorial e auditoria; nao realiza merge incremental de Anki.';

commit;
