begin;

-- Estrutura comercial interna oficial. O catalogo continua sem criar compras.
-- public.aluno_produtos permanece legada e nao integra a nova fonte de verdade.

create or replace function public.definir_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $function$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$function$;

revoke all on function public.definir_updated_at() from public, anon, authenticated;
grant execute on function public.definir_updated_at() to service_role;

create table if not exists public.leis (
  id bigint generated by default as identity primary key,
  slug text not null,
  titulo text not null,
  nome_curto text,
  descricao text,
  codigo text,
  categoria text,
  ativo boolean not null default true,
  ordem integer not null default 0,
  thumbnail_url text,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint leis_slug_normalizado_check check (
    slug = pg_catalog.lower(pg_catalog.btrim(slug))
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
  ),
  constraint leis_titulo_nao_vazio_check check (pg_catalog.btrim(titulo) <> ''),
  constraint leis_ordem_check check (ordem >= 0),
  constraint leis_slug_key unique (slug)
);

create index if not exists leis_ativo_ordem_idx
  on public.leis (ativo, ordem, id);
create index if not exists leis_categoria_idx
  on public.leis (categoria) where categoria is not null;

create table if not exists public.materiais_leis (
  id bigint generated by default as identity primary key,
  lei_id bigint not null,
  tipo text not null,
  titulo text not null,
  descricao text,
  provedor text not null default 'google_drive',
  url_externa text not null,
  acao text not null default 'abrir',
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint materiais_leis_lei_id_fkey
    foreign key (lei_id) references public.leis(id) on delete restrict,
  constraint materiais_leis_tipo_check check (
    tipo in ('flashcards', 'video', 'pdf', 'tutorial', 'audio', 'outro')
  ),
  constraint materiais_leis_provedor_check check (
    provedor in ('google_drive', 'youtube', 'externo', 'supabase_storage')
  ),
  constraint materiais_leis_acao_check check (
    acao in ('abrir', 'baixar', 'assistir')
  ),
  constraint materiais_leis_titulo_nao_vazio_check check (pg_catalog.btrim(titulo) <> ''),
  constraint materiais_leis_url_nao_vazia_check check (pg_catalog.btrim(url_externa) <> ''),
  constraint materiais_leis_ordem_check check (ordem >= 0)
);

create index if not exists materiais_leis_lei_ativo_ordem_idx
  on public.materiais_leis (lei_id, ativo, ordem, id);
create index if not exists materiais_leis_provedor_idx
  on public.materiais_leis (provedor);
create index if not exists materiais_leis_tipo_idx
  on public.materiais_leis (tipo);

-- public.produtos usa UUID como chave primaria no schema existente.
alter table public.produtos
  add column if not exists slug text,
  add column if not exists descricao text,
  add column if not exists hotmart_url text,
  add column if not exists observacao_administrativa text,
  add column if not exists ordem integer not null default 0,
  add column if not exists tipo_produto text not null default 'outro',
  add column if not exists updated_at timestamptz not null default pg_catalog.now();

alter table public.produtos
  alter column hotmart_product_id drop not null;

do $do$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.produtos'::pg_catalog.regclass
      and conname = 'produtos_slug_normalizado_check'
  ) then
    alter table public.produtos add constraint produtos_slug_normalizado_check
      check (
        slug is null
        or (
          slug = pg_catalog.lower(pg_catalog.btrim(slug))
          and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
        )
      );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.produtos'::pg_catalog.regclass
      and conname = 'produtos_tipo_produto_check'
  ) then
    alter table public.produtos add constraint produtos_tipo_produto_check
      check (tipo_produto in ('lei_avulsa', 'combo', 'edital', 'assinatura', 'outro'));
  end if;

  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.produtos'::pg_catalog.regclass
      and conname = 'produtos_ordem_check'
  ) then
    alter table public.produtos add constraint produtos_ordem_check check (ordem >= 0);
  end if;
end;
$do$;

create unique index if not exists produtos_slug_unique_idx
  on public.produtos (slug) where slug is not null;
create index if not exists produtos_ativo_ordem_idx
  on public.produtos (ativo, ordem, id);
create index if not exists produtos_tipo_produto_idx
  on public.produtos (tipo_produto);

create table if not exists public.produto_leis (
  produto_id uuid not null,
  lei_id bigint not null,
  ordem integer not null default 0,
  created_at timestamptz not null default pg_catalog.now(),
  constraint produto_leis_pkey primary key (produto_id, lei_id),
  constraint produto_leis_produto_id_fkey
    foreign key (produto_id) references public.produtos(id) on delete restrict,
  constraint produto_leis_lei_id_fkey
    foreign key (lei_id) references public.leis(id) on delete restrict,
  constraint produto_leis_ordem_check check (ordem >= 0)
);

create index if not exists produto_leis_produto_ordem_idx
  on public.produto_leis (produto_id, ordem, lei_id);
create index if not exists produto_leis_lei_idx
  on public.produto_leis (lei_id);

-- public.compras continua preservando os campos Hotmart antigos por compatibilidade.
alter table public.compras
  add column if not exists origem text not null default 'hotmart',
  add column if not exists identificador_externo text,
  add column if not exists observacao_administrativa text,
  add column if not exists administrador_user_id uuid,
  add column if not exists status_acesso text,
  add column if not exists adquirida_em timestamptz,
  add column if not exists cancelada_em timestamptz,
  add column if not exists reembolsada_em timestamptz,
  add column if not exists reativada_em timestamptz,
  add column if not exists updated_at timestamptz not null default pg_catalog.now();

alter table public.compras
  alter column hotmart_product_id drop not null;

update public.compras
set identificador_externo = hotmart_transaction_id
where identificador_externo is null
  and hotmart_transaction_id is not null;

update public.compras
set adquirida_em = comprada_em
where adquirida_em is null
  and comprada_em is not null;

update public.compras
set status_acesso = case
  when status in ('aprovada', 'manual') then 'ativo'
  when status in ('cancelada', 'chargeback') then 'cancelado'
  when status = 'reembolsada' then 'reembolsado'
  else null
end
where status_acesso is null;

do $do$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.compras'::pg_catalog.regclass
      and conname = 'compras_origem_check'
  ) then
    alter table public.compras add constraint compras_origem_check check (
      origem in ('hotmart', 'cortesia', 'amostra', 'premiacao', 'migracao', 'administrativo')
    );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.compras'::pg_catalog.regclass
      and conname = 'compras_status_acesso_check'
  ) then
    alter table public.compras add constraint compras_status_acesso_check check (
      status_acesso is null or status_acesso in ('ativo', 'cancelado', 'reembolsado')
    );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.compras'::pg_catalog.regclass
      and conname = 'compras_administrador_user_id_fkey'
  ) then
    alter table public.compras add constraint compras_administrador_user_id_fkey
      foreign key (administrador_user_id) references auth.users(id) on delete set null;
  end if;
end;
$do$;

create unique index if not exists compras_origem_identificador_unique_idx
  on public.compras (origem, identificador_externo)
  where identificador_externo is not null;
create index if not exists compras_status_acesso_idx
  on public.compras (status_acesso);
create index if not exists compras_origem_idx
  on public.compras (origem);
create index if not exists compras_adquirida_em_idx
  on public.compras (adquirida_em desc);

create table if not exists public.liberacoes_leis (
  id bigint generated by default as identity primary key,
  aluno_id uuid not null,
  lei_id bigint not null,
  compra_id uuid,
  produto_id uuid,
  origem text not null,
  status text not null default 'ativo',
  motivo text,
  concedida_por uuid,
  concedida_em timestamptz not null default pg_catalog.now(),
  revogada_por uuid,
  revogada_em timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint liberacoes_leis_aluno_id_fkey
    foreign key (aluno_id) references public.alunos(id) on delete restrict,
  constraint liberacoes_leis_lei_id_fkey
    foreign key (lei_id) references public.leis(id) on delete restrict,
  constraint liberacoes_leis_compra_id_fkey
    foreign key (compra_id) references public.compras(id) on delete restrict,
  constraint liberacoes_leis_produto_id_fkey
    foreign key (produto_id) references public.produtos(id) on delete restrict,
  constraint liberacoes_leis_concedida_por_fkey
    foreign key (concedida_por) references auth.users(id) on delete set null,
  constraint liberacoes_leis_revogada_por_fkey
    foreign key (revogada_por) references auth.users(id) on delete set null,
  constraint liberacoes_leis_origem_check check (
    origem in ('produto', 'hotmart', 'cortesia', 'amostra', 'premiacao', 'migracao', 'administrativo')
  ),
  constraint liberacoes_leis_status_check check (
    status in ('ativo', 'revogado', 'cancelado', 'reembolsado')
  ),
  constraint liberacoes_leis_revogada_em_check check (
    status <> 'revogado' or revogada_em is not null
  )
);

create unique index if not exists liberacoes_leis_compra_lei_unique_idx
  on public.liberacoes_leis (compra_id, lei_id)
  where compra_id is not null;
create unique index if not exists liberacoes_leis_individual_ativa_unique_idx
  on public.liberacoes_leis (aluno_id, lei_id, origem)
  where status = 'ativo' and compra_id is null and produto_id is null;
create index if not exists liberacoes_leis_aluno_lei_status_idx
  on public.liberacoes_leis (aluno_id, lei_id, status);
create index if not exists liberacoes_leis_compra_idx
  on public.liberacoes_leis (compra_id) where compra_id is not null;
create index if not exists liberacoes_leis_produto_idx
  on public.liberacoes_leis (produto_id) where produto_id is not null;
create index if not exists liberacoes_leis_concedida_em_idx
  on public.liberacoes_leis (concedida_em desc);
create index if not exists liberacoes_leis_revogada_em_idx
  on public.liberacoes_leis (revogada_em desc) where revogada_em is not null;

create table if not exists public.auditoria_administrativa (
  id bigint generated by default as identity primary key,
  ator_user_id uuid,
  acao text not null,
  entidade text not null,
  entidade_id text,
  estado_anterior jsonb,
  estado_posterior jsonb,
  detalhes jsonb,
  created_at timestamptz not null default pg_catalog.now(),
  constraint auditoria_administrativa_ator_user_id_fkey
    foreign key (ator_user_id) references auth.users(id) on delete set null,
  constraint auditoria_administrativa_acao_nao_vazia_check
    check (pg_catalog.btrim(acao) <> ''),
  constraint auditoria_administrativa_entidade_nao_vazia_check
    check (pg_catalog.btrim(entidade) <> '')
);

create index if not exists auditoria_administrativa_ator_idx
  on public.auditoria_administrativa (ator_user_id) where ator_user_id is not null;
create index if not exists auditoria_administrativa_entidade_idx
  on public.auditoria_administrativa (entidade, entidade_id);
create index if not exists auditoria_administrativa_acao_idx
  on public.auditoria_administrativa (acao);
create index if not exists auditoria_administrativa_created_at_idx
  on public.auditoria_administrativa (created_at desc);

do $do$
begin
  if not exists (
    select 1 from pg_catalog.pg_trigger
    where tgrelid = 'public.leis'::pg_catalog.regclass
      and tgname = 'leis_definir_updated_at'
      and not tgisinternal
  ) then
    create trigger leis_definir_updated_at
      before update on public.leis
      for each row execute function public.definir_updated_at();
  end if;

  if not exists (
    select 1 from pg_catalog.pg_trigger
    where tgrelid = 'public.materiais_leis'::pg_catalog.regclass
      and tgname = 'materiais_leis_definir_updated_at'
      and not tgisinternal
  ) then
    create trigger materiais_leis_definir_updated_at
      before update on public.materiais_leis
      for each row execute function public.definir_updated_at();
  end if;

  if not exists (
    select 1 from pg_catalog.pg_trigger
    where tgrelid = 'public.produtos'::pg_catalog.regclass
      and tgname = 'produtos_definir_updated_at'
      and not tgisinternal
  ) then
    create trigger produtos_definir_updated_at
      before update on public.produtos
      for each row execute function public.definir_updated_at();
  end if;

  if not exists (
    select 1 from pg_catalog.pg_trigger
    where tgrelid = 'public.compras'::pg_catalog.regclass
      and tgname = 'compras_definir_updated_at'
      and not tgisinternal
  ) then
    create trigger compras_definir_updated_at
      before update on public.compras
      for each row execute function public.definir_updated_at();
  end if;

  if not exists (
    select 1 from pg_catalog.pg_trigger
    where tgrelid = 'public.liberacoes_leis'::pg_catalog.regclass
      and tgname = 'liberacoes_leis_definir_updated_at'
      and not tgisinternal
  ) then
    create trigger liberacoes_leis_definir_updated_at
      before update on public.liberacoes_leis
      for each row execute function public.definir_updated_at();
  end if;
end;
$do$;

alter table public.leis enable row level security;
alter table public.materiais_leis enable row level security;
alter table public.produto_leis enable row level security;
alter table public.liberacoes_leis enable row level security;
alter table public.auditoria_administrativa enable row level security;

-- Mantem somente as leituras de transicao ja existentes em produtos.
drop policy if exists "DEV permitir cadastro publico de produtos" on public.produtos;
drop policy if exists "DEV permitir edicao publica de produtos" on public.produtos;
revoke insert, update, delete, truncate, references, trigger
  on public.produtos, public.compras from public, anon, authenticated;

-- Novos objetos nao possuem policies para anon ou authenticated.
revoke all on public.leis,
  public.materiais_leis,
  public.produto_leis,
  public.liberacoes_leis,
  public.auditoria_administrativa
from public, anon, authenticated;

revoke all on sequence public.leis_id_seq,
  public.materiais_leis_id_seq,
  public.liberacoes_leis_id_seq,
  public.auditoria_administrativa_id_seq
from public, anon, authenticated;

grant all privileges on public.leis,
  public.materiais_leis,
  public.produto_leis,
  public.liberacoes_leis
to service_role;

revoke all on public.auditoria_administrativa from service_role;
grant select, insert on public.auditoria_administrativa to service_role;

grant usage, select, update on sequence public.leis_id_seq,
  public.materiais_leis_id_seq,
  public.liberacoes_leis_id_seq,
  public.auditoria_administrativa_id_seq
to service_role;

create or replace view public.acessos_efetivos_leis
with (security_barrier = true, security_invoker = true)
as
select distinct
  liberacao.aluno_id,
  liberacao.lei_id
from public.liberacoes_leis as liberacao
where liberacao.status = 'ativo';

revoke all on public.acessos_efetivos_leis from public, anon, authenticated;
revoke all on public.acessos_efetivos_leis from service_role;
grant select on public.acessos_efetivos_leis to service_role;

-- Preserva o historico comercial quando um usuario Auth for excluido.
alter table public.alunos alter column user_id drop not null;

do $do$
declare
  tipo_exclusao "char";
begin
  select constraint_definition.confdeltype
  into tipo_exclusao
  from pg_catalog.pg_constraint as constraint_definition
  where constraint_definition.conrelid = 'public.alunos'::pg_catalog.regclass
    and constraint_definition.conname = 'alunos_user_id_fkey';

  if tipo_exclusao is distinct from 'n' then
    alter table public.alunos drop constraint if exists alunos_user_id_fkey;
    alter table public.alunos add constraint alunos_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete set null;
  end if;
end;
$do$;

create or replace function public.criar_aluno_para_usuario()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $function$
begin
  insert into public.alunos (user_id, nome, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', new.raw_user_meta_data ->> 'name'),
    new.email
  )
  on conflict (user_id) do update
    set nome = coalesce(public.alunos.nome, excluded.nome),
        email = excluded.email,
        atualizado_em = pg_catalog.now();

  return new;
end;
$function$;

revoke all on function public.criar_aluno_para_usuario() from public, anon, authenticated;
grant execute on function public.criar_aluno_para_usuario() to service_role;

comment on table public.aluno_produtos is
  'Tabela legada, vazia e fora da arquitetura comercial interna oficial. Preservada temporariamente para compatibilidade.';
comment on column public.produtos.slug_opcional is
  'Campo legado preservado. Novos cadastros devem usar public.produtos.slug.';
comment on column public.compras.hotmart_product_id is
  'Campo Hotmart legado, preservado e opcional para aquisicoes sem origem Hotmart.';
comment on column public.compras.hotmart_transaction_id is
  'Identificador Hotmart legado, preservado para compatibilidade.';
comment on column public.compras.hotmart_evento_id is
  'Vinculo legado com public.hotmart_eventos, preservado para compatibilidade.';
comment on view public.acessos_efetivos_leis is
  'Acesso efetivo quando ao menos uma fonte de liberacao permanece ativa. Sem campos administrativos.';

commit;
