begin;

-- Vínculos complementares não alteram o dispositivo principal da questão.
create table if not exists public.question_supporting_devices (
  id bigint generated by default as identity primary key,
  question_id uuid not null references public.questions(id) on delete cascade,
  lei_id bigint not null references public.leis(id) on delete restrict,
  slug text not null check (btrim(slug) <> ''),
  ordem text not null check (btrim(ordem) <> ''),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (question_id, slug, ordem)
);
create index if not exists question_supporting_devices_lookup_idx on public.question_supporting_devices (lei_id, slug, ordem);

-- A aprovação pertence à versão de legislação revisada, preservando decisões antigas.
create table if not exists public.question_intentional_combinations (
  id bigint generated by default as identity primary key,
  question_id uuid not null references public.questions(id) on delete cascade,
  legislation_signature text not null check (btrim(legislation_signature) <> ''),
  justification text not null check (btrim(justification) <> ''),
  supporting_snapshot jsonb not null default '[]'::jsonb,
  decided_by uuid references auth.users(id) on delete set null,
  decided_at timestamptz not null default now(),
  invalidated_at timestamptz,
  invalidated_reason text
);
create unique index if not exists question_intentional_combinations_active_idx
  on public.question_intentional_combinations(question_id) where invalidated_at is null;

create table if not exists public.article_legislative_updates (
  id uuid primary key default gen_random_uuid(),
  lei_id bigint not null references public.leis(id) on delete restrict,
  slug text not null check (btrim(slug) <> ''),
  ordem text not null check (btrim(ordem) <> ''),
  status text not null default 'pendente' check (status in ('pendente','em_revisao','concluida')),
  observacao_interna text,
  observacao_publica text,
  marcado_por uuid references auth.users(id) on delete set null,
  marcado_em timestamptz not null default now(),
  concluido_por uuid references auth.users(id) on delete set null,
  concluido_em timestamptz,
  reaberto_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists article_legislative_updates_open_idx
  on public.article_legislative_updates(lei_id, slug, ordem) where status <> 'concluida';
create index if not exists article_legislative_updates_context_idx
  on public.article_legislative_updates(lei_id, slug, ordem, marcado_em desc);

create table if not exists public.article_legislative_update_steps (
  update_id uuid not null references public.article_legislative_updates(id) on delete cascade,
  step text not null check (step in ('legislacao','questoes','mapeamento','materiais')),
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  primary key (update_id, step)
);

do $do$
begin
  if not exists (select 1 from pg_trigger where tgrelid='public.article_legislative_updates'::regclass and tgname='article_legislative_updates_updated_at') then
    create trigger article_legislative_updates_updated_at before update on public.article_legislative_updates for each row execute function public.definir_updated_at();
  end if;
end;
$do$;

alter table public.question_supporting_devices enable row level security;
alter table public.question_intentional_combinations enable row level security;
alter table public.article_legislative_updates enable row level security;
alter table public.article_legislative_update_steps enable row level security;
revoke all on public.question_supporting_devices, public.question_intentional_combinations, public.article_legislative_updates, public.article_legislative_update_steps from public, anon, authenticated;
grant select, insert, update, delete on public.question_supporting_devices, public.question_intentional_combinations, public.article_legislative_updates, public.article_legislative_update_steps to service_role;
grant usage, select, update on sequence public.question_supporting_devices_id_seq, public.question_intentional_combinations_id_seq to service_role;

commit;
