begin;

create table if not exists public.progresso_leis_alunos (
  id bigint generated by default as identity primary key,
  aluno_id uuid not null,
  lei_id bigint not null,
  em_estudo boolean not null default false,
  questoes_finalizadas boolean not null default false,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint progresso_leis_alunos_aluno_id_fkey
    foreign key (aluno_id) references public.alunos(id) on delete cascade,
  constraint progresso_leis_alunos_lei_id_fkey
    foreign key (lei_id) references public.leis(id) on delete cascade,
  constraint progresso_leis_alunos_aluno_lei_key unique (aluno_id, lei_id),
  constraint progresso_leis_alunos_estado_coerente_check
    check (not questoes_finalizadas or em_estudo)
);

create index if not exists progresso_leis_alunos_lei_idx
  on public.progresso_leis_alunos (lei_id, aluno_id);

do $do$
begin
  if not exists (
    select 1
    from pg_catalog.pg_trigger
    where tgrelid = 'public.progresso_leis_alunos'::pg_catalog.regclass
      and tgname = 'progresso_leis_alunos_definir_updated_at'
  ) then
    create trigger progresso_leis_alunos_definir_updated_at
      before update on public.progresso_leis_alunos
      for each row execute function public.definir_updated_at();
  end if;
end;
$do$;

alter table public.progresso_leis_alunos enable row level security;

revoke all on public.progresso_leis_alunos from public, anon, authenticated, service_role;
revoke all on sequence public.progresso_leis_alunos_id_seq from public, anon, authenticated, service_role;
grant select, insert, update, delete on public.progresso_leis_alunos to service_role;
grant usage, select, update on sequence public.progresso_leis_alunos_id_seq to service_role;

comment on table public.progresso_leis_alunos is
  'Marcacoes privadas de progresso por aluno e lei. O acesso da aplicacao ocorre somente no servidor apos validar sessao e liberacao ativa.';

commit;
