begin;

-- Conteúdo de questões unificado: a lei comercial existente é a única fonte de identidade.
create table if not exists public.law_structure (
  id bigint generated by default as identity primary key,
  lei_id bigint not null references public.leis(id) on delete cascade,
  parent_id bigint references public.law_structure(id) on delete cascade,
  tipo text not null check (tipo in ('titulo', 'capitulo', 'secao', 'subsecao')),
  nome text not null check (btrim(nome) <> ''),
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  lei_id bigint not null references public.leis(id) on delete cascade,
  structure_id bigint references public.law_structure(id) on delete set null,
  pergunta text not null check (btrim(pergunta) <> ''),
  resposta text not null check (resposta in ('Certo', 'Errado')),
  justificativa text,
  assunto text,
  legislacao text,
  ordem text not null check (ordem ~ '^\d+(?:\.\d+)*$'),
  titulo text,
  total_artigos integer check (total_artigos is null or total_artigos >= 0),
  slug text not null check (slug ~ '^[a-z0-9-]{1,160}$'),
  ultima_alteracao_legislativa text,
  capitulo text,
  secao text,
  subsecao text,
  artigo text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint questions_slug_matches_law_not_enforced_note check (btrim(slug) <> '')
);

create index if not exists law_structure_lei_id_idx on public.law_structure (lei_id);
create index if not exists law_structure_parent_id_idx on public.law_structure (parent_id);
create index if not exists law_structure_lei_ordem_idx on public.law_structure (lei_id, ordem);
create index if not exists questions_lei_id_idx on public.questions (lei_id);
create index if not exists questions_lei_ordem_idx on public.questions (lei_id, ordem);
create index if not exists questions_structure_id_idx on public.questions (structure_id);

create or replace function public.questions_definir_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists law_structure_definir_updated_at on public.law_structure;
create trigger law_structure_definir_updated_at before update on public.law_structure for each row execute function public.questions_definir_updated_at();
drop trigger if exists questions_definir_updated_at on public.questions;
create trigger questions_definir_updated_at before update on public.questions for each row execute function public.questions_definir_updated_at();

alter table public.law_structure enable row level security;
alter table public.questions enable row level security;
revoke all on public.law_structure, public.questions from public, anon, authenticated;
revoke all on sequence public.law_structure_id_seq from public, anon, authenticated;
grant select, insert, update, delete on public.law_structure, public.questions to service_role;
grant usage, select, update on sequence public.law_structure_id_seq to service_role;

commit;
