begin;

create table if not exists public.campanhas_leis_alunos (
  id uuid primary key default gen_random_uuid(),
  aluno_id uuid not null references public.alunos(id) on delete cascade,
  lei_id bigint not null references public.leis(id) on delete cascade,
  iniciada_em timestamptz not null default now(),
  concluida_em timestamptz,
  total_erros integer not null default 0 check (total_erros >= 0),
  score integer check (score between 0 and 10000),
  concluida boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campanhas_leis_alunos_conclusao_check check (
    (concluida = false and concluida_em is null and score is null)
    or (concluida = true and concluida_em is not null and score is not null)
  )
);

create index if not exists campanhas_leis_alunos_historico_idx
  on public.campanhas_leis_alunos (aluno_id, lei_id, concluida, iniciada_em);
create unique index if not exists campanhas_leis_alunos_ativa_unica_idx
  on public.campanhas_leis_alunos (aluno_id, lei_id) where not concluida;

create table if not exists public.campanhas_leis_niveis (
  id bigint generated by default as identity primary key,
  campanha_id uuid not null references public.campanhas_leis_alunos(id) on delete cascade,
  ordem integer not null check (ordem >= 0),
  chave_origem text not null,
  nome text not null check (btrim(nome) <> ''),
  questoes_ids jsonb not null check (jsonb_typeof(questoes_ids) = 'array'),
  proxima_posicao integer not null default 0 check (proxima_posicao >= 0),
  pendencias_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(pendencias_ids) = 'array'),
  concluido boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campanhas_leis_niveis_campanha_ordem_key unique (campanha_id, ordem)
);
create index if not exists campanhas_leis_niveis_campanha_idx on public.campanhas_leis_niveis (campanha_id, ordem);

create or replace function public.increment_campaign_errors(campaign_id uuid)
returns void language sql security definer set search_path = public as $$
  update public.campanhas_leis_alunos set total_erros = total_erros + 1 where id = campaign_id and not concluida;
$$;
revoke all on function public.increment_campaign_errors(uuid) from public, anon, authenticated;
grant execute on function public.increment_campaign_errors(uuid) to service_role;

alter table public.progresso_leis_alunos
  add column if not exists status_campanha text not null default 'nao_iniciada'
    check (status_campanha in ('nao_iniciada', 'em_andamento', 'concluida')),
  add column if not exists campanha_ativa_id uuid references public.campanhas_leis_alunos(id) on delete set null;
create index if not exists progresso_leis_alunos_campanha_ativa_idx on public.progresso_leis_alunos (campanha_ativa_id);

create or replace function public.campanhas_leis_definir_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists campanhas_leis_alunos_definir_updated_at on public.campanhas_leis_alunos;
create trigger campanhas_leis_alunos_definir_updated_at before update on public.campanhas_leis_alunos for each row execute function public.campanhas_leis_definir_updated_at();
drop trigger if exists campanhas_leis_niveis_definir_updated_at on public.campanhas_leis_niveis;
create trigger campanhas_leis_niveis_definir_updated_at before update on public.campanhas_leis_niveis for each row execute function public.campanhas_leis_definir_updated_at();

alter table public.campanhas_leis_alunos enable row level security;
alter table public.campanhas_leis_niveis enable row level security;
revoke all on public.campanhas_leis_alunos, public.campanhas_leis_niveis from public, anon, authenticated;
revoke all on sequence public.campanhas_leis_niveis_id_seq from public, anon, authenticated;
grant select, insert, update, delete on public.campanhas_leis_alunos, public.campanhas_leis_niveis to service_role;
grant usage, select, update on sequence public.campanhas_leis_niveis_id_seq to service_role;

comment on table public.campanhas_leis_alunos is 'Historico imutavel de tentativas de campanha por aluno e lei.';
comment on table public.campanhas_leis_niveis is 'Snapshot dos niveis, ordem e pendencias da campanha ativa.';

commit;
