create table if not exists public.article_context_mappings (
  id bigint generated by default as identity primary key,
  slug text not null,
  ordem text not null,
  incidencia text not null default 'nao_mapeado' check (incidencia in ('muito_alta','alta','media','baixa','nao_mapeado')),
  artigo_recente boolean not null default false,
  origem_mapeamento text null check (origem_mapeamento in ('questoes_reais','estimativa','analogia','manual','ia')),
  observacao_interna text null,
  confianca numeric null check (confianca is null or (confianca >= 0 and confianca <= 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (slug, ordem)
);
create index if not exists article_context_mappings_slug_idx on public.article_context_mappings (slug, ordem);
alter table public.article_context_mappings enable row level security;
revoke all on public.article_context_mappings from public, anon, authenticated;
grant select, insert, update, delete on public.article_context_mappings to service_role;
