begin;

create table if not exists public.ligas (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  nome text not null,
  titulo text not null,
  imagem_url text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ligas_leis (
  liga_id bigint not null references public.ligas(id) on delete cascade,
  lei_id bigint not null references public.leis(id) on delete restrict,
  ordem integer not null check (ordem >= 0),
  primary key (liga_id, lei_id),
  unique (liga_id, ordem)
);

create index if not exists ligas_leis_lei_idx on public.ligas_leis(lei_id);

alter table public.ligas enable row level security;
alter table public.ligas_leis enable row level security;
revoke all on public.ligas, public.ligas_leis from anon, authenticated;

insert into public.ligas (slug, nome, titulo)
values ('pmma', 'Liga PMMA', 'Ranking Geral de Legislação')
on conflict (slug) do update set nome = excluded.nome, titulo = excluded.titulo, ativo = true;

insert into public.ligas_leis (liga_id, lei_id, ordem)
select liga.id, lei.id, source.ordem
from public.ligas liga
join (values
  ('l6513ma', 0),
  ('l14751', 1),
  ('l12896ma', 2)
) as source(slug, ordem) on true
join public.leis lei on lei.slug = source.slug and lei.ativo = true
where liga.slug = 'pmma'
on conflict (liga_id, lei_id) do update set ordem = excluded.ordem;

create or replace function public.obter_ranking_liga(
  p_liga_slug text,
  p_aluno_id uuid default null,
  p_limite integer default 10
)
returns table(posicao bigint, aluno_id uuid, score_total bigint)
language sql
security definer
set search_path = public, pg_catalog
as $$
  with liga as (
    select id from public.ligas where slug = p_liga_slug and ativo = true
  ), melhores as (
    select c.aluno_id, c.lei_id, max(coalesce(c.score_ajustado, c.score)) as melhor_score
    from public.campanhas_leis_alunos c
    join public.ligas_leis ll on ll.lei_id = c.lei_id
    join liga on liga.id = ll.liga_id
    where c.concluida = true and coalesce(c.score_ajustado, c.score) is not null
    group by c.aluno_id, c.lei_id
  ), melhores_com_data as (
    select m.aluno_id, m.lei_id, m.melhor_score,
      min(c.concluida_em) filter (where coalesce(c.score_ajustado, c.score) = m.melhor_score) as melhor_score_em
    from melhores m
    join public.campanhas_leis_alunos c on c.aluno_id = m.aluno_id and c.lei_id = m.lei_id and c.concluida = true
    group by m.aluno_id, m.lei_id, m.melhor_score
  ), totais as (
    select aluno_id, sum(melhor_score)::bigint as score_total, min(melhor_score_em) as score_total_em
    from melhores_com_data
    group by aluno_id
  ), ordenados as (
    select row_number() over (order by score_total desc, score_total_em asc nulls last, aluno_id asc) as posicao,
      aluno_id, score_total
    from totais
  )
  select posicao, aluno_id, score_total
  from ordenados
  where posicao <= case when p_limite between 1 and 100 then p_limite else 10 end
    or aluno_id = p_aluno_id
  order by posicao;
$$;

revoke all on function public.obter_ranking_liga(text, uuid, integer) from public, anon, authenticated;
grant execute on function public.obter_ranking_liga(text, uuid, integer) to service_role;

commit;
