begin;

-- `ativo` permanece para compatibilidade interna. O estado público é explícito
-- para que "em_breve" não seja confundido com conteúdo inativo.
alter table public.leis add column if not exists status_publicacao text;
update public.leis set status_publicacao=case when ativo then 'ativa' else 'inativa' end where status_publicacao is null;
alter table public.leis alter column status_publicacao set default 'ativa';
alter table public.leis alter column status_publicacao set not null;
alter table public.leis drop constraint if exists leis_status_publicacao_check;
alter table public.leis add constraint leis_status_publicacao_check check (status_publicacao in ('ativa','em_breve','inativa'));

alter table public.recortes_leis add column if not exists status_publicacao text;
update public.recortes_leis set status_publicacao=case when ativo then 'ativa' else 'inativa' end where status_publicacao is null;
alter table public.recortes_leis alter column status_publicacao set default 'ativa';
alter table public.recortes_leis alter column status_publicacao set not null;
alter table public.recortes_leis drop constraint if exists recortes_leis_status_publicacao_check;
alter table public.recortes_leis add constraint recortes_leis_status_publicacao_check check (status_publicacao in ('ativa','em_breve','inativa'));
create index if not exists leis_status_publicacao_idx on public.leis(status_publicacao,ordem,id);
create index if not exists recortes_leis_status_publicacao_idx on public.recortes_leis(lei_id,status_publicacao,nome);

create or replace function public.admin_atualizar_lei(p_ator_user_id uuid,p_lei_id bigint,p_dados jsonb)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare v_before public.leis; v_after public.leis; v_status text;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_dados is null or p_dados='{}'::jsonb or p_dados-array['slug','titulo','nome_curto','descricao','codigo','categoria','ativo','status_publicacao','acesso_gratuito','ordem','thumbnail_url','norma_originaria_referencia','norma_originaria_data','houve_alteracao_legislativa','ultima_alteracao_referencia','ultima_alteracao_data','situacao_atualizacao']<>'{}'::jsonb then raise exception using errcode='22023',message='Campos da lei invalidos.'; end if;
  select * into v_before from public.leis where id=p_lei_id for update;
  if not found then raise exception using errcode='P0002',message='Lei nao encontrada.'; end if;
  v_status:=case when p_dados?'status_publicacao' then p_dados->>'status_publicacao' when p_dados?'ativo' then case when (p_dados->>'ativo')::boolean then 'ativa' else 'inativa' end else v_before.status_publicacao end;
  if v_status not in ('ativa','em_breve','inativa') then raise exception using errcode='22023',message='Status de publicacao invalido.'; end if;
  update public.leis set slug=case when p_dados?'slug' then p_dados->>'slug' else slug end,titulo=case when p_dados?'titulo' then pg_catalog.btrim(p_dados->>'titulo') else titulo end,nome_curto=case when p_dados?'nome_curto' then nullif(p_dados->>'nome_curto','') else nome_curto end,descricao=case when p_dados?'descricao' then nullif(p_dados->>'descricao','') else descricao end,codigo=case when p_dados?'codigo' then nullif(p_dados->>'codigo','') else codigo end,categoria=case when p_dados?'categoria' then nullif(p_dados->>'categoria','') else categoria end,status_publicacao=v_status,ativo=(v_status<>'inativa'),acesso_gratuito=case when p_dados?'acesso_gratuito' then (p_dados->>'acesso_gratuito')::boolean else acesso_gratuito end,ordem=case when p_dados?'ordem' then (p_dados->>'ordem')::integer else ordem end,thumbnail_url=case when p_dados?'thumbnail_url' then nullif(p_dados->>'thumbnail_url','') else thumbnail_url end,norma_originaria_referencia=case when p_dados?'norma_originaria_referencia' then nullif(p_dados->>'norma_originaria_referencia','') else norma_originaria_referencia end,norma_originaria_data=case when p_dados?'norma_originaria_data' then nullif(p_dados->>'norma_originaria_data','')::date else norma_originaria_data end,houve_alteracao_legislativa=case when p_dados?'houve_alteracao_legislativa' then (p_dados->>'houve_alteracao_legislativa')::boolean else houve_alteracao_legislativa end,ultima_alteracao_referencia=case when p_dados?'ultima_alteracao_referencia' then nullif(p_dados->>'ultima_alteracao_referencia','') else ultima_alteracao_referencia end,ultima_alteracao_data=case when p_dados?'ultima_alteracao_data' then nullif(p_dados->>'ultima_alteracao_data','')::date else ultima_alteracao_data end,situacao_atualizacao=case when p_dados?'situacao_atualizacao' then p_dados->>'situacao_atualizacao' else situacao_atualizacao end where id=p_lei_id returning * into v_after;
  perform public.admin_comercial_auditar(p_ator_user_id,'atualizar','lei',p_lei_id::text,pg_catalog.to_jsonb(v_before),pg_catalog.to_jsonb(v_after)); return pg_catalog.to_jsonb(v_after);
end;$function$;

-- Sobrecarga nova; a assinatura antiga continua atendendo código publicado e
-- converte p_ativo para ativa/inativa pela função de atualização/compatibilidade.
create or replace function public.admin_criar_lei(p_ator_user_id uuid,p_slug text,p_titulo text,p_nome_curto text,p_descricao text,p_codigo text,p_categoria text,p_ativo boolean,p_ordem integer,p_thumbnail_url text,p_norma_originaria_referencia text,p_norma_originaria_data date,p_houve_alteracao_legislativa boolean,p_ultima_alteracao_referencia text,p_ultima_alteracao_data date,p_situacao_atualizacao text,p_status_publicacao text)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare v_row public.leis; v_status text:=coalesce(p_status_publicacao,case when p_ativo then 'ativa' else 'inativa' end);
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_slug is null or p_slug!~'^[a-z0-9]+(-[a-z0-9]+)*$' or p_titulo is null or pg_catalog.btrim(p_titulo)='' or p_ordem is null or p_ordem<0 or v_status not in ('ativa','em_breve','inativa') then raise exception using errcode='22023',message='Dados da lei invalidos.'; end if;
  insert into public.leis(slug,titulo,nome_curto,descricao,codigo,categoria,ativo,status_publicacao,ordem,thumbnail_url,norma_originaria_referencia,norma_originaria_data,houve_alteracao_legislativa,ultima_alteracao_referencia,ultima_alteracao_data,situacao_atualizacao) values(p_slug,pg_catalog.btrim(p_titulo),p_nome_curto,p_descricao,p_codigo,p_categoria,v_status<>'inativa',v_status,p_ordem,p_thumbnail_url,p_norma_originaria_referencia,p_norma_originaria_data,p_houve_alteracao_legislativa,p_ultima_alteracao_referencia,p_ultima_alteracao_data,p_situacao_atualizacao) returning * into v_row;
  perform public.admin_comercial_auditar(p_ator_user_id,'criar','lei',v_row.id::text,null,pg_catalog.to_jsonb(v_row)); return pg_catalog.to_jsonb(v_row);
end;$function$;
revoke all on function public.admin_criar_lei(uuid,text,text,text,text,text,text,boolean,integer,text,text,date,boolean,text,date,text,text) from public,anon,authenticated;
grant execute on function public.admin_criar_lei(uuid,text,text,text,text,text,text,boolean,integer,text,text,date,boolean,text,date,text,text) to service_role;
create or replace function public.admin_criar_lei(p_ator_user_id uuid,p_slug text,p_titulo text,p_nome_curto text,p_descricao text,p_codigo text,p_categoria text,p_ativo boolean,p_ordem integer,p_thumbnail_url text,p_norma_originaria_referencia text,p_norma_originaria_data date,p_houve_alteracao_legislativa boolean,p_ultima_alteracao_referencia text,p_ultima_alteracao_data date,p_situacao_atualizacao text)
returns jsonb language sql security definer set search_path='' as $function$
  select public.admin_criar_lei(p_ator_user_id,p_slug,p_titulo,p_nome_curto,p_descricao,p_codigo,p_categoria,p_ativo,p_ordem,p_thumbnail_url,p_norma_originaria_referencia,p_norma_originaria_data,p_houve_alteracao_legislativa,p_ultima_alteracao_referencia,p_ultima_alteracao_data,p_situacao_atualizacao,case when p_ativo then 'ativa' else 'inativa' end);
$function$;

create or replace function public.admin_salvar_recorte_lei(p_recorte_id uuid,p_lei_id bigint,p_nome text,p_descricao text,p_ativo boolean,p_status_publicacao text,p_structure_ids bigint[])
returns uuid language plpgsql security definer set search_path='' as $function$
declare v_id uuid;v_total integer;v_valid integer;v_status text:=coalesce(p_status_publicacao,case when p_ativo then 'ativa' else 'inativa' end);
begin
  if pg_catalog.btrim(coalesce(p_nome,''))='' or v_status not in ('ativa','em_breve','inativa') then raise exception using errcode='22023',message='Dados do recorte invalidos.'; end if;
  if cardinality(coalesce(p_structure_ids,array[]::bigint[]))=0 then raise exception using errcode='22023',message='Selecione ao menos uma estrutura.'; end if;
  select count(*),count(distinct x) into v_total,v_valid from pg_catalog.unnest(p_structure_ids) x; if v_total<>v_valid then raise exception using errcode='22023',message='Estrutura duplicada no recorte.'; end if;
  select count(*) into v_valid from public.law_structure where lei_id=p_lei_id and ativo and id=any(p_structure_ids); if v_valid<>v_total then raise exception using errcode='22023',message='A estrutura selecionada nao pertence a esta lei.'; end if;
  if p_recorte_id is null then insert into public.recortes_leis(lei_id,nome,descricao,ativo,status_publicacao) values(p_lei_id,pg_catalog.btrim(p_nome),nullif(pg_catalog.btrim(coalesce(p_descricao,'')),''),v_status<>'inativa',v_status) returning id into v_id; else update public.recortes_leis set nome=pg_catalog.btrim(p_nome),descricao=nullif(pg_catalog.btrim(coalesce(p_descricao,'')),''),ativo=v_status<>'inativa',status_publicacao=v_status where id=p_recorte_id and lei_id=p_lei_id returning id into v_id; if v_id is null then raise exception using errcode='P0002',message='Recorte nao encontrado para esta lei.'; end if; delete from public.recortes_leis_estrutura where recorte_id=v_id; end if;
  insert into public.recortes_leis_estrutura(recorte_id,structure_id,lei_id) select v_id,x,p_lei_id from pg_catalog.unnest(p_structure_ids) x; return v_id;
end;$function$;
revoke all on function public.admin_salvar_recorte_lei(uuid,bigint,text,text,boolean,text,bigint[]) from public,anon,authenticated;
grant execute on function public.admin_salvar_recorte_lei(uuid,bigint,text,text,boolean,text,bigint[]) to service_role;

create or replace function public.obter_minhas_leis() returns table (id bigint,slug text,titulo text,nome_curto text,descricao text,codigo text,categoria text,thumbnail_url text,ordem integer,fontes_ativas bigint,total_flashcards bigint,versao_material text,revisado_em date,publicado_em date,situacao_atualizacao text,houve_alteracao_legislativa boolean,referencia_normativa_atual text,tipo_referencia_normativa text) language sql stable security definer set search_path='' as $function$
 with aluno_atual as (select id from public.alunos where user_id=auth.uid()),acessos as (select liberacao.lei_id,count(*)::bigint fontes_ativas from public.liberacoes_leis liberacao join aluno_atual aluno on aluno.id=liberacao.aluno_id where liberacao.status='ativo' group by liberacao.lei_id),visiveis as (select lei.id,coalesce(acessos.fontes_ativas,0::bigint) fontes_ativas from public.leis lei left join acessos on acessos.lei_id=lei.id where lei.ativo=true and lei.status_publicacao='ativa' and exists(select 1 from aluno_atual) and (lei.acesso_gratuito or acessos.lei_id is not null)) select lei.id,lei.slug,lei.titulo,lei.nome_curto,lei.descricao,lei.codigo,lei.categoria,lei.thumbnail_url,lei.ordem,visiveis.fontes_ativas,coalesce(totais.total_flashcards,0::bigint),vigente.versao_material,vigente.revisado_em,vigente.publicado_em,lei.situacao_atualizacao,lei.houve_alteracao_legislativa,case when lei.houve_alteracao_legislativa then lei.ultima_alteracao_referencia else lei.norma_originaria_referencia end,case when lei.houve_alteracao_legislativa then 'alteracao'::text else 'originaria'::text end from visiveis join public.leis lei on lei.id=visiveis.id left join lateral(select coalesce(sum(material.quantidade_itens),0)::bigint total_flashcards from public.materiais_leis material where material.lei_id=lei.id and material.ativo=true and material.tipo='flashcards') totais on true left join lateral(select material.versao_material,material.revisado_em,material.publicado_em from public.materiais_leis material where material.lei_id=lei.id and material.ativo=true and material.tipo='flashcards' order by material.publicado_em desc nulls last,material.revisado_em desc nulls last,material.ordem,material.id desc limit 1) vigente on true order by lei.ordem,lei.titulo,lei.id;$function$;
revoke all on function public.obter_minhas_leis() from public,anon,authenticated,service_role; grant execute on function public.obter_minhas_leis() to authenticated;

create or replace function public.obter_detalhes_records_produto(p_produto_slug text,p_aluno_id uuid default null) returns jsonb language sql security definer set search_path='' as $function$
 with produto as (select id from public.produtos where slug=p_produto_slug and ativo=true and records_enabled=true),leis_produto as (select pl.lei_id,pl.recorte_id,pl.ordem,l.slug,l.titulo,l.status_publicacao lei_status,r.nome recorte_nome,r.status_publicacao recorte_status from produto p join public.produto_leis pl on pl.produto_id=p.id join public.leis l on l.id=pl.lei_id and l.ativo=true and l.status_publicacao in ('ativa','em_breve') left join public.recortes_leis r on r.id=pl.recorte_id and r.lei_id=pl.lei_id and r.ativo=true and r.status_publicacao in ('ativa','em_breve') where pl.recorte_id is null or r.id is not null),melhores as (select c.aluno_id,c.lei_id,max(coalesce(c.score_ajustado,c.score)) melhor_score from public.campanhas_leis_alunos c join leis_produto lp on lp.lei_id=c.lei_id where c.score_version=2 and coalesce(c.score_ajustado,c.score) is not null group by c.aluno_id,c.lei_id),totais as (select aluno_id,sum(melhor_score)::bigint score_total from melhores group by aluno_id),ordenados as (select row_number() over(order by score_total desc,aluno_id asc) posicao,aluno_id,score_total from totais),atual as(select * from ordenados where aluno_id=p_aluno_id) select jsonb_build_object('top10',coalesce((select jsonb_agg(jsonb_build_object('posicao',posicao,'aluno_id',aluno_id,'score_total',score_total) order by posicao) from ordenados where posicao<=10),'[]'::jsonb),'current_user',(select jsonb_build_object('posicao',posicao,'aluno_id',aluno_id,'score_total',score_total) from atual),'nearby','[]'::jsonb,'laws',coalesce((select jsonb_agg(jsonb_build_object('lei_id',lp.lei_id,'slug',lp.slug,'titulo',case when lp.recorte_nome is null then lp.titulo else lp.titulo||' — '||lp.recorte_nome end,'status_publicacao',case when lp.lei_status='em_breve' or lp.recorte_status='em_breve' then 'em_breve' else 'ativa' end,'score',coalesce((select m.melhor_score from melhores m where m.aluno_id=p_aluno_id and m.lei_id=lp.lei_id),0)) order by lp.ordem,lp.lei_id) from leis_produto lp),'[]'::jsonb));$function$;
-- Reaplica a mesma definição preservando também a janela de posições próximas.
create or replace function public.obter_detalhes_records_produto(p_produto_slug text,p_aluno_id uuid default null) returns jsonb language sql security definer set search_path='' as $function$
 with produto as (select id from public.produtos where slug=p_produto_slug and ativo=true and records_enabled=true),leis_produto as (select pl.lei_id,pl.recorte_id,pl.ordem,l.slug,l.titulo,l.status_publicacao lei_status,r.nome recorte_nome,r.status_publicacao recorte_status from produto p join public.produto_leis pl on pl.produto_id=p.id join public.leis l on l.id=pl.lei_id and l.ativo=true and l.status_publicacao in ('ativa','em_breve') left join public.recortes_leis r on r.id=pl.recorte_id and r.lei_id=pl.lei_id and r.ativo=true and r.status_publicacao in ('ativa','em_breve') where pl.recorte_id is null or r.id is not null),melhores as (select c.aluno_id,c.lei_id,max(coalesce(c.score_ajustado,c.score)) melhor_score from public.campanhas_leis_alunos c join leis_produto lp on lp.lei_id=c.lei_id where c.score_version=2 and coalesce(c.score_ajustado,c.score) is not null group by c.aluno_id,c.lei_id),melhores_com_data as (select m.aluno_id,m.lei_id,m.melhor_score,min(c.score_competitivo_atualizado_em) filter(where coalesce(c.score_ajustado,c.score)=m.melhor_score) melhor_score_em from melhores m join public.campanhas_leis_alunos c on c.aluno_id=m.aluno_id and c.lei_id=m.lei_id and c.score_version=2 group by m.aluno_id,m.lei_id,m.melhor_score),totais as (select aluno_id,sum(melhor_score)::bigint score_total,max(melhor_score_em) score_total_em from melhores_com_data group by aluno_id),ordenados as (select row_number() over(order by score_total desc,score_total_em asc nulls last,aluno_id asc) posicao,aluno_id,score_total from totais),atual as(select * from ordenados where aluno_id=p_aluno_id),limites_proximos as(select greatest(1::bigint,least(a.posicao-5,greatest((select count(*) from ordenados)-9,1))) inicio from atual a where a.posicao>10) select jsonb_build_object('top10',coalesce((select jsonb_agg(jsonb_build_object('posicao',posicao,'aluno_id',aluno_id,'score_total',score_total) order by posicao) from ordenados where posicao<=10),'[]'::jsonb),'current_user',(select jsonb_build_object('posicao',posicao,'aluno_id',aluno_id,'score_total',score_total) from atual),'nearby',coalesce((select jsonb_agg(jsonb_build_object('posicao',o.posicao,'aluno_id',o.aluno_id,'score_total',o.score_total) order by o.posicao) from ordenados o join limites_proximos l on o.posicao between l.inicio and l.inicio+9),'[]'::jsonb),'laws',coalesce((select jsonb_agg(jsonb_build_object('lei_id',lp.lei_id,'slug',lp.slug,'titulo',case when lp.recorte_nome is null then lp.titulo else lp.titulo||' — '||lp.recorte_nome end,'status_publicacao',case when lp.lei_status='em_breve' or lp.recorte_status='em_breve' then 'em_breve' else 'ativa' end,'score',coalesce((select m.melhor_score from melhores m where m.aluno_id=p_aluno_id and m.lei_id=lp.lei_id),0)) order by lp.ordem,lp.lei_id) from leis_produto lp),'[]'::jsonb));$function$;
revoke all on function public.obter_detalhes_records_produto(text,uuid) from public,anon,authenticated; grant execute on function public.obter_detalhes_records_produto(text,uuid) to service_role;
commit;
