begin;

-- O acesso gratuito pode pertencer a um recorte sem tornar a lei inteira
-- pública. Registros existentes conservam false.
alter table public.recortes_leis
  add column if not exists acesso_gratuito boolean not null default false;
comment on column public.recortes_leis.acesso_gratuito is
  'Recorte acessível a qualquer aluno autenticado, sem liberar a lei completa.';

-- Cada campanha continua pertencendo a uma lei; recorte_id só delimita o
-- contexto quando a tentativa foi iniciada por um recorte específico.
alter table public.campanhas_leis_alunos
  add column if not exists recorte_id uuid references public.recortes_leis(id) on delete restrict;

drop index if exists public.campanhas_leis_alunos_ativa_unica_idx;
create unique index if not exists campanhas_leis_alunos_ativa_lei_unica_idx
  on public.campanhas_leis_alunos(aluno_id, lei_id)
  where recorte_id is null and not concluida and not abandonada;
create unique index if not exists campanhas_leis_alunos_ativa_recorte_unica_idx
  on public.campanhas_leis_alunos(aluno_id, lei_id, recorte_id)
  where recorte_id is not null and not concluida and not abandonada;
create index if not exists campanhas_leis_alunos_recorte_idx
  on public.campanhas_leis_alunos(aluno_id, lei_id, recorte_id, concluida, iniciada_em);

-- O progresso do recorte é deliberadamente separado da tabela histórica da
-- lei completa. Assim, uma campanha parcial não substitui nem mistura o
-- progresso já existente para a lei inteira.
create table if not exists public.progresso_recortes_leis_alunos (
  id bigint generated by default as identity primary key,
  aluno_id uuid not null references public.alunos(id) on delete cascade,
  lei_id bigint not null references public.leis(id) on delete cascade,
  recorte_id uuid not null references public.recortes_leis(id) on delete restrict,
  em_estudo boolean not null default false,
  questoes_finalizadas boolean not null default false,
  status_campanha text not null default 'nao_iniciada' check (status_campanha in ('nao_iniciada','em_andamento','concluida')),
  campanha_ativa_id uuid references public.campanhas_leis_alunos(id) on delete set null,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint progresso_recortes_leis_alunos_aluno_lei_recorte_key unique(aluno_id,lei_id,recorte_id),
  constraint progresso_recortes_leis_alunos_estado_coerente_check check (not questoes_finalizadas or em_estudo)
);
create index if not exists progresso_recortes_leis_alunos_lei_idx on public.progresso_recortes_leis_alunos(lei_id,recorte_id,aluno_id);

create or replace function public.validar_contexto_recorte_campanha()
returns trigger language plpgsql set search_path='' as $function$
declare v_lei_id bigint;
begin
  select r.lei_id into v_lei_id from public.recortes_leis r where r.id=new.recorte_id;
  if v_lei_id is null or v_lei_id is distinct from new.lei_id then
    raise exception using errcode='23514',message='O recorte deve pertencer à mesma lei do contexto de estudo.';
  end if;
  return new;
end;
$function$;

drop trigger if exists campanhas_leis_alunos_validar_recorte on public.campanhas_leis_alunos;
create trigger campanhas_leis_alunos_validar_recorte before insert or update of lei_id,recorte_id
  on public.campanhas_leis_alunos for each row when (new.recorte_id is not null)
  execute function public.validar_contexto_recorte_campanha();
drop trigger if exists progresso_recortes_leis_alunos_validar_recorte on public.progresso_recortes_leis_alunos;
create trigger progresso_recortes_leis_alunos_validar_recorte before insert or update of lei_id,recorte_id
  on public.progresso_recortes_leis_alunos for each row
  execute function public.validar_contexto_recorte_campanha();
drop trigger if exists progresso_recortes_leis_alunos_definir_updated_at on public.progresso_recortes_leis_alunos;
create trigger progresso_recortes_leis_alunos_definir_updated_at before update on public.progresso_recortes_leis_alunos
  for each row execute function public.definir_updated_at();

alter table public.progresso_recortes_leis_alunos enable row level security;
revoke all on public.progresso_recortes_leis_alunos from public, anon, authenticated;
revoke all on sequence public.progresso_recortes_leis_alunos_id_seq from public, anon, authenticated;
grant select,insert,update,delete on public.progresso_recortes_leis_alunos to service_role;
grant usage,select,update on sequence public.progresso_recortes_leis_alunos_id_seq to service_role;

-- Assinatura nova; a anterior é mantida para o código já publicado até a
-- aplicação deste release. O RPC administrativo continua validando lei e nós.
create or replace function public.admin_salvar_recorte_lei(
  p_recorte_id uuid,p_lei_id bigint,p_nome text,p_descricao text,p_ativo boolean,
  p_status_publicacao text,p_acesso_gratuito boolean,p_structure_ids bigint[]
) returns uuid language plpgsql security definer set search_path='' as $function$
declare v_id uuid;v_total integer;v_valid integer;v_status text:=coalesce(p_status_publicacao,case when p_ativo then 'ativa' else 'inativa' end);
begin
  if pg_catalog.btrim(coalesce(p_nome,''))='' or v_status not in ('ativa','em_breve','inativa') then raise exception using errcode='22023',message='Dados do recorte invalidos.'; end if;
  if coalesce(p_acesso_gratuito,false) and v_status<>'ativa' then raise exception using errcode='22023',message='Somente recorte ativo pode ter acesso gratuito.'; end if;
  if cardinality(coalesce(p_structure_ids,array[]::bigint[]))=0 then raise exception using errcode='22023',message='Selecione ao menos uma estrutura.'; end if;
  select count(*),count(distinct x) into v_total,v_valid from pg_catalog.unnest(p_structure_ids) x; if v_total<>v_valid then raise exception using errcode='22023',message='Estrutura duplicada no recorte.'; end if;
  select count(*) into v_valid from public.law_structure where lei_id=p_lei_id and ativo and id=any(p_structure_ids); if v_valid<>v_total then raise exception using errcode='22023',message='A estrutura selecionada nao pertence a esta lei.'; end if;
  if p_recorte_id is null then
    insert into public.recortes_leis(lei_id,nome,descricao,ativo,status_publicacao,acesso_gratuito)
    values(p_lei_id,pg_catalog.btrim(p_nome),nullif(pg_catalog.btrim(coalesce(p_descricao,'')),''),v_status<>'inativa',v_status,coalesce(p_acesso_gratuito,false)) returning id into v_id;
  else
    update public.recortes_leis set nome=pg_catalog.btrim(p_nome),descricao=nullif(pg_catalog.btrim(coalesce(p_descricao,'')),''),ativo=v_status<>'inativa',status_publicacao=v_status,acesso_gratuito=coalesce(p_acesso_gratuito,false)
    where id=p_recorte_id and lei_id=p_lei_id returning id into v_id;
    if v_id is null then raise exception using errcode='P0002',message='Recorte nao encontrado para esta lei.'; end if;
    delete from public.recortes_leis_estrutura where recorte_id=v_id;
  end if;
  insert into public.recortes_leis_estrutura(recorte_id,structure_id,lei_id)
    select v_id,x,p_lei_id from pg_catalog.unnest(p_structure_ids) x;
  return v_id;
end;
$function$;
revoke all on function public.admin_salvar_recorte_lei(uuid,bigint,text,text,boolean,text,boolean,bigint[]) from public,anon,authenticated;
grant execute on function public.admin_salvar_recorte_lei(uuid,bigint,text,text,boolean,text,boolean,bigint[]) to service_role;

-- A lei aparece em Minhas Leis quando o aluno tem ao menos um contexto: lei
-- inteira por acesso prévio ou um recorte gratuito ativo.
create or replace function public.obter_minhas_leis()
returns table (id bigint,slug text,titulo text,nome_curto text,descricao text,codigo text,categoria text,thumbnail_url text,ordem integer,fontes_ativas bigint,total_flashcards bigint,versao_material text,revisado_em date,publicado_em date,situacao_atualizacao text,houve_alteracao_legislativa boolean,referencia_normativa_atual text,tipo_referencia_normativa text)
language sql stable security definer set search_path='' as $function$
  with aluno_atual as (select id from public.alunos where user_id=auth.uid()), acessos as (
    select liberacao.lei_id,count(*)::bigint as fontes_ativas from public.liberacoes_leis liberacao join aluno_atual aluno on aluno.id=liberacao.aluno_id where liberacao.status='ativo' group by liberacao.lei_id
  ), visiveis as (
    select lei.id,coalesce(acessos.fontes_ativas,0::bigint) as fontes_ativas
    from public.leis lei left join acessos on acessos.lei_id=lei.id
    where lei.ativo=true and lei.status_publicacao='ativa' and exists(select 1 from aluno_atual)
      and (lei.acesso_gratuito or acessos.lei_id is not null or exists(select 1 from public.recortes_leis r where r.lei_id=lei.id and r.ativo=true and r.status_publicacao='ativa' and r.acesso_gratuito=true))
  )
  select lei.id,lei.slug,lei.titulo,lei.nome_curto,lei.descricao,lei.codigo,lei.categoria,lei.thumbnail_url,lei.ordem,visiveis.fontes_ativas,coalesce(totais.total_flashcards,0::bigint),vigente.versao_material,vigente.revisado_em,vigente.publicado_em,lei.situacao_atualizacao,lei.houve_alteracao_legislativa,case when lei.houve_alteracao_legislativa then lei.ultima_alteracao_referencia else lei.norma_originaria_referencia end,case when lei.houve_alteracao_legislativa then 'alteracao'::text else 'originaria'::text end
  from visiveis join public.leis lei on lei.id=visiveis.id
  left join lateral (select coalesce(sum(material.quantidade_itens),0)::bigint as total_flashcards from public.materiais_leis material where material.lei_id=lei.id and material.ativo=true and material.tipo='flashcards') totais on true
  left join lateral (select material.versao_material,material.revisado_em,material.publicado_em from public.materiais_leis material where material.lei_id=lei.id and material.ativo=true and material.tipo='flashcards' order by material.publicado_em desc nulls last,material.revisado_em desc nulls last,material.ordem,material.id desc limit 1) vigente on true
  order by lei.ordem,lei.titulo,lei.id;
$function$;
revoke all on function public.obter_minhas_leis() from public,anon,authenticated,service_role;
grant execute on function public.obter_minhas_leis() to authenticated;

commit;
