begin;

create table if not exists public.mensagens_conclusao_niveis (
  id bigint generated by default as identity primary key,
  texto text not null,
  ativo boolean not null default true,
  ordem integer not null,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint mensagens_conclusao_niveis_texto_nao_vazio_check check (pg_catalog.btrim(texto) <> ''),
  constraint mensagens_conclusao_niveis_ordem_nao_negativa_check check (ordem >= 0)
);

create index if not exists mensagens_conclusao_niveis_ativas_ordem_idx
  on public.mensagens_conclusao_niveis (ordem asc, id asc)
  where ativo = true;

do $do$
begin
  if not exists (
    select 1 from pg_catalog.pg_trigger
    where tgrelid = 'public.mensagens_conclusao_niveis'::pg_catalog.regclass
      and tgname = 'mensagens_conclusao_niveis_definir_updated_at'
  ) then
    create trigger mensagens_conclusao_niveis_definir_updated_at
      before update on public.mensagens_conclusao_niveis
      for each row execute function public.definir_updated_at();
  end if;
end;
$do$;

alter table public.mensagens_conclusao_niveis enable row level security;
revoke all on table public.mensagens_conclusao_niveis from public, anon, authenticated;
grant select, insert, update, delete on table public.mensagens_conclusao_niveis to service_role;
grant usage, select on sequence public.mensagens_conclusao_niveis_id_seq to service_role;

insert into public.mensagens_conclusao_niveis (texto, ativo, ordem) values
  (E'⚡ Mandou bem! Mais uma etapa vencida.\nSe algum ponto ficou confuso, use o LegisBot antes de continuar.', true, 1),
  (E'🎯 Excelente! Você avançou mais um trecho da lei.\nConfira os Destaques para identificar os pontos que merecem atenção especial.', true, 2),
  (E'🧠 Boa! Mais um nível concluído.\nMesmo quando acertar uma questão, leia a justificativa: pode haver um detalhe importante ali.', true, 3),
  (E'💬 Muito bem! Continue nesse ritmo.\nNa Comunidade, você pode encontrar observações e dúvidas de outros alunos sobre a legislação.', true, 4),
  (E'📜 Mais uma etapa vencida.\nCompare a resposta com o trecho da legislação e descubra o que tornou o item certo ou errado.', true, 5),
  (E'🎧 Excelente progresso!\nQuando houver LegisCast disponível, use o áudio para reforçar o conteúdo em outro momento do dia.', true, 6),
  (E'📄 Mandou bem!\nUse também o PDF esquematizado para enxergar a estrutura da lei e facilitar a revisão.', true, 7),
  (E'🔍 Boa! Você está avançando.\nPreste atenção em palavras como “sempre”, “somente”, “exceto”, “deverá” e “poderá”.', true, 8),
  (E'🧩 Mais um nível concluído!\nQuando encontrar uma exceção, tente lembrar primeiro qual é a regra geral.', true, 9),
  (E'🧠 Excelente!\nAo errar uma questão, procure descobrir qual palavra ou expressão alterou o sentido da regra.', true, 10),
  (E'⚡ Muito bem! Mais uma parte da lei vencida.\nConstância importa mais que velocidade. Continue.', true, 11),
  (E'🎯 Boa!\nTente responder mentalmente antes de revelar a resposta. O esforço de recuperação ajuda na memorização.', true, 12),
  (E'🔁 Mandou bem!\nDepois de concluir a lei, o Estudo Livre pode ser usado para revisitar os pontos que quiser estudar novamente.', true, 13),
  (E'💡 Mais um nível concluído.\nSe surgir uma dúvida sobre o dispositivo, consulte o LegisBot e depois retorne ao estudo.', true, 14),
  (E'🔥 Excelente progresso!\nUma lei grande fica muito menor quando você avança um nível de cada vez.', true, 15);

create or replace function public.admin_criar_mensagem_conclusao_nivel(
  p_ator_user_id uuid, p_texto text, p_ativo boolean, p_ordem integer
)
returns jsonb language plpgsql security definer set search_path = pg_catalog
as $function$
declare v_row public.mensagens_conclusao_niveis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_texto is null or pg_catalog.btrim(p_texto) = '' or p_ordem is null or p_ordem < 0 then
    raise exception using errcode = '22023', message = 'Dados da mensagem de conclusão inválidos.';
  end if;
  insert into public.mensagens_conclusao_niveis (texto, ativo, ordem)
  values (pg_catalog.btrim(p_texto), coalesce(p_ativo, true), p_ordem)
  returning * into v_row;
  perform public.admin_comercial_auditar(p_ator_user_id, 'criar', 'mensagem_conclusao_nivel', v_row.id::text, null, pg_catalog.to_jsonb(v_row));
  return pg_catalog.to_jsonb(v_row);
end;
$function$;

create or replace function public.admin_atualizar_mensagem_conclusao_nivel(
  p_ator_user_id uuid, p_mensagem_id bigint, p_dados jsonb
)
returns jsonb language plpgsql security definer set search_path = pg_catalog
as $function$
declare v_before public.mensagens_conclusao_niveis; v_after public.mensagens_conclusao_niveis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  if p_dados is null or p_dados = '{}'::jsonb or p_dados - array['texto', 'ativo', 'ordem'] <> '{}'::jsonb then
    raise exception using errcode = '22023', message = 'Campos da mensagem de conclusão inválidos.';
  end if;
  if (p_dados ? 'texto' and pg_catalog.btrim(p_dados->>'texto') = '')
    or (p_dados ? 'ordem' and ((p_dados->>'ordem') !~ '^[0-9]+$' or (p_dados->>'ordem')::integer < 0))
    or (p_dados ? 'ativo' and (p_dados->>'ativo') not in ('true', 'false')) then
    raise exception using errcode = '22023', message = 'Dados da mensagem de conclusão inválidos.';
  end if;
  select * into v_before from public.mensagens_conclusao_niveis where id = p_mensagem_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Mensagem de conclusão não encontrada.'; end if;
  update public.mensagens_conclusao_niveis set
    texto = case when p_dados ? 'texto' then pg_catalog.btrim(p_dados->>'texto') else texto end,
    ativo = case when p_dados ? 'ativo' then (p_dados->>'ativo')::boolean else ativo end,
    ordem = case when p_dados ? 'ordem' then (p_dados->>'ordem')::integer else ordem end
  where id = p_mensagem_id returning * into v_after;
  perform public.admin_comercial_auditar(p_ator_user_id, 'atualizar', 'mensagem_conclusao_nivel', p_mensagem_id::text, pg_catalog.to_jsonb(v_before), pg_catalog.to_jsonb(v_after));
  return pg_catalog.to_jsonb(v_after);
end;
$function$;

create or replace function public.admin_excluir_mensagem_conclusao_nivel(p_ator_user_id uuid, p_mensagem_id bigint)
returns jsonb language plpgsql security definer set search_path = pg_catalog
as $function$
declare v_before public.mensagens_conclusao_niveis;
begin
  perform public.admin_comercial_validar_contexto(p_ator_user_id);
  select * into v_before from public.mensagens_conclusao_niveis where id = p_mensagem_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Mensagem de conclusão não encontrada.'; end if;
  delete from public.mensagens_conclusao_niveis where id = p_mensagem_id;
  perform public.admin_comercial_auditar(p_ator_user_id, 'excluir', 'mensagem_conclusao_nivel', p_mensagem_id::text, pg_catalog.to_jsonb(v_before), null);
  return pg_catalog.to_jsonb(v_before);
end;
$function$;

revoke all on function public.admin_criar_mensagem_conclusao_nivel(uuid, text, boolean, integer) from public, anon, authenticated;
revoke all on function public.admin_atualizar_mensagem_conclusao_nivel(uuid, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.admin_excluir_mensagem_conclusao_nivel(uuid, bigint) from public, anon, authenticated;
grant execute on function public.admin_criar_mensagem_conclusao_nivel(uuid, text, boolean, integer) to service_role;
grant execute on function public.admin_atualizar_mensagem_conclusao_nivel(uuid, bigint, jsonb) to service_role;
grant execute on function public.admin_excluir_mensagem_conclusao_nivel(uuid, bigint) to service_role;

commit;
