import Link from "next/link";
import { ArticleSourceConflicts } from "@/components/admin/article-source-conflicts";
import { listArticleSourceConflicts } from "@/lib/admin-article-conflicts-server";
import { listArticleContextLaws, listArticleContexts, searchArticleContexts } from "@/lib/admin-article-center-server";
import { exigirAdministrador } from "@/lib/admin-auth";
import { getSupabaseServerClient } from "@/lib/supabase-server";
import { alterarStatusComentario } from "@/app/admin/actions";
import { moderateCommunityComment } from "@/app/admin/community-actions";
import { LEGISBOT_COMENTARIO_STATUS, type LegisBotComentario } from "@/lib/legisbot-comentario";

export const dynamic = "force-dynamic";
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? "" : value ?? "";
const botStatusLabel = { pendente: "Rascunho / pendente", processando: "Processando", concluido: "Publicado", erro: "Erro" } as const;
const formatCommentDate = (value: unknown) => {
  if (typeof value !== "string") return "Data não informada";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Data não informada" : new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(date);
};

export default async function AdminArticlesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const requestedTab = one(params.aba);
  const tab = requestedTab === "conflitos" ? "conflitos" : requestedTab === "comentarios" ? "comentarios" : requestedTab === "legisbot" ? "legisbot" : "artigos";
  const query = one(params.q);
  const lawFilter = (one(params.lei) || one(params.law)).toLowerCase();
  const orderDirection = one(params.ordem_sort) === "desc" ? "desc" : one(params.ordem_sort) === "recent" ? "recent" : "asc";
  await exigirAdministrador();
  const conflictFilters = { law: lawFilter, type: one(params.tipo) || one(params.type), ordem_sort: orderDirection };
  const conflicts = tab === "conflitos" ? await listArticleSourceConflicts({ ...conflictFilters, page: Number(one(params.pagina)) || 1 }) : null;
  const [results, recentArticles, laws] = tab !== "conflitos"
    ? await Promise.all([query.trim() ? searchArticleContexts(query, lawFilter) : Promise.resolve([]), query.trim() ? Promise.resolve([]) : listArticleContexts(lawFilter), listArticleContextLaws()])
    : [[], [], await listArticleContextLaws()];
  const tabHref = (nextTab: string) => `/admin/artigos?aba=${nextTab}${lawFilter ? `&lei=${encodeURIComponent(lawFilter)}` : ""}&ordem_sort=${orderDirection}${query ? `&q=${encodeURIComponent(query)}` : ""}`;
  const visibleArticles = (query.trim() ? results : recentArticles).toSorted((left, right) => orderDirection === "recent" ? right.updatedAt.localeCompare(left.updatedAt) : orderDirection === "asc" ? left.ordem.localeCompare(right.ordem) : right.ordem.localeCompare(left.ordem));

  return <main className="admin-shell article-center-shell">
    <Link className="admin-central-link" href="/admin">← Central Administrativa</Link>
    <header className="admin-header"><div><div className="admin-eyebrow">Central do Artigo</div><h1>Artigos e dispositivos</h1><p>Os dispositivos derivados das questões são a base; LegisBot, comunidade e conflitos são camadas agregadas.</p></div><Link className="admin-button primary" href="/admin/legisbot/novo">+ Criar conteúdo do LegisBot</Link></header>
    <nav className="article-tabs" aria-label="Áreas da Central do Artigo"><Link className={tab === "artigos" ? "active" : ""} href={tabHref("artigos")}>Artigos</Link><Link className={tab === "legisbot" ? "active" : ""} href={tabHref("legisbot")}>LegisBot</Link><Link className={tab === "comentarios" ? "active" : ""} href={tabHref("comentarios")}>Comentários</Link><Link className={tab === "conflitos" ? "active" : ""} href={tabHref("conflitos")}>Revisões{conflicts ? <span>{conflicts.indicators.pending}</span> : null}</Link></nav>
    <form className="article-context-filter"><input type="hidden" name="aba" value={tab}/>{query ? <input type="hidden" name="q" value={query}/> : null}<label>Lei<select name="lei" defaultValue={lawFilter}><option value="">Todas as leis</option>{laws.map((law) => <option key={law.slug} value={law.slug}>{law.code ? `${law.code} — ` : ""}{law.title}</option>)}</select></label><label>Ordenação<select name="ordem_sort" defaultValue={orderDirection}><option value="asc">Ordem crescente</option><option value="desc">Ordem decrescente</option><option value="recent">Mais recentes</option></select></label><button className="admin-button secondary">Aplicar contexto</button></form>
    {tab === "conflitos" && conflicts ? <ArticleSourceConflicts data={conflicts} filters={conflictFilters} /> : tab === "legisbot" ? <ArticleLegisBotPanel lawFilter={lawFilter} query={query} status={one(params.status)} orderDirection={orderDirection} /> : tab === "comentarios" ? <ArticleCommunityPanel lawFilter={lawFilter} query={query} status={one(params.status)} orderDirection={orderDirection} /> : <>
      <form className="article-search"><input type="hidden" name="aba" value={tab}/><input type="hidden" name="lei" value={lawFilter}/><input type="hidden" name="ordem_sort" value={orderDirection}/><label htmlFor="article-search">Buscar artigo</label><div><input id="article-search" name="q" defaultValue={query} placeholder="Buscar artigo por lei, código, artigo, ordem, título ou assunto..." autoComplete="off"/><button className="admin-button primary">Buscar</button><Link className="admin-button secondary" href={`/admin/artigos?aba=${tab}${lawFilter ? `&lei=${encodeURIComponent(lawFilter)}` : ""}&ordem_sort=${orderDirection}`}>Limpar busca</Link></div></form>
      {visibleArticles.length ? <section aria-live="polite"><h2 className="article-section-title">{query.trim() ? `Resultados para “${query}”` : lawFilter ? "Dispositivos da lei selecionada" : "Dispositivos das questões"}</h2><div className="article-result-list">{visibleArticles.map((item) => <article className="article-result" key={`${item.slug}:${item.ordem}`}><div><strong>{item.lawTitle ?? item.titulo}</strong><p>{item.assunto || `Art. ${item.ordem}`} · ordem {item.ordem}</p><small>{item.lawCode ? `${item.lawCode} · ` : ""}{item.slug} · LegisBot: {item.legisbot ? item.legisbot.status : "—"} · {item.commentsCount} comentário(s) · {item.questionsCount} questão(ões) · {item.conflictsCount} conflito(s) · {item.pendingCount} pendência(s)</small></div><Link className="admin-button secondary" href={`/admin/artigos/${encodeURIComponent(item.slug.toLowerCase())}/${encodeURIComponent(item.ordem)}?lei=${encodeURIComponent(lawFilter || item.slug.toLowerCase())}&ordem_sort=${orderDirection}${query ? `&q=${encodeURIComponent(query)}` : ""}`}>Abrir</Link></article>)}</div></section> : <div className="admin-empty"><h2>Nenhum dispositivo encontrado</h2><p>Não há questões ativas que formem contextos de artigo.</p></div>}
    </>}
  </main>;
}

async function ArticleLegisBotPanel({ lawFilter, query, status, orderDirection }: { lawFilter: string; query: string; status: string; orderDirection: "asc" | "desc" | "recent" }) {
  let request = getSupabaseServerClient().from("legisbot_comentarios").select("*").order(orderDirection === "recent" ? "updated_at" : "ordem", { ascending: orderDirection !== "desc" }).order("id").limit(100);
  if (lawFilter) request = request.eq("slug", lawFilter.toUpperCase());
  if (query.trim()) { const value = `%${query.trim().replace(/[,%()]/g, " ")}%`; request = request.or(`titulo.ilike.${value},slug.ilike.${value},ordem.ilike.${value},assunto.ilike.${value},comentario.ilike.${value}`); }
  if (LEGISBOT_COMENTARIO_STATUS.includes(status as (typeof LEGISBOT_COMENTARIO_STATUS)[number])) request = request.eq("status", status);
  const result = await request;
  if (result.error) throw new Error("Não foi possível carregar os comentários do LegisBot.");
  const records = (result.data ?? []) as LegisBotComentario[];
  return <section><header className="article-comments-heading"><div><h2>Comentários do LegisBot</h2><p>Gestão editorial por artigo, preservando a lei selecionada.</p></div><Link className="admin-button primary" href={`/admin/legisbot/novo${lawFilter ? `?lei=${encodeURIComponent(lawFilter)}` : ""}`}>+ Criar conteúdo do LegisBot</Link></header><form className="admin-filters article-tab-filters"><input type="hidden" name="aba" value="legisbot"/><input type="hidden" name="lei" value={lawFilter}/><input type="hidden" name="ordem_sort" value={orderDirection}/><label>Status<select name="status" defaultValue={status}><option value="">Todos</option>{LEGISBOT_COMENTARIO_STATUS.map((item) => <option key={item} value={item}>{botStatusLabel[item]}</option>)}</select></label><label className="admin-search">Buscar<input name="q" defaultValue={query} placeholder="Título, assunto, ordem ou conteúdo"/></label><div className="admin-filter-actions"><button className="admin-button primary">Filtrar</button><Link className="admin-button secondary" href={`/admin/artigos?aba=legisbot${lawFilter ? `&lei=${encodeURIComponent(lawFilter)}` : ""}&ordem_sort=${orderDirection}`}>Limpar busca</Link></div></form>{records.length ? <div className="article-result-list">{records.map((item) => { const publicUrl = `/legisbot/${encodeURIComponent(item.slug.toLowerCase())}/${encodeURIComponent(item.ordem)}`; const nextStatus = item.status === "concluido" ? "pendente" : "concluido"; const contextUrl = `/admin/artigos/${encodeURIComponent(item.slug.toLowerCase())}/${encodeURIComponent(item.ordem)}?aba=legisbot&lei=${encodeURIComponent(lawFilter || item.slug.toLowerCase())}`; return <article className="article-result" key={item.id}><div><strong>{item.titulo}</strong><p>{item.assunto} · ordem {item.ordem}</p><small>{item.slug} · <span className={`admin-status status-${item.precisa_revisao ? "erro" : item.status}`}>{item.precisa_revisao ? "Precisa de revisão" : botStatusLabel[item.status]}</span></small></div><div className="article-header-actions"><Link className="admin-button secondary" href={contextUrl}>Editar</Link>{item.status === "concluido" ? <Link className="admin-button secondary" href={publicUrl} target="_blank">Página pública</Link> : null}<form action={alterarStatusComentario}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="status" value={nextStatus}/><button className="admin-button primary">{nextStatus === "concluido" ? "Publicar" : "Rascunho"}</button></form></div></article>; })}</div> : <div className="admin-empty"><h2>Nenhum conteúdo do LegisBot encontrado</h2><p>Use os filtros ou crie um conteúdo para esta lei.</p></div>}</section>;
}

async function ArticleCommunityPanel({ lawFilter, query, status, orderDirection }: { lawFilter: string; query: string; status: string; orderDirection: "asc" | "desc" | "recent" }) {
  let request = getSupabaseServerClient().from("legisbot_comentarios_comunidade").select("*").order("created_at", { ascending: orderDirection === "asc" }).limit(100);
  if (lawFilter) request = request.eq("slug", lawFilter.toUpperCase());
  if (query.trim()) { const value = `%${query.trim().replace(/[,%()]/g, " ")}%`; request = request.or(`slug.ilike.${value},ordem.ilike.${value},conteudo.ilike.${value}`); }
  if (["publicado", "em_analise", "oculto", "removido"].includes(status)) request = request.eq("status", status);
  const result = await request;
  if (result.error) throw new Error("Não foi possível carregar os comentários da comunidade.");
  return <section><header className="article-comments-heading"><div><h2>Comentários da comunidade</h2><p>Moderação administrativa da lei selecionada.</p></div></header><form className="admin-filters article-tab-filters"><input type="hidden" name="aba" value="comentarios"/><input type="hidden" name="lei" value={lawFilter}/><input type="hidden" name="ordem_sort" value={orderDirection}/><label>Status<select name="status" defaultValue={status}><option value="">Todos</option><option value="publicado">Publicado</option><option value="em_analise">Em análise</option><option value="oculto">Oculto</option><option value="removido">Removido</option></select></label><label className="admin-search">Buscar<input name="q" defaultValue={query} placeholder="Ordem ou conteúdo"/></label><div className="admin-filter-actions"><button className="admin-button primary">Filtrar</button><Link className="admin-button secondary" href={`/admin/artigos?aba=comentarios${lawFilter ? `&lei=${encodeURIComponent(lawFilter)}` : ""}&ordem_sort=${orderDirection}`}>Limpar busca</Link></div></form>{(result.data ?? []).length ? <div className="article-result-list">{(result.data ?? []).map((item) => <article className="article-result" key={String(item.id)}><div><strong>{String(item.slug)} · ordem {String(item.ordem)}</strong><p>{item.conteudo ? String(item.conteudo) : "Comentário removido."}</p><small><span className={`admin-status status-${String(item.status)}`}>{String(item.status)}</span> · Comentado em {formatCommentDate(item.created_at)}</small></div><div className="article-header-actions">{String(item.status) !== "removido" ? <>{["publicado", "em_analise", "oculto", "removido"].map((nextStatus) => <form action={moderateCommunityComment} key={nextStatus}><input type="hidden" name="id" value={String(item.id)}/><input type="hidden" name="status" value={nextStatus}/><button className="admin-button secondary">{nextStatus === "publicado" ? "Restaurar" : nextStatus === "em_analise" ? "Analisar" : nextStatus === "oculto" ? "Ocultar" : "Remover"}</button></form>)}</> : null}</div></article>)}</div> : <div className="admin-empty"><h2>Nenhum comentário encontrado</h2><p>Ajuste os filtros ou aguarde novas participações.</p></div>}</section>;
}
