-- EXECUTAR SOMENTE NO SQL Editor DO STAGING VAZIO.
-- Não executar no principal de produção. Não cria alunos, compras, acessos ou campanhas.
begin;

create or replace function public.definir_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $function$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$function$;

revoke all on function public.definir_updated_at() from public, anon, authenticated;
grant execute on function public.definir_updated_at() to service_role;

create table if not exists public.leis (
  id bigint generated by default as identity primary key,
  slug text not null,
  titulo text not null,
  nome_curto text,
  descricao text,
  codigo text,
  categoria text,
  ativo boolean not null default true,
  ordem integer not null default 0,
  thumbnail_url text,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint leis_slug_normalizado_check check (
    slug = pg_catalog.lower(pg_catalog.btrim(slug))
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
  ),
  constraint leis_titulo_nao_vazio_check check (pg_catalog.btrim(titulo) <> ''),
  constraint leis_ordem_check check (ordem >= 0),
  constraint leis_slug_key unique (slug)
);

create index if not exists leis_ativo_ordem_idx on public.leis (ativo, ordem, id);
create index if not exists leis_categoria_idx on public.leis (categoria) where categoria is not null;

drop trigger if exists leis_definir_updated_at on public.leis;
create trigger leis_definir_updated_at
  before update on public.leis
  for each row execute function public.definir_updated_at();

alter table public.leis enable row level security;
revoke all on public.leis from public, anon, authenticated;
revoke all on sequence public.leis_id_seq from public, anon, authenticated;
grant all privileges on public.leis to service_role;
grant usage, select, update on sequence public.leis_id_seq to service_role;

insert into public.leis (slug, titulo, ativo, ordem)
values (
  'l14751',
  'Lei 14.751 (Lei Orgânica das Polícias Militares e Corpos de Bombeiros Militares)',
  true,
  0
)
on conflict (slug) do nothing;

commit;
